### ISSUE TITLE
SparkleShare folder location selection

### ISSUE THREAD

**Issue by mrtnmueller** [hbons/SparkleShare#1028]
SparkleShare should allow users to set their share folders, for example I have my Dropbox folder on partition D: because C: is reserved for System and Applications. While SparkleShare tells me that it will create a folder for me during installation, it won't let me select where.

**Comment by kevincox** [comment]
I'm just going to chime in and say that being able to have projects at arbitrary locations would be really nice. Symlinks work but are more annoying to set up then just cloning to the first place first time.

**Comment by mray** [comment]
I also want to chime in to say that a different folder per repository is needed.

**Comment by heikobornholdt** [comment]
👍

**Comment by aadfPT** [comment]
👍

**Comment by IsaacMorris1980** [comment]
@hbons  For windows would it be ok to check available drive space in users directory and if running low (eg. remaining size <10GB(this should be configurable per machine) for a new popup to inform the user about the harddrive space and allow for folder location to be changed?

**Comment by hbons** [comment]
Now tracked in #1819.
