### ISSUE TITLE
How to debug problems in SparkleShare (Wiki text?)

### ISSUE THREAD

**Issue by antonyanimator** [hbons/SparkleShare#1132]
Hi there,

I recently installed the new ubuntu 12.10. I'm did a complete format. Therefore I am building from Sparkleshare from scratch again. I have my own server which I use and has ss projects on. However I'm struggling to add projects to ubuntu. I'm certain it is just a ssh configuration problem, but I always forget where the log files for sparkleshare are to allow me see what the problem is as I don't want to bother you guys with an issue that isn't an issue.

Anyway, could somebody add a wiki page with the sparkleshare log file locations so I can debug the problem I'm having now and probably in the futre

Thanks!

**Comment by rob-hills** [comment]
This is great EXCEPT when Sparkleshare won't run at all.  A colleague running windows has been running Sparkleshare for nearly a year now when suddenly it stopped working.  He can't start it to access the "About" dialog.  I have to go to his home tomorrow to help him debug.  Where is the log on Windows?  It would be nice if it was in the Wiki too!!

Looking at my Ubuntu setup, I see the logs are in ~.config/sparkleshare/logs and the Windoze Sparkleshare config folder is %APPDATA%\sparkleshare\  so I'm hoping I'll find his logs in %APPDATA%\sparkleshare\logs ???

**Comment by rob-hills** [comment]
OK, this seems to be a problem again.
I am now running SparkleShare on Ubuntu 20.04 via flatpack.  When I click the "About Sparkleshare" menu item from the dropdown menu you get by clicking on the indicator at the top of the screen, there is no obvious information about the log file on the splash screen.  Some of the text on the splash dialog overflows the right-hand edge of the screen, so I am wondering if the log file info is also present but off the bottom of the splash dialog?  Unfortunately there seems no way of resizing the the splash dialog to find out!
And again I can't find where the log files are, so I think a Wiki reference **_would_** be useful!

**Comment by rob-hills** [comment]
OK, for anyone else searching for this, if you're running SparkleShare on Ubuntu via FlatPack, the default location the SparkleShare log files seems to be: ~/.config/org.org.sparkleshare.SparkleShare/logs
