### ISSUE TITLE
Support for host-key types other than RSA

### ISSUE THREAD

**Issue by awehrfritz** [hbons/SparkleShare#1157]
Hei!

I'm setting up a repo and my server (at a university) provides only a DSA host-key.
Thus the command "ssh-keyscan -t rsa -p 22 my.server.net" returns "no hostkey alg".
When setting the key-type to DSA ("ssh-keyscan -t dsa -p 22 my.server.net") I get a proper host-key.

Also when setting up the repo manually (which is rather cumbersome) everything works just fine.

Could you implement an option to use also other types than RSA or at least add DSA as an option.

Best regards,
Armin

P.S.: Thanks otherwise for this great utility, I already start to like this software! :)

**Comment by hbons** [comment]
SparkleShare now has an experimental CLI and support for ED25519 (the new default) keys: https://github.com/hbons/Twinkle.

If you like this work and want to support development, I’m looking for sponsors since I’m currently jobless: https://github.com/sponsors/hbons.
