### ISSUE TITLE
git status --porcelain command started repeatedly

### ISSUE THREAD

**Issue by stuckless** [hbons/SparkleShare#1170]
Ubuntu 12.10 32bit running SparkleShare 1.0

A randome times, i notice my computer is starting to act sluggish and I do a top and I see "mono" consuming 150-200% cpu and when I check the sparkleshare log I see 1000s of git status --porcelain commands.  There is nothing else in the logs except for normal updates, and then 1000s of git status --porcelain commands and they keep on coming at a rate of about 2 a second.

When I issue a restart, it seems to fix the issue, temporarily.

**Comment by elliotkendall** [comment]
I'm still seeing this issue with Ubuntu 15.04's package, 1.2-0.1ubuntu1. It runs a continuous loop starting with "git status --porcelain", containing a lot of "Don't know what to do with" errors for conflicts, and finally ending with "Failed to resolve conflict, trying again...: Could not find a part of the path...at System.IO.File.SetAttributes (System.String path, FileAttributes fileAttributes) [0x00000] in <filename unknown>:0 
  at SparkleLib.Git.SparkleRepo.ResolveConflict () [0x00000] in <filename unknown>:0 
  at SparkleLib.Git.SparkleRepo.get_branch () [0x00000] in <filename unknown>:0"

I can provide a full copy of the output, but it contains semi-sensitive file names so I'd prefer to do it privately.
