### ISSUE TITLE
Terminal Client (No GUI)

### ISSUE THREAD

**Issue by cj** [hbons/SparkleShare#1240]
Hi,

I have SparkleShare installed on my server as the host, but I also want to attach it as a client so apache can server the files.  Is it possible to run the client just in the terminal with no GUI interface?

p.s. thank you for this great app :D

**Comment by macedd** [comment]
> sadly nobody hasn't looked into making a headless SparkleShare command yet (it should not be too hard), but i'm not interested in doing this myself. you could have a look at dvcs-autosync, which is a command line tool for syncing Git repos or similar.

@hbons can you point at the right direction? I would be looking into it if possible.
