### ISSUE TITLE
Recipe PortableApps.com

### ISSUE THREAD

**Issue by viegelinsch** [hbons/SparkleShare#1260]
Hi,

a recipe for a PortableApps Installer would be great.
I would like to place SparkleShare client and files on a USB-Stick to have it with me.
Manually triggering the sync is no problem as long as it is easy. ;-)

Any information helping me to setting it up manually welcome.

Regards
viegelinsch

**Comment by gerhard-tinned** [comment]
PortableApps in that context means that the application and its configuration and data can be held on a usb stick. And even after running it, there shall be no trace left on the system itself (only on the usb stick).

**Comment by gerhard-tinned** [comment]
As far as i can tell, SparkleShare is not making use of the registry. That would make it easier as the reg. Entries handling is not required. 

What will be an issue to deal with is the location for the config files. My understanding is that those are in a predefined location in the users home directory. 

I believe by changing some environment variables befor lauschig Sparkleshare, that could be controlled. 

I am as well interested in this approach but my expiriences with those installer scripts used are very old. Someone out there willing to play with that?
