### ISSUE TITLE
Windows: Could not start ssh-agent

### ISSUE THREAD

**Issue by dakky** [hbons/SparkleShare#1286]
Hello 

I have the following problem:

Sparkleshare does not start up.

Debug log says:
19:05:39 | Controller | Could not start ssh-agent:

There is one sparkleshare process and one ssh-add.exe process. When killing the ssh-add.exe, i have the sparkleshare works fine again.
Normally i use peagent as ssh agent. in order exclude an putty/peagent issue, i switched the agent off. 
Same result: sparkleshare does only start when i kill the ssh-add.exe.

Any idea whats wrong? anything else i can test?

**Comment by tobitech** [comment]
I'm trying to debug and compile SparkleShare in Visual Studio, when I click the Start debug button nothing happens. it starts debugging and just terminates and nothing else happen. how do i fix this issue?

**Comment by tobitech** [comment]
I also want to modify the code so that sparkleshare does not asked for server url, but to have a constant server url link whenever it is opened

**Comment by Kernald** [comment]
Please open new issues for your specific problems, if some doesn't exist, but don't hijack totaly unrelated ones.

**Comment by hbons** [comment]
oops, closed the wrong issue.

**Comment by BarryThePenguin** [comment]
Wasn't this already closed? Dec 1, 2013
