### ISSUE TITLE
error: Could not fetch host key - OS X 10.8.4

### ISSUE THREAD

**Issue by ghost** [hbons/SparkleShare#1337]
Hi,

i'm trying to configure git on my Mac.
Have setup my debian machine via dazzle commands.

Now i'm getting the following error in debug_log.txt:

09:07:55 | Auth | Imported key '/Users/pm/.config/sparkleshare/2013-06-28_10h31.key'
09:07:55 | Auth | The following keys may be used:
2048 ed:5b:81:e6:b0:84:f2:e2:1f:29:c7:a7:cf:06:66:53 /Users/pm/.config/sparkleshare/2013-06-28_10h31.key (RSA)
1024 c9:2a:db:d5:04:ef:22:41:35:84:96:2d:4a:84:c6:22 /Users/pm/.ssh/id_dsa (DSA)
4096 13:0b:f5:57:7e:64:a5:71:a0:35:ba:47:8c:20:4e:ff /Users/pm/.ssh/id_rsa (RSA)
09:08:08 | Fetcher | /Users/pm/SparkleShare/.tmp/PROJECT_NAME | Fetching folder: ssh://storage@195.145.198.234/home/storage/PROJECT_NAME
09:08:08 | Auth | Fetching host key for 195.145.198.234
09:08:08 | Cmd | ssh-keyscan -t rsa -p 22 195.145.198.234
09:08:08 | Cmd | ssh-keyscan -t dsa -p 22 195.145.198.234
09:08:08 | Cmd | ssh-keyscan -t ecdsa -p 22 195.145.198.234
09:08:08 | Auth | Could not fetch host key
09:08:09 | Fetcher | Failed

When i try "ssh-keyscan -t ecdsa -p 22 195.145.198.234" i get the following error:
[pm@pm] .../pm/.config/sparkleshare (0)$ ssh-keyscan -t ecdsa -p 22 195.145.198.234
unknown key type ecdsa

Can you help me?

Thanks,
Regards,
Patrick

**Comment by hbons** [comment]
SparkleShare now has an experimental CLI and support for ED25519 (the new default) keys: https://github.com/hbons/Twinkle.

If you like this work and want to support development, I’m looking for sponsors since I’m currently jobless: https://github.com/sponsors/hbons.
