### ISSUE TITLE
MacOS. Authentication Error after keychain automatic locking.

### ISSUE THREAD

**Issue by DoctorJazz** [hbons/SparkleShare#1411]
I've spent few hours tracking down this issue and here is what I found -- when you enable feature in Keychain to automatically lock your keychains after specified period of time, sparkshare reports Authentication Failed after keychains lock themselves. 

![screen shot 2013-10-27 at 1 08 48 am](https://f.cloud.github.com/assets/5784621/1415132/123ed234-3edf-11e3-8cfa-405d2d6ef891.png)
![screen shot 2013-10-27 at 1 06 51 am](https://f.cloud.github.com/assets/5784621/1415135/190657f4-3edf-11e3-9b89-7854018d7cdc.png)

**Comment by hbons** [comment]
I know this is a very old issue. but wanted to comment anyway. :)
v2 uses its own contained SSH configuration, so weird stuff like this will no longer happen.
