### ISSUE TITLE
Can SparkleShare do one-way sync?

### ISSUE THREAD

**Issue by korenmiklos** [hbons/SparkleShare#1422]
We would like to use SparkleShare for sharing data within our projects. Clients would read updates automatically but we want to disallow clients to push any changes to the data repository. Is it possible to teak SparkleShare to do this? Thanks!

**Comment by daraul** [comment]
I wanted to set sparkleshare to only pull from my git repositories, and never push. My main problem is usually having to `git merge` because I'll forget to `pull` before I `commit`.

**Comment by hbons** [comment]
SparkleShare now has an experimental CLI and read-only mode: https://github.com/hbons/Twinkle.

If you like this work and want to support development, I’m looking for sponsors since I’m currently jobless: https://github.com/sponsors/hbons.
