### ISSUE TITLE
Official Debian/Ubuntu PPA

### ISSUE THREAD

**Issue by hbons** [hbons/SparkleShare#1458]
help appreciated!

**Comment by pathumego** [comment]
@hbons Is this not happening any time soon?

**Comment by aggsol** [comment]
What is meant by "official"? Official by SparkleShare or offcial by Ubuntu?

**Comment by akuckartz** [comment]
:+1: for a package in Debian main.

**Comment by hbons** [comment]
This is now obsolete with a Flatpak in progress.
