### ISSUE TITLE
Long Path Support

### ISSUE THREAD

**Issue by Silvenga** [hbons/SparkleShare#1481]
Windows has supported long paths (32K characters) for many years now. Sparkleshare (running on .Net) also has access to long paths. I do understand that msysgit only supports 260 characters (MAX_PATH) - however, Cygwin Git can handle 4k characters (limited by Git itself to 1K). 

It seems like we should, as a committee, start supporting long file paths. How feasible would it to switch to Cygwin Git (since we do not need the Git tools provided by msysgit)

**Comment by hbons** [comment]
closing this. this will be fixed when we bundle a new msysgit.

**Comment by BarryThePenguin** [comment]
Which msysgit will be used?

**Comment by hbons** [comment]
latest.
