### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by megies** [hbons/SparkleShare#1485]
I've been using SparkleShare for several months now and didn't have big problems with it so far, which is a pretty strong positive statement for this kind of a "background" service. However, the need for syncing with Android is getting stronger, and this might become a reason for performing a switch to another system.

The only mention of Android I can find in here is #997 and the notification about discontinuation at https://github.com/NewProggie/SparkleShare-Android/issues/83#issuecomment-15164491.

Are there any plans for Android?

**Comment by benjaminoakes** [comment]
While I would also like a purpose-built SparkleShare client for Android, I have been using [SGit](https://play.google.com/store/apps/details?id=me.sheimi.sgit) in the meantime.  It's an Android Git client that works pretty well.  You have to pull, commit, and push yourself, but it gives you access to information you have in a Git repo while using your mobile device.  I've found it especially helpful for synchronizing notes (e.g., Markdown files).

**Comment by daraul** [comment]
Interesting, @benjaminoakes. Does your sparkleshare client on desktop simply pull commits made on Android? I don't mind doing the same thing, honestly.

**Comment by benjaminoakes** [comment]
Haven't been using it recently, but that's what I recall.  Looks like [MGit has replaced SGit](https://github.com/maks/MGit)
