### ISSUE TITLE
Windows client crashes if folder from folders_path not available.

### ISSUE THREAD

**Issue by olegstepura** [hbons/SparkleShare#1492]
Windows client crashes on start if folder from folders_path not available. Seems like `System.IO.DirectoryNotFound` is thrown and not catched.

Suggested behaviour - run in suspended mode, waiting for directory to become available, maybe a grey icon should be visible in tray.

Background:
If I wish to store synced files on an encrypted drive + wish to run SparkleShare on boot - encrypted drive will appear after SparkleShare is launched (it almost always would be mounted manually after boot).

**Comment by hbons** [comment]
Now tracked in #1819.
