### ISSUE TITLE
Mac Os X 10.9 Sparkleshare crash

### ISSUE THREAD

**Issue by sasin91** [hbons/SparkleShare#1511]
I'm getting the following error:
15/05/14 18.47.24,853 com.apple.launchd.peruser.501[143]: (org.sparkleshare.sparkleshare.53360[36355]) Exited with code: 1

every time i'm trying to add a remote repository hosted on my Ubuntu 14.04LTS server, the repo is created with Dazzle script.

I am willing to help/try debugging as far as my skills go, i have Xcode installed.

**Comment by hbons** [comment]
This is a pretty old issue now... Sorry I didn't got to help sort this out.
I think the latest version will probably have solved this by now along with many other improvement.
If you're still interested in using SparkleShare, check that one out.
