### ISSUE TITLE
change credit wrong

### ISSUE THREAD

**Issue by gimmixAT** [hbons/SparkleShare#1514]
Sometimes the change of a file is credited to the wrong user. My guess is that this is due to a committed merge of recent local and remote changes which makes the merging user the author of all the remote changes.

I am using the 1.4 release on multiple OSX 10.9 machines.

**Comment by gerhard-tinned** [comment]
Saw a similar behaviour. I am not 100% sure but it looked like all changes where showN as the user whi initially committed the file.

**Comment by markusstoll** [comment]
I just observed this behaviour. It occurs, when you change two files in the same repo simultaneously, one on computer A (using user1) and one on computer B (using user2)

the change history for this scenario  gives you a split and a merge into HEAD, like this:

*   ffa1462 (HEAD, master) Merge branch 'master' of <repo>
|\  
| * 8b7e27c < ‘New Folder/’ > ‘Folder1/’ 
* | ed55165 / ‘Documents/document1.txt’
|/  

Sparkleshares "Recent changes" view merges both changes into one changeset attributed to the user that caused the first change (in the given example the lower one), which does not reflect the real scenario.

By using the git command line, its no problem to identify all check in details correctly, so I guess it should be possible to fix this issue in the "Recent changes" view.

**Comment by hbons** [comment]
@markusstoll right, it looks like the merging behaviour broke. SparkleShare used to rebase changes, but now does a normal merge to avoid some other problems with case in file names. i think it broke because of that reason.

**Comment by hbons** [comment]
@markusstoll how would you normally go about this keeping the author information intact?

**Comment by markusstoll** [comment]
:-) well, I have to take a deep look into the current implementation of "Recent Changes"...

**Comment by markusstoll** [comment]
See my pull request #1604 - I would say, this should do the trick

**Comment by hbons** [comment]
fixed by #1604.
