### ISSUE TITLE
UI for generating a public/private SSH key-pair

### ISSUE THREAD

**Issue by knocte** [hbons/SparkleShare#1525]
Some days ago I talked about this with @hbons in IRC.

If the user that has installed SparkleShare client is not tech-savy, it's very likely that he doesn't have any key yet in his .ssh folder (or he hasn't got an .ssh folder at all).

So it would be nice that SparkleShare would generate this, to make it easier for the process of creating an account in $server, where that account only allows certain authorized_keys.

BTW, while thinking about this feature, I've realised that SparkleShare client installation (at least in Windows, where I tested the last time) gives the user info about an SSH key, but I don't know:
* What's the purpose of it?
* Where is it stored? (I didn't find it in the .ssh folder.)
* Is it public or private?

Thanks

**Comment by knocte** [comment]
> Shouldn't the client ID be the SSH key fingerprint instead? The key itself has a technical relevance for
> authentication and must not be disguised as ID.

I agree.

> it doesn't have any relevance for the target audience, and people who do know what a keypair is

I think @aggsol is not asking you to change the wording. You would still keep the same text in your SparkleShare UI, that is, "here's your unique client ID...", but SparkleShare would show the contents of your id_rsa.pub (in case there's one in your account) instead of generating a new one.

> @knocte sorry, but i still don't understand what you're talking about... we should probably discuss this in person at the hackfest? :)

Seems like it's harder and harder to organize a hackfest these days, I miss them :(

So I'll try to be crystal clear this time.

First, let's not talk about SparkleShare for a second. Let's say you sign up with github, and create a repository there. When cloning your repository to a Linux machine, you're offered 2 ways to do this: HTTPS and SSH. When you choose HTTPS, you're prompted for your user and password every time you try to do any operation (clone, pull, push, etc.).

But you can decide to use SSH. If you want to go this route, then you generate an SSH keypair in your Linux machine. By doing this, a $HOME/.ssh/ folder gets created and 2 files get generated there. One is called "id_rsa", which is your private key. The other is called "id_rsa.pub" which is your public key. Then you change your github-profile settings to add the contents of your "id_rsa.pub" as your SSH public key. Whenever you have done this, now you can clone/pull/push your github repos without the need of typing your username and password everytime, because you're using SSH authentication. I hope you're following me up until here :)

Now let's imagine your a happy github+SSH user, and suddenly you discover SparkleShare, the perfect collaboration tool! Then you go and install it with the desire of using it seamlessly with your github repositories (so that you don't need to commit/push/pull manually anymore). But what happens?

1. When installing SparkleShare, the UI tells you a clientID that is basically a public key, but which is not the same one as your id_rsa.pub one.
2. When configuring SparkleShare to use the URL of one of your github repos, it will not use your existing SSH credentials, so then it fails.

Do you understand the problem now? If yes, please reopen the issue :) (Or create a new one with better wording, if you prefer.)

**Comment by hbons** [comment]
@knocte Yes, so I want to move away from this model where you have to upload the SSH key manually. It should be as easy as entering your GitHub/GitLab/Bitbucket credentials and selecting your repo(s) from a list.

For your own server you still need to upload manually of course and this can probably be renamed SSH Public Key instead of Client ID now.

The next release will also have a self-contained SSH configuration to prevent conflicts with other apps. So the shared ssh-agent support is going away entirely.
