### ISSUE TITLE
Could not fetch host key on windows

### ISSUE THREAD

**Issue by grobmeier** [hbons/SparkleShare#1533]
My colleague is on windows and I want her to collaborate with me on a repository. It actually worked a while before, but suddenly it stopped.

She tried to recreate the project with BitBucket and a remote path like:
/org/repos.de.git

The result is attached:

![sparkleshare](https://cloud.githubusercontent.com/assets/873786/3527004/eda71132-0780-11e4-8cb7-a45b7d07c8be.png)

We have checked the Client Key, she got access on bitbucket for the project.

Any advise how we can solve that?

Just for the record, I run SparkleShare successfully for the same repos, just on a mac.

Thanks!

**Comment by gerhard-tinned** [comment]
I have the same issue. On MacOSX and Linux it works perfectly. On the Windows PC of a friend it shows the exact same error. 

I have to check, but i think the is no other ssh key on that system.

**Comment by hbons** [comment]
SparkleShare 2.0 will have its own SSH configuration and should fix this. I'm pretty sure this is due to SparkleShare not using the right key at the right moment.
