### ISSUE TITLE
new type of crash

### ISSUE THREAD

**Issue by markusstoll** [hbons/SparkleShare#1546]
This new kind of crash occured when SparkleShare had to deal with changes while the WIFI was not functional.

This crash occured when using a version built manually on current unreleased version (ef4776b60800a57e42f0b546d3a6a368451e5040) - so it might very well be due to a problem in a background thread.

I am still researching and have no clue, what happened in SparkleShare
# Markus

SparkleShare version: 1.4.0 (
Operating system:     MacOSX (Unix 14.0.0.0)
System.ArgumentException: GCHandle value belongs to a different domain
  at System.Runtime.InteropServices.GCHandle.op_Explicit (IntPtr value) [0x00000] in <filename unknown>:0 
  at System.Runtime.InteropServices.GCHandle.FromIntPtr (IntPtr value) [0x00000] in <filename unknown>:0 
  at MonoMac.Foundation.NSObject.SwitchGCHandle (Boolean to_weak) [0x00000] in <filename unknown>:0 
  at MonoMac.Foundation.NSObject.RetainTrampoline (IntPtr this, IntPtr sel) [0x00000] in <filename unknown>:0 
  at (wrapper native-to-managed) MonoMac.Foundation.NSObject:RetainTrampoline (intptr,intptr)
17:05:59 | <repo1> | Next reconnect attempt in 8 seconds
17:05:59 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: No such host is known
17:05:59 | <repo3> | Falling back to regular polling
17:05:59 | <repo1> | Falling back to regular polling
17:05:59 | <repo2> | Falling back to regular polling
17:06:00 | Cmd | <repo1> | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
17:06:00 | Cmd | <repo2> | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
17:06:00 | Cmd | <repo3> | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
17:06:01 | Local | <repo3> | Activity detected, waiting for it to settle...
17:06:02 | Cmd | <repo1> | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
17:06:02 | Cmd | <repo2> | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
17:06:03 | Local | <repo3> | Activity has settled
17:06:04 | Cmd | <repo3> | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
17:06:07 | <repo1> | Next reconnect attempt in 16 seconds
17:06:07 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: No such host is known
17:06:07 | <repo3> | Falling back to regular polling
17:06:07 | <repo1> | Falling back to regular polling
17:06:07 | <repo2> | Falling back to regular polling
17:06:17 | Cmd | <repo1> | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
17:06:17 | Cmd | <repo2> | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
17:06:17 | Cmd | <repo3> | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
17:06:17 | Local | <repo3> | Activity detected, waiting for it to settle...
17:06:20 | Local | <repo3> | Activity has settled
17:06:20 | Cmd | <repo3> | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
17:06:23 | <repo1> | Next reconnect attempt in 32 seconds
17:06:23 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: No such host is known
17:06:23 | <repo3> | Falling back to regular polling
17:06:23 | <repo1> | Falling back to regular polling
17:06:23 | <repo2> | Falling back to regular polling
17:06:51 | Listener | Trying to reconnect to tcp://notifications.sparkleshare.org:443/
17:06:51 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: No such host is known
17:06:51 | <repo3> | Falling back to regular polling
17:06:51 | <repo1> | Falling back to regular polling
17:06:51 | <repo2> | Falling back to regular polling
17:06:55 | <repo2> | Falling back to regular polling
17:06:55 | <repo2> | Next reconnect attempt in 2 seconds
17:06:56 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: No such host is known
17:06:56 | <repo3> | Falling back to regular polling
17:06:56 | <repo1> | Falling back to regular polling
17:06:56 | <repo2> | Falling back to regular polling
17:06:57 | <repo2> | Next reconnect attempt in 4 seconds
17:07:00 | Listener | Subscribing to channel 4e241f9343b025725521a91490a751c738575840 on tcp://notifications.sparkleshare.org:443/
17:07:00 | Listener | Subscribing to channel ab29da3868f8270fe982fca723dad22b3836b977 on tcp://notifications.sparkleshare.org:443/
17:07:00 | Listener | Subscribing to channel 36f94e92de9e3a68883012fcc1e90d5ecc0286f2 on tcp://notifications.sparkleshare.org:443/
17:07:00 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
17:07:01 | Listener | Subscribing to channel 4e241f9343b025725521a91490a751c738575840 on tcp://notifications.sparkleshare.org:443/
17:07:01 | Listener | Subscribing to channel ab29da3868f8270fe982fca723dad22b3836b977 on tcp://notifications.sparkleshare.org:443/
17:07:01 | Listener | Subscribing to channel 36f94e92de9e3a68883012fcc1e90d5ecc0286f2 on tcp://notifications.sparkleshare.org:443/
17:07:01 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/

**Comment by hbons** [comment]
Closing this as the listener code has been disabled until it's replaced with a cloud service (see #1775).
