### ISSUE TITLE
git: shallow repositories

### ISSUE THREAD

**Issue by BarryThePenguin** [hbons/SparkleShare#1577]
The latest git documentation mentions `--update-shallow` on `git fetch` and `git pull` commands

[Fetch](http://git-scm.com/docs/git-fetch) and [Pull](http://git-scm.com/docs/git-pull)

That's as far as I've got, so I'm curious as to if this will fix the problems people have with the shallow clones?

**Comment by hbons** [comment]
tested this, doesn't make a difference.
