### ISSUE TITLE
V1.5 preview / Update after wakeup

### ISSUE THREAD

**Issue by markusstoll** [hbons/SparkleShare#1578]
After waking up my laptop, SparkleShare did not sync the latest changes

in the logs I see "Checking for remote changes" for the repository where I had remote changes, but SparkleShare did not see/pull the changes

after quiting / restarting, SparkleShare did pull the changes

Observed on SparkleShare V1.5.0 preview on Mac OSX 10.10

**Comment by hbons** [comment]
Let's track this in #1693.
