### ISSUE TITLE
Crash on Windows 8.1 while adding a hosted project

### ISSUE THREAD

**Issue by progician** [hbons/SparkleShare#1581]
I can't give the entire reproduction, because I've done this a few times before I got this crash.

When adding a new hosted project to the client, I got the the following crash:

> An unhandled exception of type 'System.UnauthorizedAccessException' occurred in mscorlib.dll
> Additional information: Access to the path 'tmp_pack_KoU7Nb' is denied.

I'm on Windows 8.1 x64, the hosted project is on a personal server. When I tried to look for the file I couldn't find it. I tried running SparkleShare in administrator mode, but it didn't help.

**Comment by jehi** [comment]
Hi BarryThePenguin,
exactly the same happens to me while trying to add a new project to the sparkleshare client.
The same behaviour in normal or administrative user. 
What are you recommending to do to avoid this behaviour? What can I do to avoid the Exception?
Thanks!

**Comment by hbons** [comment]
@jehi can you delete `~/SparkleShare/.tmp/` and try again?
also, which version of SparkleShare are you using?

**Comment by jehi** [comment]
Dear Hylke,
Thanks for your fast reply.
Deleting the named folder does give me another attempt.
Means for one attempt the client is not crashing and I
can type in the sparkleshare host password.
But after typing in the password the button "Continue" stays gray and 
inactive.
If I am closing and reopening the sparkleshare client againg (without 
deleting the tmp-Folder)
the client crashes again before the password-step.
Do you have any other idea how to solve this?
Thanks, Jens


Am 14.01.2015 00:03, schrieb Hylke Bons:

**Comment by hbons** [comment]
@jehi this is another issue and is tracked here: #1416. it may already have been fixed in master.
