### ISSUE TITLE
Can not add a hosted project

### ISSUE THREAD

**Issue by srimurtisva** [hbons/SparkleShare#1597]
I press the button "Add hosted project". Then I go thru the wizard. I press "Finish". Files are downloaded. It does not work anymore with this project - no any commits are performed.

version 1.1

There is debug log next:
12:01:56 | Config | Wrote to '/home/moscowsaa/.config/sparkleshare/config.xml'
12:01:56 | Config | Updated option notifications:True
12:01:59 | Auth | Created keypair '/home/moscowsaa/.config/sparkleshare/2015-01-06_12h01.key'
12:01:59 | Auth | Imported key '/home/moscowsaa/.config/sparkleshare/2015-01-06_12h01.key'
12:02:33 | Config | Wrote to '/home/moscowsaa/.config/sparkleshare/config.xml'
12:02:42 | Controller | Added SparkleShare to login items
12:05:33 | Fetcher | /home/moscowsaa/SparkleShare/.tmp/sankirtana-asram-accounting.git | Fetching folder: ssh://git@gitlab.com/sms/sankirtana-asram-accounting.git
12:05:33 | Auth | Fetching host key for gitlab.com
12:05:33 | Cmd | ssh-keyscan -t rsa -p 22 gitlab.com
12:05:34 | Auth | Skipping fingerprint check
12:05:34 | Auth | Accepted host key for gitlab.com
12:05:34 | Cmd | .tmp | git clone --progress --no-checkout "ssh://git@gitlab.com/sms/sankirtana-asram-accounting.git" "/home/moscowsaa/SparkleShare/.tmp/sankirtana-asram-accounting.git"
12:05:34 | Fetcher | Cloning into '/home/moscowsaa/SparkleShare/.tmp/sankirtana-asram-accounting.git'...
12:05:35 | Fetcher | Warning: Permanently added the RSA host key for IP address '62.204.93.103' to the list of known hosts.
12:05:39 | Fetcher | remote: Counting objects: 1533, done.        
12:06:01 | Fetcher | remote: Total 1533 (delta 940), reused 128 (delta 26)        
12:06:04 | Fetcher | Checking connectivity... done.
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config core.quotepath false
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config core.ignorecase false
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config core.filemode false
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config core.autocrlf false
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config core.precomposeunicode true
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config core.safecrlf false
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config core.exludesfile ""
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config core.packedGitLimit 128m
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config core.packedGitWindowSize 128m
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config pack.deltaCacheSize 128m
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config pack.packSizeLimit 128m
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config pack.windowMemory 128m
12:06:04 | Cmd | sankirtana-asram-accounting.git | git config push.default matching
12:06:04 | Fetcher | Finished
12:06:04 | Cmd | sankirtana-asram-accounting.git | git rev-parse HEAD
12:06:04 | Cmd | sankirtana-asram-accounting.git | git rev-parse HEAD
12:06:04 | Cmd | sankirtana-asram-accounting.git | git checkout --quiet HEAD
12:06:05 | Config | Wrote to '/home/moscowsaa/.config/sparkleshare/config.xml'
12:06:05 | Controller | Added plugin for gitlab.com
12:06:05 | /home/moscowsaa/SparkleShare/sankirtana-asram-accounting | Initializing...
12:06:05 | Cmd | sankirtana-asram-accounting | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges
12:06:05 | Controller | Failed to load backend 'Git' for 'sankirtana-asram-accounting': : Exception has been thrown by the target of an invocation.   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type, System.Object[] args, System.Object[] activationAttributes) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type, System.Object[] args) [0x00000] in <filename unknown>:0 
  at SparkleShare.SparkleControllerBase.AddRepository (System.String folder_path) [0x00000] in <filename unknown>:0

**Comment by hbons** [comment]
version 1.1 is pretty old now, so this was likely fixed already. can you try the latest version?

**Comment by srimurtisva** [comment]
Thank you. I'll try.
06.01.2015 14:51, Hylke Bons пишет:
