### ISSUE TITLE
Secure Secure Shell

### ISSUE THREAD

**Issue by Nukama** [hbons/SparkleShare#1598]
Can you change the preferred order of mac, cipher and key exchange algorithms?

https://stribika.github.io/2015/01/04/secure-secure-shell.html
http://ed25519.cr.yp.to/
http://cr.yp.to/chacha.html
http://cr.yp.to/mac.html

**Comment by hbons** [comment]
SparkleShare now has an experimental CLI and support for ED25519 (the new default) keys: https://github.com/hbons/Twinkle.

If you like this work and want to support development, I’m looking for sponsors since I’m currently jobless: https://github.com/sponsors/hbons.
