### ISSUE TITLE
Files not decrypted when updated

### ISSUE THREAD

**Issue by laurentcharles** [hbons/SparkleShare#1599]
Hello,

We use Sparkleshare with some encrypted repositories xxx.crypto.

For an unknown reason there are 2 files which seems not to be decrypted when pulled/updated onto the clients. We use Sparkleshare 1.4.0 on Mac.

We noticed:
- All files are crypted in the repository
- Files are fine on the client. We can see and use them normally
- Only the 2 files are wrong. They are wrong on all the clients which access to the repository.
The files contents is plain text. It looks like 

> <<<<<<< HEAD
> U2FsdGVkX18UPdTN7Al5sNGLcsxx2mUT2Y6tgDH2mvPlX94O1cA42iqvY+3LUWV
> ...

Any mean to manually (command line) decrypt the file on the client? This would allow us to check that it is really a pb with decrypt,and will provide a quick fix.

Any way to retrieve an old version (expecting it will come decrypted)?

Has this issue been faced by anyone else already? Is there any fix or caution to prevent it will happen again?

Thank you for your help.
-- Laurent

**Comment by hbons** [comment]
it looks like something went wrong merging the encrypted file, because it shows the merge divider "<<< HEAD". not sure what yet though.

in the event log you can click the file's timestamp and it should give you a history with a link to restore to older versions.

**Comment by laurentcharles** [comment]
Great! I could retrieve the most recent valid file.
Thanks a lot.

NB: Just missing a feature to search within the event log window.

**Comment by hbons** [comment]
yes, there's an issue open for search. just nobody got around doing it yet.

**Comment by hbons** [comment]
Fixed in 1b4e2d7.
