### ISSUE TITLE
Long time to quit when fanout service unreachable

### ISSUE THREAD

**Issue by gerhard-tinned** [hbons/SparkleShare#1601]
I have found the situation that the fanout service (tcp://notifications.sparkleshare.org:443/) is not reachable. According to the logs, SparkeShare uses the fallback and pulls the changes. But it still tries to reconnect from time to time.

While the connection is tried to be established, the app does not terminate. It seems to hang in the reconnect state and does only terminate after the reconnect times out. 

I cannot be sure about this as there are no log lines on application termination. 

Found on MacOSX.

**Comment by hbons** [comment]
which version are you running? i've seen this before, but am not able to reproduce this consistently.
can you confirm this happens on git master?

**Comment by gerhard-tinned** [comment]
SparkleShare version: 1.4.0, Operating system: MacOSX (Unix 14.0.0.0)
