### ISSUE TITLE
when using a custom <path>, local activity goes undetected on Mac

### ISSUE THREAD

**Issue by michaelcinquin** [hbons/SparkleShare#1602]
I noticed that if I use a 'path' setting in config.xml for a synched folder, I lose the detection of local changes (a global setting of 'folders_path' is okay).

Looking at the source code, it looks like the detection of local changes routines are hardcoded on a mac to the global 'folders_path' setting. So if changes happen inside the custom 'path' of a synched folder, they will go unnoticed.

L60 of SparkleShare/SparkleShare/Mac/SparkleController.csu reads
<code>this.watcher = new SparkleMacWatcher (Program.Controller.FoldersPath);</code>

and L177 of SparkleShare/SparkleLib/SparkleRepoBase.cs reads
<code>if (!UseCustomWatcher)
this.watcher = new SparkleWatcher (LocalPath);</code>

When using SparkleSare with customs 'paths' and looking at the log, I can see that nothing is triggered when making local changes. The only way to commit local change is manually (via git or quitting / relaunching SparkleShare)… or to not use custom 'path'.

Solving this is beyond my skills, hope you can look into it !

**Comment by gerhard-tinned** [comment]
I noticed the same yesterday. 
When two shares / repos are configured in different directories (example ~/SparkleShare/share1 and ~/testing/share2) only the share which is in the global "folders_path" is watched. Changes there trigger checking of all shares/repositories but changes in the repository outside that path dont trigger any action.

**Comment by hbons** [comment]
this will need a change in how filesystem events are handled. right now we have a watcher for each repository. we need some kind of manager object which decides on how many watchers are needed and trigger the subscribed repositories.

**Comment by richardwonka** [comment]
when moving projects out of `folders_path`, as outlined in the wiki, the projects simply disappear from SparkleShare's scope (and from the config upon closing).

**Comment by hbons** [comment]
Now tracked in #1819.
