### ISSUE TITLE
Issues syncing between 2 Win7Pro machines

### ISSUE THREAD

**Issue by vatastala** [hbons/SparkleShare#1605]
Hi all, I have installed Sparkleshare as documented on main site page, executing all steps with "dazzle setup". After all, installing client side on 2 Win7Pro laptop, I encounter difficulties syncing files, as:

- When I create a new file in Laptop 1, Laptop 2 does not update. The only way to update is to create on Laptop 2 another file, so I can see the first
- After rebooting both machines I received a baloon tip saying that Laptop 2 created a new file. Try to edit It from Laptop 1 the other does not see any baloon tip or change on the file. After this, trying to edit the file, SparkleShare found a conflict copy.

This is the log from Laptop1:

14:22:59 | Controller | ssh-agent started, PID=6508
14:22:59 | Environment | SparkleShare version: 1.4.0, Operating system: Win32NT (Microsoft Windows NT 6.1.7601 Service Pack 1)
14:22:59 | Auth | Imported key 'C:\Users\yyyyyy\AppData\Roaming\sparkleshare\2015-01-16_11h42.key'
14:23:00 | Auth | The following keys may be used:
2048 f2:5b:77:6b:70:af:a9:8e:e6:2c:bf:2d:88:0b:0c:85 C:\Users\yyyyyy\AppData\Roaming\sparkleshare\2015-01-16_11h42.key (RSA)
14:23:00 | C:\Users\yyyyyy\SparkleShare\BSO | Initializing...
14:23:00 | Cmd | BSO | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color -m --first-parent
14:23:02 | Cmd | BSO | git config core.ignorecase false
14:23:02 | ListenerFactory | Issued new listener for tcp://notifications.sparkleshare.org:443/
14:23:02 | Listener | Subscribing to channel 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:23:02 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
14:23:02 | Cmd | BSO | git config --get filter.bin.clean
14:23:03 | Cmd | BSO | git config remote.origin.url "ssh://storage@192.168.79.40/home/storage/BSO"
14:23:03 | Git | BSO | Checking for remote changes...
14:23:03 | Cmd | BSO | git rev-parse HEAD
14:23:04 | Cmd | BSO | git config core.ignorecase true
14:23:04 | Cmd | BSO | git config core.ignorecase false
14:23:04 | Cmd | BSO | git rev-parse --abbrev-ref HEAD
14:23:05 | Cmd | BSO | git ls-remote --heads --exit-code "ssh://storage@192.168.79.40/home/storage/BSO" master
14:23:06 | Git | BSO | No remote changes, local+remote: 75fc6870301dffe47c143ebba0071a0d99ab7f41
14:23:06 | Cmd | BSO | git status --porcelain
14:23:19 | Avatars | Invalid certificate for https://www.gravatar.com/
14:23:19 | Avatars | Error fetching avatar for yyyyyy@yyyyy.yy: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at SparkleShare.SparkleAvatars.GetAvatar(String email, Int32 size, String target_path)
14:28:02 | ListenerTcp | Pinging tcp://notifications.sparkleshare.org:443/
14:28:02 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: Ping timeout: An existing connection was forcibly closed by the remote host
14:28:02 | BSO | Falling back to regular polling
14:28:06 | Git | BSO | Checking for remote changes...
14:28:06 | Cmd | BSO | git rev-parse HEAD
14:28:06 | Cmd | BSO | git ls-remote --heads --exit-code "ssh://storage@192.168.79.40/home/storage/BSO" master
14:28:07 | Cmd | BSO | git merge-base d50c03896923fd399fd69ab1b8695198acd09bd8 master
14:28:07 | Git | BSO | Remote changes found, local: 75fc6870301dffe47c143ebba0071a0d99ab7f41, remote: d50c03896923fd399fd69ab1b8695198acd09bd8
14:28:07 | SyncDown | BSO | Initiated
14:28:07 | Cmd | BSO | git rev-parse HEAD
14:28:07 | Cmd | BSO | git fetch --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:28:07 | Git | BSO | remote: Counting objects: 6, done.[K
14:28:07 | Git | BSO | remote: Total 5 (delta 1), reused 0 (delta 0)[K
14:28:07 | Git | BSO | From ssh://192.168.79.40/home/storage/BSO
14:28:07 | Git | BSO |  * branch            master     -> FETCH_HEAD
14:28:07 | Cmd | BSO | git status --porcelain
14:28:07 | Cmd | BSO | git config core.ignorecase true
14:28:07 | Cmd | BSO | git merge FETCH_HEAD
14:28:07 | Cmd | BSO | git config core.ignorecase false
14:28:07 | Cmd | BSO | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color -m --first-parent
14:28:07 | Cmd | BSO | git rev-parse HEAD
14:28:08 | Avatars | Invalid certificate for https://www.gravatar.com/
14:28:08 | Avatars | Error fetching avatar for xxxxxxxxxx@xxxxxx.xx: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at SparkleShare.SparkleAvatars.GetAvatar(String email, Int32 size, String target_path)
14:28:08 | SyncDown | BSO | Done
14:28:36 | Cmd | BSO | git status --porcelain
14:28:36 | Local | BSO | Activity detected, waiting for it to settle...
14:28:38 | Local | BSO | Activity has settled
14:28:38 | Cmd | BSO | git status --porcelain
14:28:38 | SyncUp | BSO | Initiated
14:28:38 | Cmd | BSO | git add --all
14:28:38 | Cmd | BSO | git status --porcelain
14:28:38 | Cmd | BSO | git config user.name "yyyyyy"
14:28:38 | Cmd | BSO | git config user.email "yyyyyy@yyyyy.yy"
14:28:38 | Cmd | BSO | git commit --all --message="/ ‘nmb.txt’
" --author="yyyyyy <yyyyyy@yyyyy.yy>"
14:28:38 | Cmd | BSO | git push --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:28:38 | Git | BSO | Counting objects: 5, done.
14:28:38 | Git | BSO | Delta compression using up to 4 threads.
14:28:38 | Git | BSO | Total 3 (delta 1), reused 0 (delta 0)
14:28:38 | Git | BSO | To ssh://storage@192.168.79.40/home/storage/BSO
14:28:38 | Git | BSO |    4bbb722..293f293  master -> master
14:28:38 | SyncUp | BSO | Done
14:28:38 | Cmd | BSO | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color -m --first-parent
14:28:38 | Cmd | BSO | git rev-parse HEAD
14:28:38 | Listener | Can't send message to tcp://notifications.sparkleshare.org:443/. Queuing message
14:28:39 | Cmd | BSO | git status --porcelain
14:29:02 | Listener | Trying to reconnect to tcp://notifications.sparkleshare.org:443/
14:29:02 | Listener | Subscribing to channel 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:29:02 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
14:29:02 | Listener | Delivering 1 queued messages...
14:29:02 | Listener | Announcing message 293f2930e9e503fa2b7b5079ed4a2182a14f45f1 to 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:32:00 | Cmd | BSO | git status --porcelain
14:32:00 | Local | BSO | Activity detected, waiting for it to settle...
14:32:01 | Local | BSO | Activity has settled
14:32:01 | Cmd | BSO | git status --porcelain
14:32:01 | SyncUp | BSO | Initiated
14:32:01 | Cmd | BSO | git add --all
14:32:01 | Cmd | BSO | git status --porcelain
14:32:01 | Cmd | BSO | git commit --all --message="/ ‘nmb.txt’
" --author="yyyyyy <yyyyyy@yyyyy.yy>"
14:32:01 | Cmd | BSO | git push --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:32:02 | Git | BSO | To ssh://storage@192.168.79.40/home/storage/BSO
14:32:02 | Git | BSO |  ! [rejected]        master -> master (non-fast-forward)
14:32:02 | Git | BSO | error: failed to push some refs to 'ssh://storage@192.168.79.40/home/storage/BSO'
14:32:02 | Git | BSO | hint: Updates were rejected because the tip of your current branch is behind
14:32:02 | Git | BSO | hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
14:32:02 | Git | BSO | hint: before pushing again.
14:32:02 | Git | BSO | hint: See the 'Note about fast-forwards' in 'git push --help' for details.
14:32:02 | SyncUp | BSO | Error
14:32:02 | SyncDown | BSO | Initiated
14:32:02 | Cmd | BSO | git rev-parse HEAD
14:32:02 | Cmd | BSO | git fetch --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:32:02 | Git | BSO | remote: Counting objects: 7, done.[K
14:32:02 | Git | BSO | remote: Total 5 (delta 1), reused 0 (delta 0)[K
14:32:02 | Git | BSO | From ssh://192.168.79.40/home/storage/BSO
14:32:02 | Git | BSO |  * branch            master     -> FETCH_HEAD
14:32:02 | Cmd | BSO | git status --porcelain
14:32:02 | Cmd | BSO | git config core.ignorecase true
14:32:02 | Cmd | BSO | git merge FETCH_HEAD
14:32:03 | Cmd | BSO | git config core.ignorecase false
14:32:03 | Cmd | BSO | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color -m --first-parent
14:32:03 | Cmd | BSO | git rev-parse HEAD
14:32:03 | SyncDown | BSO | Done
14:32:03 | Cmd | BSO | git add --all
14:32:03 | Cmd | BSO | git status --porcelain
14:32:03 | Cmd | BSO | git push --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:32:03 | Git | BSO | Counting objects: 8, done.
14:32:03 | Git | BSO | Delta compression using up to 4 threads.
14:32:03 | Git | BSO | Total 5 (delta 2), reused 0 (delta 0)
14:32:03 | Git | BSO | To ssh://storage@192.168.79.40/home/storage/BSO
14:32:03 | Git | BSO |    1e60712..2d2b08c  master -> master
14:32:04 | Cmd | BSO | git add --all
14:32:04 | Cmd | BSO | git status --porcelain
14:32:04 | Cmd | BSO | git push --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:32:04 | Git | BSO | Everything up-to-date
14:32:04 | Cmd | BSO | git rev-parse HEAD
14:32:04 | Listener | Announcing message 2d2b08c1b5533fff83a9a8f77c4596582fe70a07 to 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:32:04 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: An existing connection was forcibly closed by the remote host
14:32:04 | BSO | Falling back to regular polling
14:32:05 | Cmd | BSO | git status --porcelain
14:33:02 | Listener | Trying to reconnect to tcp://notifications.sparkleshare.org:443/
14:33:02 | Listener | Subscribing to channel 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:33:02 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
14:33:02 | Listener | Delivering 1 queued messages...
14:33:02 | Listener | Already processed message 293f2930e9e503fa2b7b5079ed4a2182a14f45f1 to 26713dac6b6f454149dc19b6f13b777b73e68aad from tcp://notifications.sparkleshare.org:443/
14:34:02 | ListenerTcp | Pinging tcp://notifications.sparkleshare.org:443/
14:34:02 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: Ping timeout: An existing connection was forcibly closed by the remote host
14:34:02 | BSO | Falling back to regular polling
14:34:07 | Git | BSO | Checking for remote changes...
14:34:07 | Cmd | BSO | git rev-parse HEAD
14:34:07 | Cmd | BSO | git ls-remote --heads --exit-code "ssh://storage@192.168.79.40/home/storage/BSO" master
14:34:07 | Git | BSO | No remote changes, local+remote: 2d2b08c1b5533fff83a9a8f77c4596582fe70a07
14:35:02 | Listener | Trying to reconnect to tcp://notifications.sparkleshare.org:443/
14:35:02 | Listener | Subscribing to channel 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:35:02 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
14:35:02 | Listener | Delivering 1 queued messages...
14:35:02 | Listener | Already processed message 293f2930e9e503fa2b7b5079ed4a2182a14f45f1 to 26713dac6b6f454149dc19b6f13b777b73e68aad from tcp://notifications.sparkleshare.org:443/
14:40:02 | ListenerTcp | Pinging tcp://notifications.sparkleshare.org:443/
14:40:02 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: Ping timeout: An existing connection was forcibly closed by the remote host
14:40:02 | BSO | Falling back to regular polling
14:40:02 | Git | BSO | Checking for remote changes...
14:40:02 | Cmd | BSO | git rev-parse HEAD
14:40:02 | Cmd | BSO | git ls-remote --heads --exit-code "ssh://storage@192.168.79.40/home/storage/BSO" master
14:40:02 | Git | BSO | No remote changes, local+remote: 2d2b08c1b5533fff83a9a8f77c4596582fe70a07
14:41:02 | Listener | Trying to reconnect to tcp://notifications.sparkleshare.org:443/
14:41:02 | Listener | Subscribing to channel 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:41:02 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
14:41:02 | Listener | Delivering 1 queued messages...
14:41:02 | Listener | Already processed message 293f2930e9e503fa2b7b5079ed4a2182a14f45f1 to 26713dac6b6f454149dc19b6f13b777b73e68aad from tcp://notifications.sparkleshare.org:443/
14:41:45 | Cmd | BSO | git status --porcelain
14:41:45 | Local | BSO | Activity detected, waiting for it to settle...
14:41:47 | Local | BSO | Activity has settled
14:41:47 | Cmd | BSO | git status --porcelain
14:41:47 | SyncUp | BSO | Initiated
14:41:47 | Cmd | BSO | git add --all
14:41:47 | Cmd | BSO | git status --porcelain
14:41:47 | Cmd | BSO | git commit --all --message="- ‘nmb (antonello.bisciglia, gen 16 14h29).txt’
- ‘nmb.txt’
" --author="yyyyyy <yyyyyy@yyyyy.yy>"
14:41:47 | Cmd | BSO | git push --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:41:47 | Git | BSO | Counting objects: 3, done.
14:41:47 | Git | BSO | Delta compression using up to 4 threads.
14:41:47 | Git | BSO | Total 2 (delta 1), reused 0 (delta 0)
14:41:47 | Git | BSO | To ssh://storage@192.168.79.40/home/storage/BSO
14:41:47 | Git | BSO |    2d2b08c..2587c70  master -> master
14:41:47 | SyncUp | BSO | Done
14:41:47 | Cmd | BSO | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color -m --first-parent
14:41:47 | Cmd | BSO | git rev-parse HEAD
14:41:47 | Listener | Announcing message 2587c70f28202e8894a8f2149543fc493962bcb0 to 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:41:48 | Cmd | BSO | git status --porcelain
14:46:02 | ListenerTcp | Pinging tcp://notifications.sparkleshare.org:443/
14:46:02 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: Ping timeout: An existing connection was forcibly closed by the remote host
14:46:02 | BSO | Falling back to regular polling
14:46:03 | Git | BSO | Checking for remote changes...
14:46:03 | Cmd | BSO | git rev-parse HEAD
14:46:03 | Cmd | BSO | git ls-remote --heads --exit-code "ssh://storage@192.168.79.40/home/storage/BSO" master
14:46:03 | Git | BSO | No remote changes, local+remote: 2587c70f28202e8894a8f2149543fc493962bcb0

And this is the Log from Laptop 2:

14:26:42 | Controller | ssh-agent started, PID=5292
14:26:42 | Environment | SparkleShare version: 1.4.0, Operating system: Win32NT (Microsoft Windows NT 6.1.7601 Service Pack 1)
14:26:46 | Auth | Imported key 'C:\Users\xxxxxx\AppData\Roaming\sparkleshare\2015-01-16_12h47.key'
14:26:46 | Auth | The following keys may be used:
2048 98:61:8b:23:a4:79:ff:2c:77:d3:0b:ab:99:40:25:1b C:\Users\xxxxxx\AppData\Roaming\sparkleshare\2015-01-16_12h47.key (RSA)
14:26:49 | C:\Users\xxxxxx\SparkleShare\BSO | Initializing...
14:26:49 | Cmd | BSO | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color -m --first-parent
14:26:52 | Cmd | BSO | git config core.ignorecase false
14:26:52 | ListenerFactory | Issued new listener for tcp://notifications.sparkleshare.org:443/
14:26:52 | Cmd | BSO | git config --get filter.bin.clean
14:26:52 | Listener | Subscribing to channel 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:26:52 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
14:26:52 | Cmd | BSO | git config remote.origin.url "ssh://storage@192.168.79.40/home/storage/BSO"
14:26:53 | Git | BSO | Checking for remote changes...
14:26:53 | Cmd | BSO | git rev-parse HEAD
14:26:53 | Cmd | BSO | git config core.ignorecase true
14:26:53 | Cmd | BSO | git config core.ignorecase false
14:26:53 | Cmd | BSO | git rev-parse --abbrev-ref HEAD
14:26:53 | Cmd | BSO | git ls-remote --heads --exit-code "ssh://storage@192.168.79.40/home/storage/BSO" master
14:26:54 | Avatars | Invalid certificate for https://www.gravatar.com/
14:26:54 | Avatars | Error fetching avatar for yyyyyyyy@yyyyyy.yy: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at SparkleShare.SparkleAvatars.GetAvatar(String email, Int32 size, String target_path)
14:26:55 | Git | BSO | No remote changes, local+remote: 75fc6870301dffe47c143ebba0071a0d99ab7f41
14:26:55 | Cmd | BSO | git status --porcelain
14:28:02 | Cmd | BSO | git status --porcelain
14:28:02 | Local | BSO | Activity detected, waiting for it to settle...
14:28:04 | Local | BSO | Activity has settled
14:28:04 | Cmd | BSO | git status --porcelain
14:28:04 | SyncUp | BSO | Initiated
14:28:04 | Cmd | BSO | git add --all
14:28:04 | Cmd | BSO | git status --porcelain
14:28:04 | Cmd | BSO | git config user.name "xxxxxx"
14:28:04 | Cmd | BSO | git config user.email "xxxxxx@xxxx.mn"
14:28:04 | Cmd | BSO | git commit --all --message="+ ‘New Text Document.txt’
" --author="xxxxxx <xxxxxx@xxxx.mn>"
14:28:04 | Cmd | BSO | git push --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:28:05 | Git | BSO | Counting objects: 4, done.
14:28:05 | Git | BSO | Delta compression using up to 4 threads.
14:28:05 | Git | BSO | Total 3 (delta 0), reused 0 (delta 0)
14:28:05 | Git | BSO | To ssh://storage@192.168.79.40/home/storage/BSO
14:28:05 | Git | BSO |    75fc687..d50c038  master -> master
14:28:05 | SyncUp | BSO | Done
14:28:05 | Cmd | BSO | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color -m --first-parent
14:28:05 | Cmd | BSO | git rev-parse HEAD
14:28:05 | Listener | Announcing message d50c03896923fd399fd69ab1b8695198acd09bd8 to 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:28:05 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: An existing connection was forcibly closed by the remote host
14:28:05 | BSO | Falling back to regular polling
14:28:07 | Avatars | Invalid certificate for https://www.gravatar.com/
14:28:07 | Avatars | Error fetching avatar for xxxxxx@xxxx.mn: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at SparkleShare.SparkleAvatars.GetAvatar(String email, Int32 size, String target_path)
14:28:07 | Cmd | BSO | git status --porcelain
14:28:07 | Local | BSO | More changes found
14:28:07 | SyncUp | BSO | Initiated
14:28:07 | Cmd | BSO | git add --all
14:28:07 | Cmd | BSO | git status --porcelain
14:28:07 | Cmd | BSO | git commit --all --message="< ‘New Text Document.txt’
> ‘nmb.txt’
" --author="xxxxxx <xxxxxx@xxxx.mn>"
14:28:07 | Cmd | BSO | git push --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:28:07 | Git | BSO | Counting objects: 3, done.
14:28:07 | Git | BSO | Delta compression using up to 4 threads.
14:28:07 | Git | BSO | Total 2 (delta 1), reused 0 (delta 0)
14:28:07 | Git | BSO | To ssh://storage@192.168.79.40/home/storage/BSO
14:28:07 | Git | BSO |    d50c038..4bbb722  master -> master
14:28:07 | SyncUp | BSO | Done
14:28:07 | Cmd | BSO | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color -m --first-parent
14:28:07 | Cmd | BSO | git rev-parse HEAD
14:28:07 | Listener | Can't send message to tcp://notifications.sparkleshare.org:443/. Queuing message
14:28:08 | Cmd | BSO | git status --porcelain
14:28:52 | Listener | Trying to reconnect to tcp://notifications.sparkleshare.org:443/
14:28:52 | Listener | Subscribing to channel 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:28:52 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
14:28:52 | Listener | Delivering 1 queued messages...
14:28:52 | Listener | Announcing message 4bbb722d7ef3da04e9e8faf74a15e1696e50c7b1 to 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:29:43 | Cmd | BSO | git status --porcelain
14:29:43 | Local | BSO | Activity detected, waiting for it to settle...
14:29:44 | Local | BSO | Activity has settled
14:29:44 | Cmd | BSO | git status --porcelain
14:29:44 | SyncUp | BSO | Initiated
14:29:44 | Cmd | BSO | git add --all
14:29:44 | Cmd | BSO | git status --porcelain
14:29:44 | Cmd | BSO | git commit --all --message="/ ‘nmb.txt’
" --author="xxxxxx <xxxxxx@xxxx.mn>"
14:29:44 | Cmd | BSO | git push --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:29:45 | Git | BSO | To ssh://storage@192.168.79.40/home/storage/BSO
14:29:45 | Git | BSO |  ! [rejected]        master -> master (non-fast-forward)
14:29:45 | Git | BSO | error: failed to push some refs to 'ssh://storage@192.168.79.40/home/storage/BSO'
14:29:45 | Git | BSO | hint: Updates were rejected because the tip of your current branch is behind
14:29:45 | Git | BSO | hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
14:29:45 | Git | BSO | hint: before pushing again.
14:29:45 | Git | BSO | hint: See the 'Note about fast-forwards' in 'git push --help' for details.
14:29:45 | SyncUp | BSO | Error
14:29:45 | SyncDown | BSO | Initiated
14:29:45 | Cmd | BSO | git rev-parse HEAD
14:29:45 | Cmd | BSO | git fetch --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:29:45 | Git | BSO | remote: Counting objects: 5, done.[K
14:29:46 | Git | BSO | remote: Total 3 (delta 1), reused 0 (delta 0)[K
14:29:46 | Git | BSO | From ssh://192.168.79.40/home/storage/BSO
14:29:46 | Git | BSO |  * branch            master     -> FETCH_HEAD
14:29:46 | Cmd | BSO | git status --porcelain
14:29:46 | Cmd | BSO | git config core.ignorecase true
14:29:46 | Cmd | BSO | git merge FETCH_HEAD
14:29:46 | Git | 
14:29:46 | Git | BSO | Conflict detected, trying to get out...
14:29:46 | Cmd | BSO | git status --porcelain
14:29:46 | Cmd | BSO | git status --porcelain
14:29:46 | Git | BSO | Conflict type: UU nmb.txt
14:29:46 | Git | BSO | Resolving: nmb.txt
14:29:46 | Cmd | BSO | git checkout --ours "nmb.txt"
14:29:46 | Cmd | BSO | git checkout --theirs "nmb.txt"
14:29:46 | Cmd | BSO | git add --all
14:29:46 | Cmd | BSO | git commit --message "Conflict resolution by SparkleShare"
14:29:46 | Git | BSO | Conflict resolved
14:29:46 | Cmd | BSO | git config core.ignorecase false
14:29:46 | Cmd | BSO | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color -m --first-parent
14:29:46 | Cmd | BSO | git rev-parse HEAD
14:29:46 | SyncDown | BSO | Done
14:29:46 | Cmd | BSO | git add --all
14:29:46 | Cmd | BSO | git status --porcelain
14:29:46 | Cmd | BSO | git push --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:29:46 | Git | BSO | Counting objects: 7, done.
14:29:46 | Git | BSO | Delta compression using up to 4 threads.
14:29:46 | Git | BSO | Total 5 (delta 1), reused 0 (delta 0)
14:29:46 | Git | BSO | To ssh://storage@192.168.79.40/home/storage/BSO
14:29:46 | Git | BSO |    293f293..1e60712  master -> master
14:29:48 | Cmd | BSO | git add --all
14:29:48 | Cmd | BSO | git status --porcelain
14:29:48 | Cmd | BSO | git push --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:29:48 | Git | BSO | Everything up-to-date
14:29:48 | Cmd | BSO | git rev-parse HEAD
14:29:48 | Listener | Announcing message 1e607123960724892cb430efc801017a1c0ef0b3 to 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:29:48 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: An existing connection was forcibly closed by the remote host
14:29:48 | BSO | Falling back to regular polling
14:29:49 | Cmd | BSO | git status --porcelain
14:29:52 | Listener | Trying to reconnect to tcp://notifications.sparkleshare.org:443/
14:29:52 | Listener | Subscribing to channel 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:29:52 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
14:29:52 | Listener | Delivering 1 queued messages...
14:29:52 | Listener | Already processed message 4bbb722d7ef3da04e9e8faf74a15e1696e50c7b1 to 26713dac6b6f454149dc19b6f13b777b73e68aad from tcp://notifications.sparkleshare.org:443/
14:31:52 | ListenerTcp | Pinging tcp://notifications.sparkleshare.org:443/
14:31:52 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: Ping timeout: An existing connection was forcibly closed by the remote host
14:31:52 | BSO | Falling back to regular polling
14:31:55 | Git | BSO | Checking for remote changes...
14:31:55 | Cmd | BSO | git rev-parse HEAD
14:31:56 | Cmd | BSO | git ls-remote --heads --exit-code "ssh://storage@192.168.79.40/home/storage/BSO" master
14:31:56 | Git | BSO | No remote changes, local+remote: 1e607123960724892cb430efc801017a1c0ef0b3
14:32:52 | Listener | Trying to reconnect to tcp://notifications.sparkleshare.org:443/
14:32:52 | Listener | Subscribing to channel 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:32:52 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
14:32:52 | Listener | Delivering 1 queued messages...
14:32:52 | Listener | Already processed message 4bbb722d7ef3da04e9e8faf74a15e1696e50c7b1 to 26713dac6b6f454149dc19b6f13b777b73e68aad from tcp://notifications.sparkleshare.org:443/
14:37:52 | ListenerTcp | Pinging tcp://notifications.sparkleshare.org:443/
14:37:52 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: Ping timeout: An existing connection was forcibly closed by the remote host
14:37:52 | BSO | Falling back to regular polling
14:37:52 | Listener | Trying to reconnect to tcp://notifications.sparkleshare.org:443/
14:37:52 | Listener | Subscribing to channel 26713dac6b6f454149dc19b6f13b777b73e68aad on tcp://notifications.sparkleshare.org:443/
14:37:52 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
14:37:52 | Listener | Delivering 1 queued messages...
14:37:52 | Listener | Already processed message 4bbb722d7ef3da04e9e8faf74a15e1696e50c7b1 to 26713dac6b6f454149dc19b6f13b777b73e68aad from tcp://notifications.sparkleshare.org:443/
14:42:52 | ListenerTcp | Pinging tcp://notifications.sparkleshare.org:443/
14:42:52 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: Ping timeout: An existing connection was forcibly closed by the remote host
14:42:52 | BSO | Falling back to regular polling
14:42:56 | Git | BSO | Checking for remote changes...
14:42:56 | Cmd | BSO | git rev-parse HEAD
14:42:56 | Cmd | BSO | git ls-remote --heads --exit-code "ssh://storage@192.168.79.40/home/storage/BSO" master
14:42:57 | Cmd | BSO | git merge-base 2587c70f28202e8894a8f2149543fc493962bcb0 master
14:42:57 | Git | BSO | Remote changes found, local: 1e607123960724892cb430efc801017a1c0ef0b3, remote: 2587c70f28202e8894a8f2149543fc493962bcb0
14:42:57 | SyncDown | BSO | Initiated
14:42:57 | Cmd | BSO | git rev-parse HEAD
14:42:57 | Cmd | BSO | git fetch --progress "ssh://storage@192.168.79.40/home/storage/BSO" master
14:42:58 | Git | BSO | remote: Counting objects: 10, done.[K
14:42:58 | Git | BSO | remote: Total 7 (delta 3), reused 0 (delta 0)[K
14:42:58 | Git | BSO | From ssh://192.168.79.40/home/storage/BSO
14:42:58 | Git | BSO |  * branch            master     -> FETCH_HEAD
14:42:58 | Cmd | BSO | git status --porcelain
14:42:58 | Cmd | BSO | git config core.ignorecase true
14:42:58 | Cmd | BSO | git merge FETCH_HEAD
14:42:58 | Cmd | BSO | git config core.ignorecase false

BR

UPDATE: I found that HTTPS is used by Spacewalk Server, so there's the possibility to change SparkleShare 443 port to another?

UPDATE2: After stopping SpaceWalk, so releasing 443 port, the issue persists

UPDATE3: Ok, I found that SparkleShare works correctly, the only thing I tought is an immediate update on clients side, but saving a new file on Laptop1 the immediate update regards only the Server side, because looking at other Logs I see that Laptop2 queries the Server every 6 minutes to find some change. So, Is It possible to change this time? I would like for example 30 seconds for server polling by the clients. Thank you

UPDATE4: Ok I found in https://github.com/hbons/SparkleShare/wiki/Notification-service that I have to install on my server side "fanout", I did It but I'm not able to find ~/.config/sparkleshare/config.xml file after installing sparkleshare using the guide on the main page, so using dazzle. Now I can I use fanout working??? Thank you again

**Comment by hbons** [comment]
we're having some issues with the notification service right now it seems...hence the delayed syncs. @travisghansen any idea why it's down again?

the config.xml file on Windows can be found in ~/AppData/.

**Comment by travisghansen** [comment]
@hbons I was never able to ssh into the server.  To my knowledge it never got started again..
