### ISSUE TITLE
2 Problems Using SparkleShare with Github

### ISSUE THREAD

**Issue by davelab6** [hbons/SparkleShare#1614]
I installed SS on Mac OS X today to sync a Github repo, and I found that 
- [ ] first, my repo wouldn't clone; the progress bar's active portion went to the right most end of the bar signalling it was 100% complete, but it just hung there. Since I know a bit about ssh and github, I realised I should go quit the adding process, go to https://github.com/settings/ssh and add the 'client id' that is helpfully easy to copy to clipboard from the menubar status icon menu. I updated the wiki about this - https://github.com/hbons/SparkleShare/wiki/_history - and later I could not see in the log anything about this. I suggest changing the clone logic to add a timeout, and before or on the screen where you select github and type your repo path, reminding the user to add their key
- [ ] After adding the ssh key, I cloned down the repo without problem, but when I made changes I couldn't upload anything and the UI just said 'upload failed' or something like that. Reading the wiki I saw that `~/.config/sparkleshare/logs/` exists, and looking in the log, I saw something like:

```
17:58:48 | Cmd | website.com | git --exec-path="/Users/user/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" push --progress "ssh://git@github.com/user/website.com" gh-pages
17:58:48 | Git | website.com | ERROR: Sorry, but @craftingtype has blocked access to SSH keys created by some third-party applications. Your key was created before GitHub tracked keys created by applications, so we need your help.
17:58:48 | Git | website.com | 
17:58:48 | Git | website.com | If you personally created this key, you can approve it at:
17:58:48 | Git | website.com | 
17:58:48 | Git | website.com |   https://github.com/settings/ssh/audit/123456789/policy
17:58:48 | Git | website.com | 
17:58:48 | Git | website.com | Otherwise, please upload a new key:
17:58:48 | Git | website.com | 
17:58:48 | Git | website.com |   https://github.com/settings/ssh
17:58:48 | Git | website.com | 
17:58:48 | Git | website.com | Fingerprint: AB:CD:12:34;56:78:90
17:58:48 | Git | website.com | 
17:58:48 | Git | website.com | [EPOLICYKEYAGE]
17:58:48 | Git | website.com | 
17:58:48 | Git | website.com | fatal: Could not read from remote repository.
17:58:48 | Git | website.com | 
17:58:48 | Git | website.com | Please make sure you have the correct access rights
17:58:48 | Git | website.com | and the repository exists.
```

So I went to https://github.com/settings/ssh/audit/123456789/policy and then it just started working. So I suggest catching this git error and having the UI present this message to the user, ideally with a clickable link to the https://github.com/settings/ssh/audit/$id/policy url, and a try again button :)

**Comment by hbons** [comment]
that's odd. i don't know why the progress bar would hang at the end. it should give you a an error page with possible solutions why it didn't work (including a suggestion to add the Client ID)

for the second issue, any idea how to reproduce that behaviour? i don't see a setting to disable "third party" SSH keys.

**Comment by davelab6** [comment]
I'll try to get hold of a blank mac and retry

**Comment by hwine** [comment]
@davelab6 you might want to read [this article](http://www.networkworld.com/article/2931133/users-with-weak-ssh-keys-had-access-to-github-repositories-for-popular-projects.html) about why your key was rejected. Several actions you may want to take depending on your situation.

**Comment by hbons** [comment]
Tracking better error messages in #1603. I have a design for a better flow for the SSH key reminder for 3.0 in the works.
