### ISSUE TITLE
SparkleConfig confusion

### ISSUE THREAD

**Issue by BarryThePenguin** [hbons/SparkleShare#1616]
Is there any reason for the SparkleConfig to be passed around so much?

It's build in the SparkleController constructor and assigned to SparkleConfig.DefaultConfig, but is also kept in the SparkleController as a reference. Then other controllers access it through Program.Controller.Config or SparkleConfig.DefaultConfig, but I'm not able to tell the difference.

Is there something that I'm missing? Wouldn't it be simpler to have a static reference built on startup that is the source of all configuration?

**Comment by hbons** [comment]
just bad design really. :) could use a rethink.

**Comment by BarryThePenguin** [comment]
Look into locking? https://msdn.microsoft.com/en-us/library/system.threading.readerwriterlockslim.aspx
