### ISSUE TITLE
Accessing Existing GIT on Plan.io causes crash

### ISSUE THREAD

**Issue by marrngtn** [hbons/SparkleShare#1619]
Problem signature:
  Problem Event Name:                        CLR20r3
  Problem Signature 01:                       sparkleshare.exe
  Problem Signature 02:                       0.0.0.0
  Problem Signature 03:                       5353e1ae
  Problem Signature 04:                       mscorlib
  Problem Signature 05:                       4.0.30319.17929
  Problem Signature 06:                       4ffa561c
  Problem Signature 07:                       43c4
  Problem Signature 08:                       13c
  Problem Signature 09:                       System.UnauthorizedAccess
  OS Version:                                          6.1.7601.2.1.0.256.4
  Locale ID:                                             1033
  Additional Information 1:                  0a9e
  Additional Information 2:                  0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:                  0a9e
  Additional Information 4:                  0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by BarryThePenguin** [comment]
Try checking ~/Sparkleshare/.tmp as there may be a previous checkout of the project that Sparkleshare cannot delete for what ever reason. Removing that should fix the crash
