### ISSUE TITLE
Does this need translation contribution?

### ISSUE THREAD

**Issue by lua86** [hbons/SparkleShare#1621]
So, essentially, I can translate to/from Spanish, Catalan, and English.
So I am offering myself for translation to Spanish and Catalan if needed. Are they needed?
I don't know a thing about your translation system, a basic explanation on the wiki would be a good thing.

**Comment by hbons** [comment]
Translations and other localisations will be added in v3. Subscribe to #775 for progress updates and when you'll be able to help out.
