### ISSUE TITLE
"announce" commit

### ISSUE THREAD

**Issue by killes** [hbons/SparkleShare#1622]
I question the usefulness of the "greetings" commit that happens when you add a project that you have write access to.

I added a public repo that I had forgotten I had write access to and this looked rather silly.

**Comment by hbons** [comment]
i agree this isn't always needed. it's a nice introduction, but we should probably only add it on empty projects.

**Comment by killes** [comment]
I'd just remove it as it is unexpected.

**Comment by hbons** [comment]
fixed by bbf653426628eea2047134984b7da254b28eaf5b.

**Comment by wimleers** [comment]
Wow, very fast turn-around time :)

**Comment by hbons** [comment]
oneliner. :)
