### ISSUE TITLE
Files containing '/' are ignored silently on OSX

### ISSUE THREAD

**Issue by mokaspar** [hbons/SparkleShare#1624]
On OSX '/' is a legal character of a filename, which is internally represented as ':' (this can be verfied using Terminal). Unfortunately, ':' is an illegal character on Windows and any files containing ':' are ignored: See `SparekleFetcherBase.cs:104` https://github.com/hbons/SparkleShare/blob/master/SparkleLib/SparkleFetcherBase.cs

**Comment by hbons** [comment]
we can't know what OS people will be using to connect to a repository, that's why SparkleShare ignores all characters that cause problems on any of the platforms, not just the platform specific ones.
