### ISSUE TITLE
race condition generating SSH key pair

### ISSUE THREAD

**Issue by xkpd3** [hbons/SparkleShare#1626]
Hello,
When setting up SparkleShare on Windows the following happens:

1. SparkleShare asks for Username and E-Mail Address
2. click next
3. SparkleShare shows the tutorial
4. click next/next/next or skip
5. SparkleShare shows the public key and allows to copy it to the clipboard.

The issue I found is, that the key generation is started asynchronously at step 2.
It takes a few seconds. If you reach step 5 before the key generation process is finished, the public key text-box is empty and clicking on "copy" leads to a crash.

Best Regards,
Stefan

**Comment by hbons** [comment]
This has been fixed in for the next version.
