### ISSUE TITLE
notifications.sparkleshare.org

### ISSUE THREAD

**Issue by markusstoll** [hbons/SparkleShare#1628]
Hi,

notifications.sparkleshare.org is quite often down - for me the whole thing gets quite unusable without a reliable notification service (the fallback to polling is not good enough, with that I have huge update delays). I would not mind setting up my own notification server, but as I see it, I would have to configure each client manually, which I consider even more problematic, as if it is no esured that all clients use the same notification server, some clients might wait endlessly for updates.
So could we find a way to distribute the notification server config over the git repo to ensure a consistent setting?

Markus

**Comment by hbons** [comment]
i'm currently working on an alternative using ZeroMQ to replace the current
service. not sure when that will be up though. I'm also open to other
ideas. if we can utilise the existing git repository or ssh connection
somehow that would be much easier, but I don't know if that's possible.

**Comment by markusstoll** [comment]
am I the only one getting constantly

09:20:12 | Listener | Disconnected from tcp://notifications.sparkleshare.org:443/: Connection timed out


?

**Comment by hbons** [comment]
Service is still down whilst I'm working on the replacement. Help appreciated on testing the NetMQ branch. I've made a testing server here: https://github.com/hbons/SparkleShare.Fanout

**Comment by winged** [comment]
I work for Adfinis SyGroup in Switzerland - if you're interested, we could help out by hosting a backup notification service for free. I didn't look at the (serverside) code yet, so not sure how easy it would be. Or maybe the notification server isn't even the problem at all, I don't know yet. But as I said, if you're interested, please let me know!

**Comment by hbons** [comment]
@winged That's great. I will be in touch over email. :)

**Comment by wbrigg** [comment]
@hbons Please could you provide a little bit more information on how to use your fanout service? The readme is quite sparse...

(alternatively, do you have an update on when this might be resolved?)

**Comment by dhufish** [comment]
We setup my own fanout notification server and it works great after editing the config.xml on the clients.  However we have a larger roll out and decided to change the default notification server address in the 1.4 source and built a new Win installer.  
Everything installs fine, however, there is an issue with SSH when adding a project and it never makes a successful SSH connection (I suspect the key location).  We built Sparkleshare 1.4 with msysgit 1.9.5 but i am guessing the 1.4 release was built with an early version, could you please let us know which one?  Thanks

**Comment by dhufish** [comment]
Anyone looking to change the default notification server address in the source and build their own Sparkleshare 1.4 Windows binary, you'll need Git-1.8.0-preview20121022.

**Comment by hbons** [comment]
Moving this to the cloud in #1775.
