### ISSUE TITLE
Support without shallow clone

### ISSUE THREAD

**Issue by MiCHiLU** [hbons/SparkleShare#1631]
The Google [Cloud Source Repositories](https://cloud.google.com/tools/cloud-repositories/docs/) does [not support shallow clones](https://code.google.com/p/support/issues/detail?id=5753).

I got errors as below:
```
$ /Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core/git --exec-path=/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core clone --progress --no-checkout --depth=1 https://source.developers.google.com/p/<appid> $HOME/SparkleShare/.tmp/<appid>
Cloning into '$HOME/SparkleShare/.tmp/<appid>'...

error: RPC failed; result=18, HTTP code = 200
fatal: expected shallow/unshallow, got Error: internal server error
```

SparkleShare use the `--depth=1` option on repository checking [process](https://github.com/hbons/SparkleShare/blob/a2f6a1ee36b4d9b8b93130fa675303393782d94d/SparkleLib/Git/SparkleFetcherGit.cs#L123).

Please help for me.

**Comment by hbons** [comment]
You can untick the "Fetch Prior History" checkbox when adding a project to SparkleShare.

**Comment by MiCHiLU** [comment]
I had overlooked it. Thank you!
