### ISSUE TITLE
Remove Gravatar exceptions from logs

### ISSUE THREAD

**Issue by BarryThePenguin** [hbons/SparkleShare#1633]
Makes debugging client issues a bit of a pain.

Is there any objections to this?

**Comment by tst2005** [comment]
There is a way to disable Gravatar support (to deny connexion to third-party server) ?

**Comment by hbons** [comment]
@BarryThePenguin I'm fine with that. Does it show up all the time? I think it should show when an avatar was fetched successfully (it does this only once per day).
@tst2005 Yes: https://github.com/hbons/SparkleShare/wiki/Configuration-options We should make this more user friendly, as we should take privacy serious. I'm thinking about an alert bar at the top of the Events window "Would you like SparkleShare to fetch avatars from Gravatars.com? [Yes, please] [No, thanks]".

**Comment by tst2005** [comment]
@hbons Thanks. For now the XML edit is ok for me, but an entry in the SparkleShare Menu like the "Turn Notification On/Off" should be perfect!

**Comment by hbons** [comment]
@tst2005 I don't think it warrants an entry in the menu. This is typically something you want to set only once.

**Comment by BarryThePenguin** [comment]
The fetch happens once per day, but also happens on each app start if no Gravatar has been found. Would it be worth generating an identicon in the situation a Gravatar cannot be found, instead of throwing an exception?

If Gravatar is disabled, we can just show identicon instead.

**Comment by hbons** [comment]
I think the identicons are a bit ugly. We could write out each non-existing avatar anyway and check for 0-length files? Or we can just keep track whether we've checked today already.

**Comment by BarryThePenguin** [comment]
What about using the current user-icon-default.png and just writing that to the avatar folder for each Gravatar we don't find?

Otherwise, yes, just writing a 0-length file would work also. I don't see any reason to track who has been checked if we can just use the file system for that.

**Comment by hbons** [comment]
I like the idea of writing out our own default icon. We could apply a colour filter based on the email to make our own identicons. :)

**Comment by BarryThePenguin** [comment]
From a quick look at things, sounds like MD5 to HSL will provide better control over contrast and saturation.

https://zenozeng.github.io/color-hash/demo/ gives a good idea

It's javascript, but gives a https://github.com/zenozeng/color-hash

I'm not yet sure how we'd accomplish this in C#...

**Comment by hbons** [comment]
@BarryThePenguin don't worry too much about it. I can design a set as well. :)
