### ISSUE TITLE
Don't run Acrobat Reader (or make it optional)

### ISSUE THREAD

**Issue by tinloaf** [hbons/SparkleShare#1638]
I don't like long-running processes of Acrobat Reader on my system, since they grab the clipboard and thus interfere with programs like pwsafe, effectively intercepting my passwords.

Now, what has that to do with SparkleShare? I was wondering what was running Acrobat reader on my system, take a look at this: 
```
tinloaf@janeway ~ % ps alx | grep -i acror  
0  1000 11858 11838  20   0 152128 67784 poll_s Sl   pts/0      0:04 /opt/Adobe/Reader9/Reader/intellinux/bin/acroread --display :0 -progressPipe 3 -exitPipe 4
0  1000 20647 18861  20   0  10528  2108 pipe_w S+   pts/1      0:00 grep -i acror
tinloaf@janeway ~ % ps alx | grep 11838
0  1000 11838 11797  20   0  23256 13100 poll_s S    pts/0      0:00 /usr/lib64/nspluginwrapper/i386/linux/npviewer.bin --plugin /usr/lib32/nsbrowser/plugins/nppdf.so --connection /org/wrapper/NSPlugins/nppdf.so/11797-2/484718135
0  1000 11858 11838  20   0 152128 67784 poll_s Sl   pts/0      0:04 /opt/Adobe/Reader9/Reader/intellinux/bin/acroread --display :0 -progressPipe 3 -exitPipe 4
0  1000 20650 18861  20   0  10528  2176 pipe_w S+   pts/1      0:00 grep 11838
tinloaf@janeway ~ % ps alx | grep 11797
0  1000 11797     1  20   0 2967140 99888 poll_s Sl  pts/0      0:04 mono /usr/lib64/sparkleshare/SparkleShare.exe
0  1000 11838 11797  20   0  23256 13100 poll_s S    pts/0      0:00 /usr/lib64/nspluginwrapper/i386/linux/npviewer.bin --plugin /usr/lib32/nsbrowser/plugins/nppdf.so --connection /org/wrapper/NSPlugins/nppdf.so/11797-2/484718135
0  1000 20652 18861  20   0  10528  2100 pipe_w S+   pts/1      0:00 grep 11797
```

It looks like SparkleShare is running an nspluginwrapper (for whatever reason? It's not a browser...) and this is running the acroread plugin...

Would it be possible to stop this? Or at least make it optional? That would be awesome!

**Comment by hbons** [comment]
SparkleShare doesn't use Adobe Reader, or any PDF View directly for that matter. I've no idea what's causing this...

**Comment by hbons** [comment]
It does use a Webkit WebView to display the Recent Changes window. Maybe that's spawning it? It doesn't display any PDFs though. I've no idea how Webkit works.
