### ISSUE TITLE
OSX 10.11 beta El Capitan: Mono is broken

### ISSUE THREAD

**Issue by markusstoll** [hbons/SparkleShare#1639]
As Mono is broken with El Capitan, SparkleShare too won't run.

It seems they are searching to fix this in Mono, but so far no working fix available.

**Comment by hbons** [comment]
Do you have a link to the issue in the Xamarin bug tracker?

**Comment by markusstoll** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=31761

**Comment by markusstoll** [comment]
the latest 10.11 beta resolved the issue, so probably nothing to do for us
