### ISSUE TITLE
What is proper name for client-side encryption

### ISSUE THREAD

**Issue by simsong** [hbons/SparkleShare#1641]
At https://github.com/hbons/SparkleShare/wiki/Client-Side-Encryption it says that client-side encrypted repositories should be named `foo-encrypted` and `foo-crypto`. Which is correct?

**Comment by markusstoll** [comment]
foo-crypto is the correct one
You can see it in source file SparkleFetcherBase.cs 

Regards, Markus

**Comment by hbons** [comment]
I can't find this on the page... Where do you see this?

**Comment by simsong** [comment]
In the example it says:

"Alternatively, you can use the dazzle-script with the following command:

    sudo dazzle create-encrypted PROJECT_NAME

Apparently I saw the ```-encrypted``` and didn't realize that it was a parameter to the ```dazzle` script.
