### ISSUE TITLE
It takes 4 minutes to get a change

### ISSUE THREAD

**Issue by bflorat** [hbons/SparkleShare#1647]
Context : 
Git repository 1.7.1 under CentOS, created by dazzle (two weeks ago using the last version of dazzle)
Sparkshare clients : 1.4 under Windows Seven. Used to share .doc files.

Everything works great : changes are uploaded as soon as saved but others get a change (balloon + recent changes panel) after 3 to 5 minutes (average of 4 minutes). Changes are small (few KB .doc files) on a private WAN network.  

This leads to coordination issues among the team and conflicts (conflicts are correctly handled by Sparkleshare BTW).

If we restart Sparkleshare, we get changes immediately.

Any idea ?

**Comment by hbons** [comment]
This is due to the public notification server being down.

**Comment by hbons** [comment]
Duplicate of #1628.
