### ISSUE TITLE
can't add a project on HiDPi display

### ISSUE THREAD

**Issue by lordadamson** [hbons/SparkleShare#1652]
I have a macbook pro with retina display 2560*1600
 running fedora 22, that's what I get trying to set a project up.

![screenshot from 2015-09-01 22-00-48](https://cloud.githubusercontent.com/assets/6195060/9615064/325baa8a-50f6-11e5-9930-7cdeddb72f88.png)

**Comment by hbons** [comment]
Duplicate of #1613.
