### ISSUE TITLE
Moving remote paths to self-host - how?

### ISSUE THREAD

**Issue by netsgnut** [hbons/SparkleShare#1656]
I have a set of repositories that has been growing too quickly than I first anticipated, which means I will need to move to self-host. I know that [configuration options actually contains path to the remote URL](https://github.com/hbons/SparkleShare/wiki/Configuration-options), but so are the `.git` config files.

I am not sure if it is the complete step of doing it, but I guess if...
1. On the new box, after Dazzle-ing, do a `git clone git://somewhere.remote/my/repo`
2. Stop the current Sparkleshare installation
3. Change the configs, both the `~/.config/config.xml` and `.git/config` to the new repo
4. Start the Sparkleshare

...it should probably do the trick? Thanks.

**Comment by cebe** [comment]
As far as I see you also need to git pull from the old host and git push to the new one.

**Comment by netsgnut** [comment]
@cebe, does that mean doing a `git clone` in the new box? Or is there a difference to it too? Thanks.

**Comment by cebe** [comment]
Oh I see, should work that way too.
