### ISSUE TITLE
OrganizationName/RepositoryName could be synced to <sparkleshare>/directory/subdirectory

### ISSUE THREAD

**Issue by ph-hs** [hbons/SparkleShare#1657]
By default, it is just going to be <sparkleshare>/RepositoryName

It would be great if there were a checkbox in the setup wizard, for "use fully qualified directory structure", that made a parent folder for the OrganizationName, and had the mounted repo as RepositoryName within that.

**Comment by BarryThePenguin** [comment]
I like the premise of this. I currently have issues with multiple teams where each team has similar named folders, but people can also be on multiple teams. We currently prefix the folders with the team name so they don't clash in the SparkleShare directory.

I think using the organisation/team/user name to distinguish projects is a good idea. That way we end up with

TeamA/Foo
TeamA/Bar
TeamB/Foo
TeamB/Bar

However, this does fall into the same issue as being able to manually specify where SparkleShare repositories sit on a file system. Similar to #1642 and #1602

**Comment by hbons** [comment]
I like this idea. What about we use the domain name to group projects?

**Comment by ph-hs** [comment]
I'm not sure what "domain name to group projects" means, dude.

**Comment by hbons** [comment]
For example: a folder called "github.com" keeping all your github projects.

**Comment by ph-hs** [comment]
Yes, good idea.

**Comment by hbons** [comment]
So grouping by host has been implemented now (for example: SparkleShare/github.com/myproject), but I guess it doesn't solve the actual issue. Having two subfolders, one for the host and one for the org, would be too much in my opinion. Specially when you only use one or two hosts or orgs.

So what about grouping like this:

```
SparkleShare/hbons on github.com/myproject
SparkleShare/hbons on github.com/myotherproject
SparkleShare/BarryThePenguin on bitbucket.org/myotherproject
```

The status icon menu would only show the project name, unless there are multiple projects with the same name, in that case we'll add the username: `hbons - myproject`.

**Comment by BarryThePenguin** [comment]
That looks good. We have a single organisation and teams are identified by username. Using your implementation it would look like this:

```
SparkleShare/crossroads - vision100.org/guidelines
SparkleShare/crossroads - vision100.org/committee
SparkleShare/focus - vision100.org/guidelines
SparkleShare/focus - vision100.org/team workspace
```

I like that, looks good!

**Comment by ph-hs** [comment]
Great work, Hylke

**Comment by hbons** [comment]
Closing this. I'll have some more custom location stuff planned, but this should be good for now.
