### ISSUE TITLE
Specify notification server in the "Add hosted Project" wizard

### ISSUE THREAD

**Issue by ph-hs** [hbons/SparkleShare#1658]
It would be great to specify your own fanout in the wizard for "add hosted project". It means non-technical  end-users can do it too.

Better still that it's overriable per project (rather than global as it is now), but maybe that's a different issue.

**Comment by hbons** [comment]
You should be able to specify a notification server per project already.

**Comment by ph-hs** [comment]
Is that by editing the config file by hand - ~/.config/sparkleshare/config.xml - or in the add-project wizard (I couldn't see it).

**Comment by hbons** [comment]
Plugins and Invites (see wiki) can override the notification service url. People shouldn't have to specify it in the dialogue.

**Comment by hbons** [comment]
And yes, you can also edit the config.xml if you want, again the wiki has more info.
