### ISSUE TITLE
Sparkleshare doesn't work with new Git-Credential-Manager-for-Windows?

### ISSUE THREAD

**Issue by AaronJWhite** [hbons/SparkleShare#1661]
Hello,

It seems like SparkleShare is not compatible with the new [Git-Credential-Manager-for-Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows).
I am using the git credential manager to manage user/pass for connecting to my git over ssl. The git credential manager works when testing in git bash and connecting through the SublimeGit plugin I use.

Here is the error I get from SparkleShare in the logs:
20:57:29 | Fetcher | git: 'credential-manager' is not a git command. See 'git --help'.

Typing git credential-manager into command prompt does give a response though.

I'm not sure if SparkleShare is to blame, but since the credential-manager is working with my other tools I thought I should start here.

PC: Windows 7 (x64)
git version 1.9.4.msysgit.1

**Comment by AaronJWhite** [comment]
Hi guys, 
Would you consider this an issue? I built SparkleShare from source and I still have the same issue.

**Comment by jthg** [comment]
I was able to get around this issue by installing Git-Credential-Manager-for-Windows to SparkleShare's own copy of Git.

For my machine, it was download gcm-v1.0.0.zip, open an admin command prompt, and run `git-credential-manager.exe install --path "C:\Program Files (x86)\SparkleShare\msysgit"`.

**Comment by AaronJWhite** [comment]
Thanks for the reply! I no longer user SparkleShare, but I'm sure it will help someone in future.
