### ISSUE TITLE
Let plugins define their own notification service

### ISSUE THREAD

**Issue by planio** [hbons/SparkleShare#1662]
I think it would make sense that Git hosting services (SparkleShare plugins) host their own notification servers in order to

1. keep data (even if it's just hashes) contained within the same set of trusted parties,
2. help reduce load on the central notifications.sparkleshare.org server, and
3. provide a consistent service level (i.e. availability, responsibility in case of downtime, etc) to users. 

In order to achieve this, we could add a configuration option to plugin xml files which specifies the notification server to be used and write the custom ```announcements_url``` tag to the respective ```folder``` section within ```config.xml``` whenever a folder of that plugin type gets created.

Background: At [Planio](https://plan.io/), we've been offering [SparkleShare as our No. 1 file sync client](https://plan.io/synchronize-documents-using-planio-and-sparkleshare/) for non-developers and it's a very popular way for our users to access their shared data. We'd love to host our own notification server in order to accomplish 1. though 3. above. We'd just need a way to make our deployed clients pick up the change and use our server.

**Comment by hbons** [comment]
Glad you're still using SparkleShare. :)
This should already be possible: https://github.com/hbons/SparkleShare/blob/master/SparkleShare/SparkleSetupController.cs#L359

Maybe it's a bug that causes it not to work?

**Comment by hbons** [comment]
Also I'll accept a pull request if you want to update the supplied plugin with the new announcements_url value.

**Comment by yeah** [comment]
Oh, sounds awesome. I'll prepare a pull request for that!

**Comment by yeah** [comment]
Works like a charm. I think this issue can be closed, then.
