### ISSUE TITLE
Wrong aspect ratio in GNOME Software

### ISSUE THREAD

**Issue by andreasn** [hbons/SparkleShare#1667]
![screenshot from 2015-11-21 02-26-26](https://cloud.githubusercontent.com/assets/209895/11315721/4b450826-8ff7-11e5-962b-09f4a44ee528.png)

I'm happy to take a new one.

**Comment by hbons** [comment]
Hey Andreas! I don't know where this image is fetched from or who made it... It's not in the SparkleShare repo...

**Comment by andreasn** [comment]
Hm, I'll ask around and see where it comes from.

**Comment by hbons** [comment]
@andreasn Any clue? :)

**Comment by andreasn** [comment]
totally forgot about this of course. Will check

**Comment by andreasn** [comment]
Apparently it comes from Fedora.

**Comment by andreasn** [comment]
I'll try and cook up a fix to have a screenshot (with proper image ratio) added to https://github.com/hbons/SparkleShare/blob/master/SparkleShare/Linux/sparkleshare.appdata.xml

**Comment by hbons** [comment]
New appdata file with screenshots now in master. :)
