### ISSUE TITLE
Clearing notifications in gnome-shell raises the SparkleShare main window

### ISSUE THREAD

**Issue by glunardi** [hbons/SparkleShare#1669]
Using Fedora 23 with  SparkleShare 1.5 
(* master e496d2d avatars: Update certificate for gravatar.com. Closes #1545 :-) )

Works really quite well. Over 14 days up-time now with no issue.

One cosmetic thing using gnome-shell (trying at least), version 3.18.1:
When clearing the notifications using the gnome-shell, if there is a sparkleshare notification, it will raise the window (create one if closed) instead of just dismissing the notification(s).

Not sure how to best troubleshoot it.

Best,
-Guy

**Comment by hbons** [comment]
SparkleShare looks at the reason for the notification being closed here:
https://github.com/hbons/SparkleShare/blob/master/SparkleShare/Linux/SparkleBubbles.cs#L56

It seems gnome-shell gives User as the reason for the close, but it probably should be CloseReason.Expired when dismissing a bunch of notifications? https://git.gnome.org/browse/notify-sharp/tree/src/Global.cs

Maybe @allanday knows more.

**Comment by glunardi** [comment]
With that information, I've ran dbus-monitor against [ interface='org.freedesktop.Notifications' ]

The sent signal when clicking the close icon in the gnome-shell UI is:

signal time=1448636733.343049 sender=:1.15 -> destination=(null destination) serial=18354 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 505
   uint32 2

So it would seem "2" is sent out.

**Comment by hbons** [comment]
Right, that doesn't seem to be the intent when dismissing all the notifications, unless the API changed?
It seems the notification behaviour has changed a lot in GNOME and perhaps we should look at removing this feature (raising the events window on click) altogether.

**Comment by glunardi** [comment]
According to https://developer.gnome.org/notification-spec/#signals 

It has changed to: "The notification was dismissed by the user."

Hmm, maybe we need to adjust the behavior.
