### ISSUE TITLE
SparkleShare silently hangs if remote server fingerprint has changed

### ISSUE THREAD

**Issue by olegstepura** [hbons/SparkleShare#1673]
While playing with `Docker`+`SparkleShare` I've faced an issue. `SparkleShare` 1.4 silently hang on trying to fetch remote repo, or making sync on current changes.

I've digged all the issues here on two things that don't play nice together: SparkleShare with it's own `ssh-agent` and all variants of other `ssh-agents` being used by geeks on Windows PCs (cygwin in my example) #697 #1286 and even #1573. I thought this is the issue. But occidentally I found out that it's not (debugging what happens and trying to login to the host with `ssh.exe` provided with `SparkleShare`).

The reason: while recreating the Docker image SSH fingerprint has changed. All repositories were mounted as a volume and were not lost. Due to fingerprint mismatch SSH failed to login.

Nothing strange in logs. No other clear place to find out the cause of an issue.

I suggest any errors from ssh, git or any other used 3rd party software should be caught and displayed to the user.

Thanks!

**Comment by hbons** [comment]
SparkleShare does check for this, but the method is a bit hacky. It just parses the SSH output:
https://github.com/hbons/SparkleShare/blob/master/SparkleLib/Git/SparkleRepoGit.cs#L727

It seems something is going wrong there.

**Comment by hbons** [comment]
SparkleShare now uses its own SSH configuration instead of ssh-agent, so this should no longer happen. Agree better error messages are needed, there are a couple issues that track this already.
