### ISSUE TITLE
Why does new OSX version requires OSX 10.11?

### ISSUE THREAD

**Issue by vsviridov** [hbons/SparkleShare#1675]
Considering it's a UI wrapper around git for most part shouldn't it be backwards compatible quite far back?

**Comment by zzkt** [comment]
Version 1.5.0 appears to work fine on OSX 10.9.5 at least.

**Comment by vsviridov** [comment]
Here's what I observe
![Finder Icon](http://i.imgur.com/G4AAuTP.png)
![Launch dialog](http://i.imgur.com/7fgzbeo.png)

**Comment by zeigerpuppy** [comment]
Version 1.5 will also not start on Lion, V1.4 works fine

**Comment by hbons** [comment]
Something going on with the packaging. Still trying to find the problem.

**Comment by fmjrey** [comment]
This issues is preventing me from inviting my work colleagues to use SparkleShare.
May I encourage a resolution sooner rather than later?

**Comment by fmjrey** [comment]
A possible hint:

**Comment by joshchang** [comment]
I ran into the same problem but I was able to build it for my system. If anybody wants a binary shoot me a message.

**Comment by fmjrey** [comment]
Hi Josh, did you just build it without changing the code?

**Comment by joshchang** [comment]
Yup, ran a git clone and followed the directions here: https://github.com/hbons/SparkleShare/blob/master/SparkleShare/Mac/README.md

I built it within Xamarin Studio though you can do it on the command line as well. It generated an app bundle under SparkleShare/SparkleShare/Mac/bin/Debug

**Comment by fmjrey** [comment]
I tried building it as well and it first produced a 287Mb .app file!
It looks like the Resources/git folder is much bigger for some reasons, 243Mb or so.
So I replaced it with the 43Mb version found in the "official" .app file.
Tested in my Yosemite machine and it worked fine, was able to use it on a github repository.
I did not have to change any line of code for that to work, was on my macbook pro with Yosemite 10.10.5, Xcode 7.2.1, and Xamarin Studio 5.10.3.
Oh, and I did checkout 1.5.0 tag before build, as I'm unsure about master status.
Still, it would be good to have a fixed official download, much easier for people find and use.

**Comment by hbons** [comment]
The Info.plist had the minimum macOS version set to 10.6, whilst Xamarin.Mac apps require at least 10.7. It could be that the Xamarin.Mac launch script got confused by that?

I pushed an update to the Info.plist to set the minimum version to 10.7.

**Comment by hbons** [comment]
I think this, together with the next release being built with Xcode 8 tools (thanks @fmjrey for the links), should fix the issue. Feel free to reopen if it doesn't.

<img width="497" alt="screen shot 2017-09-09 at 3 47 59 pm" src="https://user-images.githubusercontent.com/103326/30241191-487acba4-9576-11e7-8de1-1bd6fc376b10.png">
