### ISSUE TITLE
smudge/clean filters not used

### ISSUE THREAD

**Issue by zeigerpuppy** [hbons/SparkleShare#1677]
I am trying to use smudge/clean filters for gnupg encryption and have hit a snag.
if i run git from the command line (in OS X)
 ```
  git add -A
   git commit -a -m "my test"
   git push origin master
```
then my filter is activated and pushed files are encrypted properly 
(configured in the repo .git/config and .git/info/attributes)

However, when sparkleshare runs the git add/commit/push, then the filters are not activated.
I am wondering if the executable which sparkleshare uses (git --exec-path="/Applications/Networking/SparkleShare.app/Contents/Resources/git/libexec/git-core") does not support smudge/clean filters or whether the gpg command may be unavailable in the sparkleshare path?

**Comment by zeigerpuppy** [comment]
full path in commands helped with this issue

**Comment by hbons** [comment]
Have you tried SparkleShare's encryption feature?
It uses the same smudge/clean filters but with openssl: https://github.com/hbons/SparkleShare/wiki/Client-Side-Encryption
