### ISSUE TITLE
is it possible to run notification server on multiple ports?

### ISSUE THREAD

**Issue by zeigerpuppy** [hbons/SparkleShare#1679]
I have installed the fanout server and also recompiled it to run on port 21 (as mobile clients often don't have 1986 open).
Is it possible to tell SparkleShare to look for notifications on two different notification server addresses.
I have tried adding another server to the config.xml file but it only checks the first one.
I guess the other option is through firewall rules.

**Comment by hbons** [comment]
You can set different announcements url for differnent folders, but not multiple urls per folder.
See https://github.com/hbons/SparkleShare/wiki/Configuration-options
