### ISSUE TITLE
No more synchronization from some computer

### ISSUE THREAD

**Issue by ludogre** [hbons/SparkleShare#1681]
Hi!

I've got many user that could not synchronize their sparkleshare project any more from few month.
Many of them are running on Windows.
But, some of them are running GNU/Linux or Mac OSX.

In client side, if they try to add a new project, Sparkleshare say: "Could not fetch host key".
In server side, I've got this one: "fatal: no matching mac found: client hmac-md5,hmac-sha1,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96 server
hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com [preauth]"

Any idea?

**Comment by hbons** [comment]
This looks like a messed up SSH configuration on the server. I can' tell exactly, but it seems it can't create the fingerprint for the clients to check.

**Comment by ludogre** [comment]
OK. I have fixed this for a long time ago. Sorry to not have noticed it here.
Windows needs hmac-sha1 encryption. So, it's necessary to add hmac-sha1 in MACs options in /etc/ssh/sshd_config file (on Debian GNU/Linux).

**Comment by hbons** [comment]
Thanks for documenting it here!
