### ISSUE TITLE
Sync without GUI login?

### ISSUE THREAD

**Issue by biocyberman** [hbons/SparkleShare#1683]
I read somewhere about a year ago (2015) that SparkleShare only does sync when user login to desktop environment. How is it now? I connect a remote server to my SparkleShare repo and work remotely to this server a lot in the terminal. I have to do git command manually to get the repo synced on this remote server. If SparkleShare does not have a true (headless) daemon, is there an option to setup a cronjob for it?

**Comment by mlanner** [comment]
+1

**Comment by hbons** [comment]
Thanks for your patience. :P
This is not currently possible. I think it's a nice idea to have a headless SparkleShare daemon with some simple configuration commands for servers, but I'm not really interested in working on that myself.

If someone can implement this in a nice way I will accept a patch.

**Comment by hbons** [comment]
SparkleShare now has an experimental CLI mode: https://github.com/hbons/Twinkle.

If you like this work and want to support development, I’m looking for sponsors since I’m currently jobless: https://github.com/sponsors/hbons.
