### ISSUE TITLE
Ransomware detected by Malwarebytes

### ISSUE THREAD

**Issue by jortok** [hbons/SparkleShare#1684]
Hi guys,

I just found that the software Malwarebytes Anti-Ransomware (BETA) 0.9.15.416 is detecting two files as ransomware. Attached you will find screen captures of the issue reported by the software and the exe files.

**Comment by hbons** [comment]
Can you attach the images to the issue? No need to have them in a .zip.

**Comment by jortok** [comment]
Sure.
![sparkleshare](https://cloud.githubusercontent.com/assets/10870694/14366352/e725b0e0-fcd7-11e5-8a39-3f1319c0e020.png)
![git](https://cloud.githubusercontent.com/assets/10870694/14366353/e7285638-fcd7-11e5-917e-c68e357a87f1.png)

**Comment by cebe** [comment]
it should be reported to the Anti-Ransomware software instead.

**Comment by hbons** [comment]
Must be the openssl commands that gives this a false positive?

**Comment by hbons** [comment]
Closing this as there doesn't seem much we can do about this...
