### ISSUE TITLE
Doesn't sync if folder has a dot in its name on OS X El Capitan

### ISSUE THREAD

**Issue by semencov** [hbons/SparkleShare#1685]
The SparkleShare does not sync if there is a dot in the folder's name. I've added a project which name was a domain name with `.com` on the end, but it didn't sync new changes. However, when I did rename the repo to replace the dot like `-com` and added it like new project to the SparkleShare every thing works like it should be.

If confirm, please append the name restriction rules in the wiki.

**Comment by hbons** [comment]
I can't reproduce this. it works fine for me on GitHub with a repo called "test.com". This may have been fixed in a newer version.  Feel free to repopen if it doesn't.
