### ISSUE TITLE
I could not generate "aspx.designer.cs" from cs file

### ISSUE THREAD

**Issue by karim10** [hbons/SparkleShare#1686]
Hello SparkleShare Community,
First of all I want thank you for this awesome program.
I make a git clone of SparkleShare source with my Visual Studio 2015 IDE,But I want to generate a design mode of SparkleSetup.cs file to make some modification. When I select the project I don't get "Convert to Web Application" option under "Project" in the Menu bar.
Thank you in advance.

**Comment by hbons** [comment]
I don't know what this option does, as I don't use Visual Studio myself. What are you trying to do?

**Comment by karim10** [comment]
Hello,
I want make some modification in the UI window.For example to add a text box into the configuration window I add ContentCanvas.Children.Add (address_box) in SparkleSetup.cs. I want use the graphic mode of visual studio with drag and drop of components ,it's much easier.

**Comment by hbons** [comment]
Most UI code is written by hand and doesn't use layout files. I think that's why it doesn't work.

**Comment by karim10** [comment]
okay thank you :)
