### ISSUE TITLE
Error : Could not copy "obj\Debug\SparkleShare.exe" to "..\..\bin\SparkleShare.exe" after each modification and build

### ISSUE THREAD

**Issue by karim10** [hbons/SparkleShare#1687]
Hi everyone,
Greeting from Tunisia
After each modification and build I got this warning "MSB3026: Could not copy "obj\Debug\SparkleShare.exe" to "....\bin\SparkleShare.exe". Beginning retry 10 in 1000ms. The process cannot access the file '....\bin\SparkleShare.exe' because it is being used by another process." and this error "MSB3027: Could not copy "obj\Debug\SparkleShare.exe" to "....\bin\SparkleShare.exe". Exceeded retry count of 10. Failed". So after each modification and build I have to delete all my bin and obj folders and restart Visual Studio (I got this after consulting this [issue](https://github.com/hbons/SparkleShare/issues/1623) ).Can anyone help me.
Thank you in advance

**Comment by hbons** [comment]
I think this is because of a lingering process? Task manager should let you kill it. Anyway, that's the best I can think of and you probably don't need this anymore as this issue is so old so closing. :)
