### ISSUE TITLE
Offer Flatpak download

### ISSUE THREAD

**Issue by hbons** [hbons/SparkleShare#1690]
Offer a [Flatpak](flatpak.org) download based on the GNOME platform.

Blockers, help appreciated:
- [x] Ubuntu dependencies won't compile inside the sandbox (`libdbusmenu`, `libindicator`, `libappindicator`, `appindicator-sharp`)
- [x] xdg-open actions don't work, needs portal

Work is happening on the `xdg-app` branch.
The `xdg-app-builder` spec can be found here: https://github.com/hbons/org.sparkleshare.SparkleShare

**Comment by probonopd** [comment]
Would you be interested in an [AppImage](http://appimage.org/)? It is a bundle format that is not tied to any particular desktop or distribution. Here is an example of a small Mono-based app packaged this way: https://bintray.com/probono/AppImages/Graphmonkey/view#files - just download, `chmod a+x` it, and run.

**Comment by hbons** [comment]
I haven't heard about AppImage, it looks pretty cool.

What I like about Flatpak is that it runs apps sandboxed.
SparkleShare is a GNOME app, so it's great that all the dependencies are already provided to me as a runtime, so that's not a concern. Also the GNOME Software integration is really nice.

So I think Flatpak is better suited to SparkleShare as a project. Definitely cool with it if people wanting to make an AppImage bundle. :)

**Comment by hbons** [comment]
Portal support for opening uris will be available in the next GTK: https://blogs.gnome.org/mclasen/2016/07/08/portals-using-gtk-in-a-flatpak/
Fixed in SparkleShare: https://github.com/hbons/SparkleShare/commit/0bd79d48ac4aab17c558c3dd1e42e6443d06d6c4

**Comment by hbons** [comment]
The only thing blocking a release of a Flatpak is support for Ubuntu. I've added the up-for-grabs label, so if anyone knows how to compile appindicator please go for it! :)

**Comment by hbons** [comment]
With the news that Ubuntu is moving to GNOME (yay!), AppIndicator support is no longer needed.

**Comment by hbons** [comment]
Flatpak package is now available from http://www.flathub.org.
