### ISSUE TITLE
Implementing new backend error "Failed to load new backend"

### ISSUE THREAD

**Issue by karim10** [hbons/SparkleShare#1691]
Hello everyone,
I'm trying to implement a new back-end for Sparkle. I added my backend files (SparkleFetcher and SparkleRepo) to SparkleLib I added them also to MakeFile.am file like this : 
//////////////////////////////////////////////////////////////////////////////////////////////////
ASSEMBLY = SparkleLib
TARGET = library

ASSEMBLY_INFO_SOURCE = Defines.cs

SOURCES =  \
	SparkleFetcher.cs \ (new backend Fetcher file)
	SparkleRepo.cs \ (new backend Repo file)
	SparkleBackend.cs \
	SparkleConfig.cs \
	SparkleExtensions.cs \
	SparkleFetcherBase.cs \
	SparkleFetcherSSH.cs \
	SparkleListenerBase.cs \
	SparkleListenerFactory.cs \
	SparkleListenerTcp.cs \
	SparkleLogger.cs \
	SparkleRepoBase.cs \
	SparkleUser.cs \
	SparkleWatcher.cs \
	SparkleWrappers.cs

install-data-hook:
	for ASM in $(EXTRA_BUNDLE); do \
		$(INSTALL) -m 0755 $$ASM $(DESTDIR)$(moduledir); \
	done;

uninstall-hook:
	for ASM in $(EXTRA_BUNDLE); do \
		rm -f $(DESTDIR)$(moduledir)/`basename $$ASM`; \
	done;

include $(top_srcdir)/build/build.mk
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Unfortunately When I test I get an error : Failed to load backend.
when I displayed the exception content I got this:
![karim](https://cloud.githubusercontent.com/assets/6545840/15748010/15d5087c-28d5-11e6-86c7-38531a7ed296.png)

Thank you in advance !!

**Comment by hbons** [comment]
What are your class names? and are they in the SparkleLib namespace?

**Comment by karim10** [comment]
Hello hbons,
Yes I added new backend classes to the name space SparkleLib.Fossil and I can create instance of SparkleLib.Fossil.SparkleFetcher.cs in SparkleControllerBase.cs . so tried this and it works and my new backend is successfully loaded
`SparkleLib.Fossil.SparkleFetcher a = new SparkleLib.Fossil.SparkleFetcher(folder_path, Config);
            try {
                repo = (SparkleRepoFetcher) Activator.CreateInstance (
                    a.GetType(),
                    new object [] { folder_path, Config });
                
            } catch (Exception e) {
                SparkleLogger.LogInfo ("Controller", "Failed to load backend '" + backend + "' for '" + folder_name + "': ", e);
                return;
            }`
I thought that may be I have a problem on the accessibility to SparkleFetcher constructor but I checked it and it's setted at public.
If I continue loading my backend this way can it affect the functioning of my backend.

**Comment by hbons** [comment]
So what are you putting into the setup page? the address will need to start with "fossil+ssh://" for the backend to be parsed as Fossil. Alternatively you can make a plugin with `<backend>Fossil</backend>` and see if that works.

**Comment by karim10** [comment]
In fact I add " backend = "Fossil"; " in SparkleFetcherBase I want to use only this backend by default so in Setup page I have only 2 text box the server url and the project name.
what do you think about it ??

**Comment by hbons** [comment]
That won't do the trick. The fetcher type is dynamically loaded based on the backend string. SparkleShare has to know what to look for. Based on the info you enter on that page. 

I'd suggest try the plugin approach and see if that works: https://github.com/hbons/SparkleShare/wiki/Plugins

Fill it out and put the .xml in `~/.config/sparkleshare/plugins/` and it should show up on the setup page.

**Comment by karim10** [comment]
Thank you Hbons I will try this :)
