### ISSUE TITLE
only 4 character password for encrption

### ISSUE THREAD

**Issue by toby-1-kenobi** [hbons/SparkleShare#1696]
I'm using Ubuntu 16.04 with dazzle for the server the first client is Ubuntu 16.04 and the second is Ubuntu 15.10. I created an encrypted project with the first client and used a 12 character string for the password. I added the project to the second client. When it asked for the password I entered it but the continue button remained disabled. When I deleted the password back to the first 4 characters the continue button enabled and clicking continue then gave the impression that the project had been successfully decrypted, but only when I looked at the content of the files did I see that it hadn't been.

**Comment by toby-1-kenobi** [comment]
This may be related to issue #1315

**Comment by toby-1-kenobi** [comment]
Looks like my Ubuntu 15.10 client is using SparkleShare 1.2 and my Ubuntu 16.04 client is using SpakleShare 1.5

I'm guessing this is the same as issue #1649 and is probably fixed in SparkleShare 1.5 so I'll try to get that version on Ubuntu 15.10, hopefully it'll work.

**Comment by cknoll** [comment]
@toby-1-kenobi did Version 1.5. solve the problem for you?
