### ISSUE TITLE
sha256 verify git source download when building

### ISSUE THREAD

**Issue by hbons** [hbons/SparkleShare#1701]
On Mac we download Git when building to bundle inside the SparkleShare package. The download will need to be verified using sha256: https://github.com/hbons/SparkleShare/blob/master/SparkleShare/Mac/checkGit.sh

**Comment by orien3243** [comment]
I don't see anything on github that allows for checking downloads of any kind. Perhaps I'm not using it right. (its possible I goofed or missed it)

I tried to see if another source offered signed packages and kernel.org does offers signatures. They sign the source with gnupg and offer sha256 hashes. 

I notice that the hashes from kernel.org do not match the sha 256 signature on github.

bff7560f5602fcd8e37669e0f65ef08c6edc996e4f324e4ed6bb8a84765e30bd  git-2.9.0.tar.gz (kernel.org)
dad202c1a2dec4caa2a6cab5c1ca8dc486206fd4a39585613bece8aa8c9da93b  git-2.9.0.tar.gz (github)

I'm not sure why this is the case, they seem the archives seem to be identical. I extracted them and they appear to be the same, I just looked at the files sizes of each file/folder. So IDK if that is a big deal or not, I've never seen this happen, I usually just haphazardly download/run all software via apt-get on debian/ubuntu/etc.

would it just be easier to download from kernel.org or one of their mirrors and use either pgp keys or sha 256 sums? 

https://www.kernel.org/pub/software/scm/git/
https://www.kernel.org/pub/software/scm/git/sha256sums.asc

**Comment by hbons** [comment]
Hey @orien3243. Downloading from kernel.org directly sounds good to me! :)

**Comment by orien3243** [comment]
alrightly, then. :D

**Comment by hbons** [comment]
It's actually better, cause the hash is provided by the developers themselves, and updating the Git version will be somewhat easier too. :)

**Comment by hbons** [comment]
SHA256 for the git download is checked now. We now download binaries provided by the GitHub team, so this had to be reworked a bit. But it was much easier due to your initial implementation. Thanks! :)
