### ISSUE TITLE
using two remotes

### ISSUE THREAD

**Issue by bryanwillis** [hbons/SparkleShare#1707]
I want to push to two places at the same time. So far it appears that I got it right, but I'm not sure if there's any problems with doing this as I didn't see any docs on it and I'm not an expert with git. Also, if there isn't anything wrong with doing this, it will probably be useful to others. 

I have two remotes. One is WPENGINE which has [git integration](https://wpengine.com/git/) and the other is github. 
### **Here are the steps I took...**

1) Add my Sparkleshare CLIENT ID/SSH Key to both Github and ["My own server" (in this case WPENGINE)
](https://wpengine.com/support/set-git-push-user-portal/)

2) Add a sparkleshare hosted project and select _"On my own server"_ 
- **Address :** git@git.wpengine.com
- **Remote Path :** staging/INSTALLNAME (install name is the name of the wpengine site install found in https://my.wpengine.com/)

3) Quit sparkleshare and add the second remote origin (github)

``` bash
git remote set-url --add origin ssh://git@bitbucket.org/user/myproject.git
```

4) That's it. My changes seem to be pushing to both github and WPENGINE fine without any problems as far as I know. It seems like this could be achieved with any two or more remotes, github, bitbucket, etc.
### **Below are my sparkleshare configs for reference:**

**Sparkleshare config:** `~/USERNAME/.config/sparkleshare/config.xml`

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<sparkleshare>
  <user>
    <name>Bryan Willis</name>
    <email>bryanwillis1@gmail.com</email>
  </user>
  <notifications>True</notifications>
 <folder>
    <name>disputebils16</name>
    <identifier>12345****************************************</identifier>
    <url>ssh://git@git.wpengine.com/staging/disputebils16</url>
    <backend>Git</backend>
  </folder>
</sparkleshare>
```

**Sparkleshare plugin:** `~/USERNAME/.config/sparkleshare/plugins/git.wpengine.com.xml`

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<sparkleshare>
   <plugin>
      <info>
         <name>git.wpengine.com</name>
         <description>ssh://git@git.wpengine.com</description>
         <icon>own-server.png</icon>
      </info>
      <address>
         <value>ssh://git@git.wpengine.com</value>
         <example />
      </address>
      <path>
         <value />
         <example>/path/to/project</example>
      </path>
   </plugin>
</sparkleshare>
```

**Comment by hbons** [comment]
Thanks for documenting. :)
