### ISSUE TITLE
allow user to decide where to store repo

### ISSUE THREAD

**Issue by kaystrobach** [hbons/SparkleShare#1709]
I know: https://github.com/hbons/SparkleShare/wiki/Configuration-options

But a normal user would never edit an xml file, so it would be brilliant to

* a) detect folder movements automatically (and update config) - should atleast be possible on osx
* b) let the user decide where to store the repo on creation

**Comment by hbons** [comment]
This comes up every now and then, but I've yet to find a good use case for this...

**Comment by aggsol** [comment]
There is no need for this. When would you want to do that?

**Comment by kaystrobach** [comment]
use case is very easy in my opinion:

we use a structure like that in gitlab:

* group A
 * project A
 * project B
 * internal-contracts
* group B
 * project A
 * project B
 * internal-contracts

If you want to share both `internal-contracts` repos with one guy in the contract management your are screwed, as you do not know, which one is which, and i do not talk about 2 or 3 projects like that, but atleast 50 per year ...

Regarding moving, I would do it like that:

* listen filesystem events
* detect move or rename of watched folder
* update config

Having that it's quite easy to move the files in another DMS or similar stuff.

**Comment by kaystrobach** [comment]
And by the way transparend watching and moving folders feels the most natural for me, as this is also possible with normal git repos (from the cli).

**Comment by hbons** [comment]
In the upcoming 2.0 release SparkleShare will group repositories by source/group automatically, see #1657.

Rename detection already works within the SparkleShare folder. For anything outside the SparkleShare folder it's tricky, I've noticed file system events aren't that reliable and it will require watching the whole home folder.

**Comment by kaystrobach** [comment]
you could still use an explorer / finder extension to check for sparkleshare folders, ... this can also result in folder icons, which indicate uploads, conflicts, etc.

**Comment by ianchanning** [comment]
I think the option b) suggested of being able to select the installation location is a very good one. This is common in both Dropbox and Google Drive and pretty much every installion program.

**Comment by ianchanning** [comment]
Bare in mind - I'm searching for this topic because this is the third time now that I've had to install a new SparkleShare project and then go hunting through my browser history for how I'm supposed to move the directory.

**Comment by ianchanning** [comment]
A further, possibly more similar, example is cloning an existing repository in Atlassians SourceTree. This always includes a destination path.

![2016-08-07 21_32_32-sourcetree](https://cloud.githubusercontent.com/assets/233318/17464766/ecbf8ce6-5ce6-11e6-9c08-a20c3c353391.png)
