### ISSUE TITLE
Copying files 

### ISSUE THREAD

**Issue by bryanwillis** [hbons/SparkleShare#1711]
Not sure if this is a limitation of git itself, a sparkleshare bug, or something I screwed up. I have a remote setup that works fine. I have a mac and right clicked and duplicated a file already in the repo. I then renamed it, opened it and edited the contents of it. 

I later went on my server and instead of two files there was three. The original, the copy and the renamed version.  Any suggestions here?

**Comment by gerhard-tinned** [comment]
In general, git should be clever enough to detect renamed files. 

When you creaded the copy, the following happened: 
SparkleShare detected the change almost immediately and triggered git to add/commit/push the new file. 

Then you renamed it. Which should have triggered SparkleShare again. This time when git was triggered to add the changes, it should have detected the rename operation as the files content did not change. That is then committed and pushed to the server. 

The current version of the repository will only show the renamed file but the history will show of course all 3 files. 

If the current version of the repository shows still all 3 versions, then I guess something went wrong. The logs of that time should give more details of what went wrong. :)
