### ISSUE TITLE
No right click menu in system tray on openSuse Tumbleweed KDE

### ISSUE THREAD

**Issue by JimmyBuzzard** [hbons/SparkleShare#1713]
The icon appears in system tray, but I can not get to the menu where I can add project. Both left and right click do not work.  

The only suspicious thing in the output are these two lines:  
**(mono:12269): Gtk-WARNING **: Theme directory base/ of theme oxygen has no size field**

**Message: console message: file:/// @41: SyntaxError: Unexpected token ';'. Expected ')' to end a 'if' condition.**

**Comment by hbons** [comment]
which version is this?

**Comment by JimmyBuzzard** [comment]
It's a 1.4. [Here](http://download.opensuse.org/tumbleweed/repo/oss/suse/x86_64/sparkleshare-1.4-1.3.x86_64.rpm) is the package.

**Comment by hbons** [comment]
I don't use openSUSE nor KDE, so if someone could look into this that would be great.

**Comment by nekohayo** [comment]
Interestingly enough, I also have this issue with Fedora 24 and GNOME (but for some reason, even Fedora 24 ships a version that is really ancient)... the icon is there but there's no way to interact with it… sometimes. At other times it works.

Anyway, I do wonder if there could be a better way to interact with it than a (minuscule+hidden) "tray icon", but I'm afraid I don't know what the best practice for this is, nowadays... doing something to interact directly with the app icon in the dock (in gnome-shell and OSX) and having an app that keeps running even if you close the windows, until you use a "Shut down SparkleShare" button somewhere in the UI?

**Comment by hbons** [comment]
@nekohayo completely agree. I'd like to have the menu in the app icon itself. I think this requires writing a shell extension to do, which I'm not familiar with. So if someone wants to contribute this would be a good one. :)

@JimmyBuzzard were you using gnome-shell like @nekohayo?

**Comment by JimmyBuzzard** [comment]
> were you using gnome-shell like @nekohayo?  

Nope. I used KDE. The issue is not present when using Debian or Ubuntu with KDE.

**Comment by gerhard-tinned** [comment]
Ubuntu and LinuxMint work fine.

**Comment by hbons** [comment]
Closing as we're going to ditch the status icon with the next GNOME version.
