### ISSUE TITLE
config file in repo

### ISSUE THREAD

**Issue by markusstoll** [hbons/SparkleShare#1724]
Hi,

what's with the notification server tcp://notifications.sparkleshare.org:443/

I hardly recall the last time this worked...

Markus

**Comment by hbons** [comment]
Just pushed my work in progress on a new service here: https://github.com/hbons/TrumpetCat
Next release will use this.

**Comment by markusstoll** [comment]
what is the problem with the old one - beside the fact that the service is not running (wich rather looked like a maintenance / deployment problem to me)?

I know that its possible to use your own notification server rather than the default one. I never did that because I would have to tell all my cousers to tweak the configuration for this.

Wouldn't it be a good idea to have some ".sparkleshare_config" file in the repo itself that has configuration information like that? By that all users would share one notification server automatically?

**Comment by hbons** [comment]
It was crashy and hard to maintain. Also the client code was pretty horrible.

I like the idea of a config file in the repo.

**Comment by aggsol** [comment]
I agree with the config file in the repo. Could you also write a short spec how the notification protocol is supposed t work so we can implement our own services?

**Comment by hbons** [comment]
It's based on ZeroMQ. It's pretty much the same protocol. Haven't had time to document yet but you can see it here: https://github.com/hbons/TrumpetCat/blob/master/TrumpetCat.Server/TrumpetCat.Server.cs

**Comment by hbons** [comment]
I noticed trying to write network code is preventing me having fun hacking on SparkleShare. Since it's been so long since the notification service I've decided to remove this code for 2.0 and rely on a cloud provider for this functionality for the release after. Suggestions welcome on #1775. :)
