### ISSUE TITLE
Migrating from 1.4 setup not supported? (OSX)

### ISSUE THREAD

**Issue by markusstoll** [hbons/SparkleShare#1728]
Is this intentional, that I have to reconfigure my client after upgrading to current nightly version?

I figured out that it would quite easy to support automatic migration of config and supporting old style folder without hostname as new folder level.
But before I invest too much time, I would like to know whether it was your intention to have your users restart with a new configuration set

**Comment by hbons** [comment]
Yes, master will be 2.0 and will break a lot of things. Even with automatic migration of the config things wouldn't work.
