### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by psyqologicaL** [hbons/SparkleShare#1732]
First of all: yes, it has been already asked but I couldn't find and answer in the comments so it's probably a  retarded problem which is pretty easy to solve but anyways...

I installed SparkleShare on my Kali Linux laptop and Windows PC today. I linked my Windows PC using "dazzle link" over a ssh connection so it's easier to copy & paste and stuff. The problem is that if I add a new hosted project on my own server (address: ssh://storage@192.168.178.21:22 and path: /home/storage/myfolders) it just simply doesn't work for some reason. I'm connected to the same network with both computers obviously. 

Here are the logs (ye I tried it a few times over and over again lol):

> 03:04:19 | Controller | Could not start ssh-agent:
> 03:04:19 | Environment | SparkleShare version: 1.4.0, Operating system: Win32NT (Microsoft Windows NT 6.2.9200.0)
> 03:04:19 | Config | Wrote to 'C:\Users\drago\AppData\Roaming\sparkleshare\config.xml'
> 03:04:19 | Config | Updated option notifications:True
> 03:04:20 | Auth | Created keypair 'C:\Users\drago\AppData\Roaming\sparkleshare\2016-10-10_03h04.key'
> 03:04:45 | Config | Wrote to 'C:\Users\drago\AppData\Roaming\sparkleshare\config.xml'
> 03:11:26 | Fetcher | C:\Users\drago\SparkleShare.tmp\myfolders | Fetching folder: ssh://storage@192.168.178.21:22/home/storage/myfolders
> 03:11:26 | Auth | Fetching host key for 192.168.178.21
> 03:11:26 | Cmd | ssh-keyscan -t rsa -p 22 192.168.178.21
> 03:11:27 | Auth | Skipping fingerprint check
> 03:11:27 | Auth | Accepted host key for 192.168.178.21
> 03:11:27 | Cmd | .tmp | git clone --progress --no-checkout --depth=1 "ssh://storage@192.168.178.21:22/home/storage/myfolders" "C:\Users\drago\SparkleShare.tmp\myfolders"
> 03:11:27 | Fetcher |       0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
> 03:11:27 | Fetcher | AllocationBase 0xB30000, BaseAddress 0xC30000, RegionSize 0xFD000, State 0x2000
> 03:11:27 | Fetcher | C:\Program Files (x86)\SparkleShare\msysgit\bin\ssh.exe: **\* Couldn't reserve space for cygwin's heap, Win32 error 0
> 03:11:27 | Fetcher | fatal: Could not read from remote repository.
> 03:11:27 | Fetcher | 
> 03:11:27 | Fetcher | Please make sure you have the correct access rights
> 03:11:27 | Fetcher | and the repository exists.
> 03:11:28 | Fetcher | Failed
> 03:12:21 | Fetcher | C:\Users\drago\SparkleShare.tmp\myfolders | Fetching folder: ssh://storage@192.168.178.21:22/home/storage/myfolders
> 03:12:21 | Auth | Fetching host key for 192.168.178.21
> 03:12:21 | Cmd | ssh-keyscan -t rsa -p 22 192.168.178.21
> 03:12:22 | Auth | Skipping fingerprint check
> 03:12:22 | Cmd | .tmp | git clone --progress --no-checkout --depth=1 "ssh://storage@192.168.178.21:22/home/storage/myfolders" "C:\Users\drago\SparkleShare.tmp\myfolders"
> 03:12:22 | Fetcher |       0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
> 03:12:22 | Fetcher | AllocationBase 0xC20000, BaseAddress 0xD20000, RegionSize 0xFD000, State 0x2000
> 03:12:22 | Fetcher | C:\Program Files (x86)\SparkleShare\msysgit\bin\ssh.exe: **\* Couldn't reserve space for cygwin's heap, Win32 error 0
> 03:12:22 | Fetcher | fatal: Could not read from remote repository.
> 03:12:22 | Fetcher | 
> 03:12:22 | Fetcher | Please make sure you have the correct access rights
> 03:12:22 | Fetcher | and the repository exists.
> 03:12:22 | Fetcher | Failed
> 03:12:37 | Fetcher | C:\Users\drago\SparkleShare.tmp\myfolders | Fetching folder: ssh://storage@192.168.178.21:22/home/storage/myfolders
> 03:12:37 | Auth | Fetching host key for 192.168.178.21
> 03:12:37 | Cmd | ssh-keyscan -t rsa -p 22 192.168.178.21
> 03:12:37 | Auth | Skipping fingerprint check
> 03:12:37 | Cmd | .tmp | git clone --progress --no-checkout --depth=1 "ssh://storage@192.168.178.21:22/home/storage/myfolders" "C:\Users\drago\SparkleShare.tmp\myfolders"
> 03:12:38 | Fetcher | Permission denied (publickey).
> 03:12:38 | Fetcher | fatal: Could not read from remote repository.
> 03:12:38 | Fetcher | 
> 03:12:38 | Fetcher | Please make sure you have the correct access rights
> 03:12:38 | Fetcher | and the repository exists.
> 03:12:38 | Fetcher | Failed
> 03:16:07 | Fetcher | C:\Users\drago\SparkleShare.tmp\myfolders | Fetching folder: ssh://storage@192.168.178.21:22/home/storage/myfolders
> 03:16:07 | Auth | Fetching host key for 192.168.178.21
> 03:16:07 | Cmd | ssh-keyscan -t rsa -p 22 192.168.178.21
> 03:16:07 | Cmd | ssh-keyscan -t dsa -p 22 192.168.178.21
> 03:16:07 | Cmd | ssh-keyscan -t ecdsa -p 22 192.168.178.21
> 03:16:07 | Auth | Could not fetch host key
> 03:16:07 | Fetcher | Failed
> 03:24:03 | Fetcher | C:\Users\drago\SparkleShare.tmp\myfolders | Fetching folder: ssh://storage@192.168.178.21:22/home/storage/myfolders
> 03:24:03 | Auth | Fetching host key for 192.168.178.21
> 03:24:03 | Cmd | ssh-keyscan -t rsa -p 22 192.168.178.21
> 03:24:04 | Cmd | ssh-keyscan -t dsa -p 22 192.168.178.21
> 03:24:04 | Cmd | ssh-keyscan -t ecdsa -p 22 192.168.178.21
> 03:24:04 | Auth | Could not fetch host key
> 03:24:04 | Fetcher | Failed
> 03:50:20 | Fetcher | C:\Users\drago\SparkleShare.tmp\myfolders | Fetching folder: ssh://storaage@192.168.178.21/home/storage/myfolders
> 03:50:20 | Auth | Fetching host key for 192.168.178.21
> 03:50:20 | Cmd | ssh-keyscan -t rsa -p 22 192.168.178.21
> 03:50:20 | Cmd | ssh-keyscan -t dsa -p 22 192.168.178.21
> 03:50:20 | Cmd | ssh-keyscan -t ecdsa -p 22 192.168.178.21
> 03:50:20 | Auth | Could not fetch host key
> 03:50:21 | Fetcher | Failed
> 03:52:16 | Fetcher | C:\Users\drago\SparkleShare.tmp\myfolders | Fetching folder: ssh://storage@192.168.178.21:22/home/storage/myfolders
> 03:52:16 | Auth | Fetching host key for 192.168.178.21
> 03:52:16 | Cmd | ssh-keyscan -t rsa -p 22 192.168.178.21
> 03:52:16 | Auth | Skipping fingerprint check
> 03:52:16 | Cmd | .tmp | git clone --progress --no-checkout --depth=1 "ssh://storage@192.168.178.21:22/home/storage/myfolders" "C:\Users\drago\SparkleShare.tmp\myfolders"
> 03:52:16 | Fetcher |       0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
> 03:52:16 | Fetcher | AllocationBase 0xB20000, BaseAddress 0xC30000, RegionSize 0xED000, State 0x2000
> 03:52:16 | Fetcher | C:\Program Files (x86)\SparkleShare\msysgit\bin\ssh.exe: **\* Couldn't reserve space for cygwin's heap, Win32 error 0
> 03:52:16 | Fetcher | fatal: Could not read from remote repository.
> 03:52:16 | Fetcher | 
> 03:52:16 | Fetcher | Please make sure you have the correct access rights
> 03:52:16 | Fetcher | and the repository exists.
> 03:52:17 | Fetcher | Failed
> 03:52:23 | Fetcher | C:\Users\drago\SparkleShare.tmp\myfolders | Fetching folder: ssh://storage@192.168.178.21:22/home/storage/myfolders
> 03:52:23 | Auth | Fetching host key for 192.168.178.21
> 03:52:23 | Cmd | ssh-keyscan -t rsa -p 22 192.168.178.21
> 03:52:24 | Auth | Skipping fingerprint check
> 03:52:24 | Cmd | .tmp | git clone --progress --no-checkout --depth=1 "ssh://storage@192.168.178.21:22/home/storage/myfolders" "C:\Users\drago\SparkleShare.tmp\myfolders"
> 03:52:24 | Fetcher |       0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
> 03:52:24 | Fetcher | AllocationBase 0xAA0000, BaseAddress 0xC30000, RegionSize 0x6B000, State 0x2000
> 03:52:24 | Fetcher | C:\Program Files (x86)\SparkleShare\msysgit\bin\ssh.exe: **\* Couldn't reserve space for cygwin's heap, Win32 error 0
> 03:52:24 | Fetcher | fatal: Could not read from remote repository.
> 03:52:24 | Fetcher | 
> 03:52:24 | Fetcher | Please make sure you have the correct access rights
> 03:52:24 | Fetcher | and the repository exists.
> 03:52:24 | Fetcher | Failed
> 03:53:26 | Fetcher | C:\Users\drago\SparkleShare.tmp\myfolders | Fetching folder: ssh://storage@192.168.178.21:22/home/storage/myfolders
> 03:53:26 | Auth | Fetching host key for 192.168.178.21
> 03:53:26 | Cmd | ssh-keyscan -t rsa -p 22 192.168.178.21
> 03:53:27 | Auth | Skipping fingerprint check
> 03:53:27 | Cmd | .tmp | git clone --progress --no-checkout --depth=1 "ssh://storage@192.168.178.21:22/home/storage/myfolders" "C:\Users\drago\SparkleShare.tmp\myfolders"
> 03:53:27 | Fetcher | Permission denied (publickey).
> 03:53:27 | Fetcher | fatal: Could not read from remote repository.
> 03:53:27 | Fetcher | 
> 03:53:27 | Fetcher | Please make sure you have the correct access rights
> 03:53:27 | Fetcher | and the repository exists.
> 03:53:27 | Fetcher | Failed
> 03:57:38 | Fetcher | C:\Users\drago\SparkleShare.tmp\myfolders | Fetching folder: ssh://storage@192.168.178.21:22/home/storage/myfolders
> 03:57:38 | Auth | Fetching host key for 192.168.178.21
> 03:57:38 | Cmd | ssh-keyscan -t rsa -p 22 192.168.178.21
> 03:57:38 | Auth | Skipping fingerprint check
> 03:57:38 | Cmd | .tmp | git clone --progress --no-checkout --depth=1 "ssh://storage@192.168.178.21:22/home/storage/myfolders" "C:\Users\drago\SparkleShare.tmp\myfolders"
> 03:57:39 | Fetcher | Permission denied (publickey).
> 03:57:39 | Fetcher | fatal: Could not read from remote repository.
> 03:57:39 | Fetcher | 
> 03:57:39 | Fetcher | Please make sure you have the correct access rights
> 03:57:39 | Fetcher | and the repository exists.
> 03:57:39 | Fetcher | Failed

As far as I understand it's probably something wrong with my access  rights since the repository exists 100% - the question is what I did wrong since I copied the Client ID directly from the installation wizard.

**Comment by payalord** [comment]
Looks like you are using your own local server for git repository. Have you installed ssh publickeys from your "Kali Linux laptop" and "Windows PC" to the server?

**Comment by hbons** [comment]
Yep, seems the public keys haven't been added on the server. Add the "Client ID" in the SparkleShare menu to ~/.ssh/authorized_keys on your server.
