### ISSUE TITLE
Conflicting files moved to the root of the repo

### ISSUE THREAD

**Issue by noidexe** [hbons/SparkleShare#1736]
Not sure if this is by design or a bug but I've noticed conflicting files are moved outside it's folder and to the root of the repo. 

Most syncing solutions like Dropbox, Drive, Syncthing, etc. would keep both files in the same directory and rename one stating the conflict, ideally stating username, machine name, and datetime.

What none of those solution do is flag the repo as conflicting so you can notice there had been conflicts and provide you a list of the conflicting files. 

This behavior would make SparkleShare the best tool for the non-programmers in my team, above Dropbox or any other since it won't require git-saavy users to intervene in case of conflicts.

**Comment by hbons** [comment]
That's definitely a bug. Conflicted copies should stay in their folders.

**Comment by hbons** [comment]
Which version and OS?
