### ISSUE TITLE
error while building/installing

### ISSUE THREAD

**Issue by sirajkrm** [hbons/SparkleShare#1737]
hi
i saw this software
it looks quit cool & great as an alternative to Dropbox
but..
i'm facing this error while installing it

Making all in build
Making all in m4
Making all in SparkleLib
  MCS   ../bin/SparkleLib.dll
Note: dmcs is deprecated, please use mcs instead!
Making all in SparkleLib/Git
  MCS   ../../bin/SparkleLib.Git.dll
Note: dmcs is deprecated, please use mcs instead!
Making all in SparkleShare
Making all in Linux
Making all in Pixmaps
Making all in icons
Making all in ubuntu-mono-dark
Making all in ubuntu-mono-light
Making all in gnome
  MCS   ../../bin/SparkleShare.exe
Note: dmcs is deprecated, please use mcs instead!
./SparkleUI.cs(64,52): error CS1502: The best overloaded method match for `GLib.Application.Run(int, string)' has some invalid arguments
/usr/lib64/pkgconfig/../../lib/mono/gtk-sharp-3.0/gio-sharp.dll (Location of the symbol related to previous error)
./SparkleUI.cs(64,57): error CS1503: Argument `#1' cannot convert `null' expression to type `int'
Compilation failed: 2 error(s), 0 warnings
make[3]: *** [../../bin/SparkleShare.exe] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

i'm running CentOS 7 on VMware
any help is very appreciated!
thank's.

**Comment by hbons** [comment]
looks like an old version? can you try from master?

**Comment by sirajkrm** [comment]
hi
no not really
that version is from bitbucket
and the version is 1.5 which is the latest as it seems

**Comment by hbons** [comment]
Fixed in master now.
