### ISSUE TITLE
index file corrupt but no GUI warnings

### ISSUE THREAD

**Issue by ianchanning** [hbons/SparkleShare#1741]
I'm running SparkleShare 1.5 on Windows 10 64-bit.

I hadn't noticed that my Sparkleshare hadn't been syncing properly for the last three months as I'd only been using one machine.

The problem was with the git index file being corrupt. It's relatively simply fixed by this SO question: http://stackoverflow.com/questions/1115854/how-to-resolve-error-bad-index-fatal-index-file-corrupt-when-using-git

I guess the more worrying issue though is that SparkleShare wasn't syncing and I had no idea - no warning icon was displayed even though there were errors in the logs.

```
10:41:16 | Cmd | sparkleshare | git merge-base 3342cdba421f9295bdf2e52e4009df5ea046be7d master
10:41:16 | Git | sparkleshare | Remote changes found, local: 05b04a927149f84931e020a1ce8e831a23d57c15, remote: 3342cdba421f9295bdf2e52e4009df5ea046be7d
10:41:16 | SyncDown | sparkleshare | Initiated
10:41:16 | Cmd | sparkleshare | git rev-parse HEAD
10:41:16 | Cmd | sparkleshare | git fetch --progress "ssh://git@example.com/me/sparkleshare-crypto" master
10:41:16 | Git | sparkleshare | error: bad signature
10:41:17 | Git | sparkleshare | fatal: index file corrupt
10:41:17 | Git | dev | No remote changes, local+remote: 071612920f93f5769a51c3a9269ae2cc511ba01e
10:41:17 | Cmd | dev | git status --porcelain
10:41:18 | SyncDown | sparkleshare | Error
```

**Comment by hbons** [comment]
Tracking this in #1603.
