### ISSUE TITLE
SparkleShare does not seem to auto-pull?

### ISSUE THREAD

**Issue by karai17** [hbons/SparkleShare#1745]
I am testing out SparkleShare and while it instantly pushes file changes to GitHub, it does not seem to pull until I restart the application (1.2.0 on Fedora 25). Same issue for my friend (1.5.0 on Ubuntu 16.04). It would be very handy for SparkleShare to git pull every couple seconds to ensure that we are always working on the same files.

**Comment by hbons** [comment]
Notification service is currently down. Working on fixing this soon.

**Comment by hbons** [comment]
Plan is #1775.
