### ISSUE TITLE
Status icon missing after upgrade to Linux Mint 18.1 (Ubuntu  Xenia)

### ISSUE THREAD

**Issue by inolil** [hbons/SparkleShare#1751]
Hi,
The main icon of Sparkleshare is missing in the status bar (notification area).

Others icon (synching...) are OK.

Sparkleshare version 1.5.0-1

Thank you for your help

**Comment by gerhard-tinned** [comment]
+1
I noticed the same!

**Comment by hbons** [comment]
Can you try the 2.0 flatpak and see if this still happens?

**Comment by hbons** [comment]
Is this the Ubuntu package? That one is compiled with appindicator support. I don't know if Mint supports that.

**Comment by hbons** [comment]
Probably a duplicate of #1790. Try the newer flatpak version if you can.
