### ISSUE TITLE
Gitolite ssh:// route does not use aliases defined in /etc/hosts or ~/.ssh/config

### ISSUE THREAD

**Issue by robbintt** [hbons/SparkleShare#1760]
I linked the gitolite mac client to my remote server today with no FQDN and was required to use the IP in the ssh:// declaration rather than a locally set alias from one of the two popular locations, `/etc/hosts` or `~/.ssh/config`.

Has anyone gotten one of these aliases to work? Thanks!

**Comment by hbons** [comment]
SparkleShare uses its own ssh configuration as much as possible to prevent conflicts with other apps, so this is intentional. However, easier ways to add your projects are coming.
