### ISSUE TITLE
SparkleShare crashes on macos if you have two projects with the same name

### ISSUE THREAD

**Issue by robbintt** [hbons/SparkleShare#1761]
I added a Gitolite repo with the same name as a github one. I then attempted to exit and had to kill the process. In general, things didn't go very well. It seemed to add a file that belonged in one to the other.  It might be nice to stop people from doing that in the first place if it isn't intended behavior.

**Comment by hbons** [comment]
2.0 now groups projects by host, so this shouldn't happen anymore.
