### ISSUE TITLE
After upgrade to 1.5.4, it's not picking up config file

### ISSUE THREAD

**Issue by asoliverez** [hbons/SparkleShare#1766]
In Manjaro, I upgraded from 1.5.2 to 1.5.4.
It starts as if it had an empty config, no repos configured at all, it just sits there. When I try to add the repos again, it fails with:

09:24:55 Auth | Fetching host key for git.internal.xxxxxxxxx.co.uk
09:24:55 Cmd |  | ssh-keyscan -t rsa -p 22 git.internal.xxxxxx.co.uk
09:24:57 Auth | Skipping fingerprint check
09:24:57 Auth | Accepted host key for git.internal.xxxxx.co.uk
32:6f:ac:a0:98:bc:d9:8e:f9:f6:80:73:ea:9f:01:f9:b9:0d:2f:a7:f2:f3:c5:b0:83:3b:85:07:35:62:97:f9
09:24:57 Cmd | tmp | git ls-remote --heads "ssh://asoliver@git.internal.xxxxxxxxx.co.uk/git/documents/projects.git"
09:25:00 Fetcher | Failed

**Comment by hbons** [comment]
I can't look into distros other than Fedora and Ubuntu. Can you try the latest flatpak version?

**Comment by asoliverez** [comment]
I forgot to reply on this. I tried the Flatpak version and it fails the same way.

**Comment by hbons** [comment]
I forgot to mention v2 will require re-adding of all the repos because of some restructure work to support some features. Sorry about that.

**Comment by asoliverez** [comment]
With the Flatpak version, it fails when I try to add new repos. Do the repos themselves need any conversion to work with the new version?

**Comment by hbons** [comment]
What's the error you get?
