### ISSUE TITLE
Automate cert renewal for sparkleshare.org

### ISSUE THREAD

**Issue by jcbhltz22** [hbons/SparkleShare#1767]
https://www.sparkleshare.org LE certificate has expired.

**Comment by petmos** [comment]
Unfortunately the site https://www.sparkleshare.org is still not save caused by expired certificate.  I'm afraid this breaks confidence.

**Comment by rorymbyrne** [comment]
Yep, still a problem. It's because you have to renew Letsencrypt Certs every three months 

<img width="1179" alt="screen shot 2017-08-11 at 00 38 36" src="https://user-images.githubusercontent.com/18581795/29196564-0fcfa988-7e2d-11e7-9546-6a64373b33bc.png">

**Comment by jcbhltz22** [comment]
There are a number of ways to automate this. I believe certbot has this ability out of box.

Sent from my iPhone

On Aug 10, 2017, at 8:36 PM, Rory Byrne <notifications@github.com<mailto:notifications@github.com>> wrote:


Yep, still a problem. It's because you have to renew Letsencrypt Certs every three months

[screen shot 2017-08-11 at 00 38 36]<https://user-images.githubusercontent.com/18581795/29196564-0fcfa988-7e2d-11e7-9546-6a64373b33bc.png>

-

**Comment by hbons** [comment]
I'm looking into it but it's not so easy to automate. :(

**Comment by zeigerpuppy** [comment]
Which OS/Webserver are you running?  
I can help if it's on Linux and running either apache or nginx (happy to share cron scripts that automate renewal).

**Comment by jcbhltz22** [comment]
Also,If you are using HAProxy, I am able to help.


On Aug 16, 2017, at 1:17 PM, zeigerpuppy <notifications@github.com<mailto:notifications@github.com>> wrote:


Which OS/Webserver are you running?
I can help if it's on Linux and running either apache or nginx (happy to share cron scripts that automate renewal).

**Comment by gerhard-tinned** [comment]
@hbons: I have successfully installed let's encrypt automatic renewal on multiple hosts. If you want, I can help you. I found different solutions even for quite complex setups. Let me know if you are interested.

**Comment by gerhard-tinned** [comment]
Website certificate expired (2017-12-25) again ... Can I help in any way to automate this for you? 

There are many different Let's Encrypt clients out there to automate this process. Even hosting provider support this procedure of auto-renewal.

**Comment by hbons** [comment]
I've removed the cert for now. I'm having issues automating this.

@gerhard-tinned your help would be appreciated! Right now I'm hosting on GitLab because it's easy to push new updates and it supports certs with custom domains. The downside is that it has to be manually updated every 90 days through the settings panel and it's buggy sometimes... Do you know a good place for hosting?

**Comment by hbons** [comment]
Now uses GitHub's automatic SSL cert.
