### ISSUE TITLE
sparkleshare recommended for usage?

### ISSUE THREAD

**Issue by petmos** [hbons/SparkleShare#1769]
I really love Sparkleshare but now I'm not sure if I can recommend sparkleshare for usage.

It looks like the development and maintenance is stopped.
The referenced Twitter account was updated last at 30. Juni 2016 and the webseite seems to be outdated too. E.g. the certificate is expired but no reaction (https://github.com/hbons/SparkleShare/issues/1767).
The last version of Sparkleshare is 1.5 from Dec 22, 2015.

I hope Sparkleshare is still alive and development goes on. But it is so calm on all channels as this project would be dead.

Hopefully I'm wrong because as I said at the beginning I love Sparkleshare.

**Comment by aggsol** [comment]
That is worrying indeed. @hbons just changed his email to hi@planetpeanut.uk Maybe you can contact him there.

**Comment by hbons** [comment]
It's not dead, development has just slowed as it has achived most of its goals. :)
But yes, we need to fix a couple of things and make automatic releases.
