### ISSUE TITLE
Sparkleshare crashes on Windows Client when adding Host Project

### ISSUE THREAD

**Issue by Kampii** [hbons/SparkleShare#1771]
I reinstalled the app multiple times without any luck. How can I fix it? I am using windows 10.

**Comment by BarryThePenguin** [comment]
There's been a few issues like this in the past, eg https://github.com/hbons/SparkleShare/issues/1581

Try deleting `~/SparkleShare/.tmp/` and trying again

**Comment by Kampii** [comment]
I am not able to find that under "C:\Program Files (x86)\SparkleShare\". What is the full path?

We have set the host on the Linux server and now I am trying to sync a project with my Laptop.

**Comment by BarryThePenguin** [comment]
It's in your user directory, where SparkleShare syncs to

**Comment by Kampii** [comment]
Awesome, now I got passed the crash!

Is there any way to figure out why the "Adding Project" message displays all night and the project still does not get added? This worked fine before I reinstalled my PC but now simply does not pull the project.

**Comment by BarryThePenguin** [comment]
Not sure sorry. You may need to look at the debug logs
