### ISSUE TITLE
Shows empty 'Adding Project..' for a long time but actually never adds it

### ISSUE THREAD

**Issue by Kampii** [hbons/SparkleShare#1772]
I have been struggling with this for the past 5hrs and I still can't figure out what is wrong. Below is the log which does not report anything being wrong with the settings or ports etc. It just takes forever to add a brand new project, and never actually adds it. How do I figure out what is wrong here?

22:29:12 | Fetcher | C:\Users\KR\SparkleShare\.tmp\test1 | Fetching folder: ssh://storage@94.101.227.79:22/home/storage/test1
22:29:12 | Auth | Fetching host key for 94.101.123.45
22:29:12 | Cmd | ssh-keyscan -t rsa -p 22 94.101.123.45
22:29:14 | Auth | Skipping fingerprint check
22:29:14 | Cmd | .tmp | git clone --progress --no-checkout --depth=1 "ssh://storage@94.101.123.45:22/home/storage/test1" "C:\Users\KR\SparkleShare\.tmp\test1"

I am using Windows 10. The host is set up on Linux. Everything worked before I reinstalled my Windows 10.

**Comment by Kampii** [comment]
Here is how I solved it on Win 10:
Delete the C:\Users\..\.ssh\known hosts > connect using Putty (and not OpenSSH which was the source of the problem because it generated wrong key) > add the key permanently > Done > now SparkleShare will add the hosted project and will not get stuck at the 'coffee' message.

**Comment by hbons** [comment]
I think this is due to conflicting SSH configurations. Next SparkleShare version will fix this.
