### ISSUE TITLE
[Linux] Use native notifications by default

### ISSUE THREAD

**Issue by csoriano1618** [hbons/SparkleShare#1773]
Hello,

Currently Sparkleshare doesn't use native notifications. For Linux desktops using native notifications would be appreciated. The following are the benefits when using native notifications:
1. User will have a equal experience across apps
2. Notifications are implemented in the way the desktop the user is using wants them to be. Including theme, position, etc.
3. User will be able to disable and control notifications from the system settings, together with all the other apps.
4. Notifications can have actions, useful for integration with the system and quick access from the main UI.
5. It will help with issue #1774 and the status icon story.

Documentation for native notifications can be found [here](https://developer.gnome.org/hig/stable/notifications.html.en).
Feel free to ask any question you may have about how to implement this or the reasoning behind.

Thanks

**Comment by hbons** [comment]
What's the difference between "native notifications" and the currently used notify-sharp?

**Comment by csoriano1618** [comment]
I didn't manage to make Sparkleshare to fire a notification, so I guessed it's broken in my system, and I couldn't double check.

However, I was looking precisely at that project before filing the bug and seems it's inspired in libnotify but doesn't use it and they claim is has some differences. So I'm not sure if it works in the same way as glib notifications do.

Do I have a way to make Sparkleshare fire a notification so I can check if they work as expected?

**Comment by hbons** [comment]
You'll need 2 computers or the same folder synced twice. Change a file in one folder and it should give you a notification once it's synced to the other.

**Comment by hbons** [comment]
I'm going to assume this still works. Will reopen when I see it broken on GNOME 3.
