### ISSUE TITLE
2.0 build for Windows?

### ISSUE THREAD

**Issue by olegstepura** [hbons/SparkleShare#1781]
Hi!

First, thanks for great software! I found out that version 2.0 is already fixed.
Any chance to get binary distribution of 2.0 for Windows?

Thanks!

**Comment by olegstepura** [comment]
Hi!

FYI: I tried building current master myself, but there is a lot of issues with build instructions/scripts.

* `build.cmd` does not build from `[sources]\SparkleShare\Windows` but it builds binary if being copied to  `[sources]\` (where `.sln` file is located)
* On the other side to build installer, `build.cmd` must be located in `[sources]\SparkleShare\Windows`
* `build.cmd` does not build installer after WIX installed:
  * it's complaining on missing `[sources]\bin\plugins` folder
  * If I just create `[sources]\bin\plugins` empty folder, installer is not created due to missing `plugins.wxs`. Since `plugins` folder is empty `plugins.wxs` is not created.
  * Ok, I've put an empty file to `[sources]\bin\plugins`, but now installer is not created due to the fact that build created `SparkleShare.Windows.exe` file, `SparleShare.exe` was missing.
  * Ok, I renamed the file, now installer is not created due to missing `SparkleShareInviteOpener.exe`. I have no idea on how to build it.
  * Ok, I copied `SparkleShareInviteOpener.exe` from 1.5 distribution. Installer is created.
  * After running such installer `SparkleShare.exe` does not launch since installer does not copy folders `Images`, `Presets`, `ru`, and `mscorlib.dll` file (not sure all are required, but after copying all it launched)

Also I have to notice that instead of copying `C:\Program Files\Git` to `[sources]\bin\msysgit` it's ok to make a symlink. From inside of `[sources]\bin` folder run:
```cmd
mklink /D msysgit "c:\Program Files\Git"
```

Also since I already have `msysgit` installed, I prefer to remove `msysgit` folder from installed SparkleShare dir and create a symlink there as well.

![2017-10-04 22_40_06-about sparkleshare](https://user-images.githubusercontent.com/534510/31198588-18b1922a-a955-11e7-810b-c0eab81b353c.png)

**Comment by BarryThePenguin** [comment]
I've been working on https://github.com/BarryThePenguin/sparkleshare/tree/new-squirrel to get a version of SparkleShare for Windows working without WIX.

My plan was to get nightly Windows builds setup, with automatic updates with Squirrel for Windows. Similar to #1572

**Comment by olegstepura** [comment]
@BarryThePenguin that is cool, but releasing current 2.0 version installer even made with WIX would be welcomed by community

**Comment by hbons** [comment]
Tracked in #1743.
