### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by baimafeima** [hbons/SparkleShare#1783]
Could you make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by hbons** [comment]
It's a good idea. I've added this as a to do item in https://github.com/hbons/SparkleShare/issues/1749
