### ISSUE TITLE
Improve the .appdata file

### ISSUE THREAD

**Issue by baimafeima** [hbons/SparkleShare#1784]
For reference: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

**Comment by hbons** [comment]
There is an appdata file: https://github.com/hbons/SparkleShare/blob/master/SparkleShare/Linux/org.sparkleshare.SparkleShare.appdata.xml
Maybe it's not added to the build or in the right location? What distro are you using?

**Comment by hbons** [comment]
This is installed in the right location now with #1808.
