### ISSUE TITLE
Sparkleshare 1.5 client on mac unable to sync 0% on existing repository. Hang.

### ISSUE THREAD

**Issue by offset25** [hbons/SparkleShare#1787]
Sparkleshare 1.5 client on mac unable to sync 0% on existing repository. Git repository is on my linux server. Sparkleshare client just stays stuck after I added/modified files on my client. This happened before. Previous Fix was to restart and re-open sparkleshare and that was able to eventually sync. Now it won't sync even after restart. Using MacOS High Sierra. Not able to pause sparkelshare and not able to quit or force quit sparkleshare. Wondering if other people have this issue on MacOS? I saw previous reports back in 2012 of 0% sync after making a high number of changes. Let me know if this is similar issue or if there is a fix. Would like to use this solution to sync my project files, but concerned of sync reliability  and/or losing files.

**Comment by hbons** [comment]
Can you try version 2? You'll have to re-add your repositories, but it should be much better.
