### ISSUE TITLE
not able to sync on 3.4GB share in latest mac build with latest macOS but able to sync on older macOS with 1.5 build

### ISSUE THREAD

**Issue by offset25** [hbons/SparkleShare#1789]
Sparkleshare Mac v 1.5 and 2.0 is having issues on latest macOS 10.13.1 syncing on a large share.

But on older macOS v10.12 its syncing fine with same share.

The share is on my linux server setup as instructed on home page of sparkleshare.
Other test shares on same system work fine.

in Sparkleshare 2.0 it goes through both sending and receiving, but eventually says not everything synced.
or it will say cannot reach host, but host is there and reachable in my other mac

files consist of personal files and web project files. would like to use as my storage system hopefully.

**Comment by hbons** [comment]
Can you look at the logs folder and see if there’s anything interesting in there?

**Comment by offset25** [comment]
getting a protocol error:

13:20:26 Cmd | dino personal | git status --porcelain
13:20:27 Cmd | dino personal | git push --all --progress origin
13:20:27 Git | fatal: protocol error: expected old/new/ref, got 'shallow adade304811b0514ade8de42eb04ab83b8a4c636'
13:20:27 Git | fatal: The remote end hung up unexpectedly
13:20:27 Git | Counting objects: 4, done.
13:20:27 Git | Delta compression using up to 4 threads.
13:20:27 Git | fatal: The remote end hung up unexpectedly
13:20:34 Git | dino personal | Checking for remote changes...
13:20:34 Cmd | dino personal | git rev-parse HEAD
13:20:34 Cmd | dino personal | git ls-remote --heads --exit-code origin master
13:20:35 Cmd | dino personal | git merge-base f77916fce2207b72ba49ad947199bac0ffa06c53 master
13:20:35 Git | dino personal | Remote f77916fce2207b72ba49ad947199bac0ffa06c53 is already in our history
13:20:38 Cmd | dino personal | git status --porcelain
13:22:51 Git | test project | Checking for remote changes...
13:22:51 Cmd | test project | git rev-parse HEAD
13:22:51 Cmd | test project | git ls-remote --heads --exit-code origin master
13:22:52 Git | test project | No remote changes, local+remote: 2e01eb0ac8254a23b6096588d2d2637f75da7b9f
13:25:36 SyncUp | dino personal | Initiated
13:25:36 Cmd | dino personal | git add --all
13:25:38 Cmd | dino personal | git status --porcelain
13:25:39 Cmd | dino personal | git push --all --progress origin
13:25:39 Git | fatal: protocol error: expected old/new/ref, got 'shallow adade304811b0514ade8de42eb04ab83b8a4c636'
13:25:39 Git | fatal: The remote end hung up unexpectedly
13:25:40 Git | Counting objects: 4, done.
13:25:40 Git | Delta compression using up to 4 threads.
13:25:40 Git | fatal: The remote end hung up unexpectedly
13:25:46 SyncUp | dino personal | Error
13:25:46 SyncDown | dino personal | Initiated
13:25:46 Cmd | dino personal | git rev-parse HEAD
13:25:46 Cmd | dino personal | git fetch --progress origin master
13:25:47 Git | From ssh://199.241.142.237/home/storage/sparkle_storage/dino_personal
13:25:47 Git |  * branch              master     -> FETCH_HEAD
13:25:47 Cmd | dino personal | git status --porcelain
13:25:48 Cmd | dino personal | git config core.ignorecase true
13:25:48 Cmd | dino personal | git merge FETCH_HEAD
13:25:48 Cmd | dino personal | git config core.ignorecase false
13:25:56 Cmd | dino personal | git --no-pager log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges
13:26:02 Cmd | dino personal | git rev-parse HEAD
13:26:02 SyncDown | dino personal | Done
13:26:02 Cmd | dino personal | git add --all
13:26:03 Cmd | dino personal | git status --porcelain
13:26:04 Cmd | dino personal | git push --all --progress origin
13:26:04 Git | fatal: protocol error: expected old/new/ref, got 'shallow adade304811b0514ade8de42eb04ab83b8a4c636'
13:26:04 Git | fatal: The remote end hung up unexpectedly
13:26:04 Git | Counting objects: 4, done.
13:26:04 Git | Delta compression using up to 4 threads.
13:26:04 Git | fatal: The remote end hung up unexpectedly
13:26:11 Git | dino personal | Checking for remote changes...
13:26:11 Cmd | dino personal | git rev-parse HEAD
13:26:11 Cmd | dino personal | git ls-remote --heads --exit-code origin master
13:26:11 Cmd | dino personal | git merge-base f77916fce2207b72ba49ad947199bac0ffa06c53 master
13:26:11 Git | dino personal | Remote f77916fce2207b72ba49ad947199bac0ffa06c53 is already in our history
13:26:14 Cmd | dino personal | git status --porcelain
13:26:18 Cmd | dino personal | git status --porcelain
13:27:51 Git | test project | Checking for remote changes...
13:27:51 Cmd | test project | git rev-parse HEAD
13:27:51 Cmd | test project | git ls-remote --heads --exit-code origin master
13:27:52 Git | test project | No remote changes, local+remote: 2e01eb0ac8254a23b6096588d2d2637f75da7b9f
13:31:11 SyncUp | dino personal | Initiated
13:31:11 Cmd | dino personal | git add --all
13:31:13 Cmd | dino personal | git status --porcelain
13:31:14 Cmd | dino personal | git push --all --progress origin
13:31:14 Git | fatal: protocol error: expected old/new/ref, got 'shallow adade304811b0514ade8de42eb04ab83b8a4c636'
13:31:14 Git | fatal: The remote end hung up unexpectedly
13:31:16 Git | Counting objects: 1   
13:31:16 Git | Counting objects: 4, done.
13:31:16 Git | Delta compression using up to 4 threads.
13:31:16 Git | fatal: The remote end hung up unexpectedly
13:31:25 SyncUp | dino personal | Error
13:31:25 SyncDown | dino personal | Initiated
13:31:25 Cmd | dino personal | git rev-parse HEAD
13:31:25 Cmd | dino personal | git fetch --progress origin master
13:31:26 Git | From ssh://199.241.142.237/home/storage/sparkle_storage/dino_personal
13:31:26 Git |  * branch              master     -> FETCH_HEAD
13:31:26 Cmd | dino personal | git status --porcelain
13:31:27 Cmd | dino personal | git config core.ignorecase true
13:31:27 Cmd | dino personal | git merge FETCH_HEAD
13:31:27 Cmd | dino personal | git config core.ignorecase false
13:31:35 Cmd | dino personal | git --no-pager log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges
13:31:40 Cmd | dino personal | git rev-parse HEAD
13:31:40 SyncDown | dino personal | Done
13:31:40 Cmd | dino personal | git add --all
13:31:40 Cmd | dino personal | git status --porcelain
13:31:41 Cmd | dino personal | git push --all --progress origin
13:31:42 Git | fatal: protocol error: expected old/new/ref, got 'shallow adade304811b0514ade8de42eb04ab83b8a4c636'
13:31:42 Git | fatal: The remote end hung up unexpectedly
13:31:42 Git | Counting objects: 4, done.
13:31:42 Git | Delta compression using up to 4 threads.
13:31:42 Git | fatal: The remote end hung up unexpectedly
13:31:48 Git | dino personal | Checking for remote changes...
13:31:48 Cmd | dino personal | git rev-parse HEAD
13:31:48 Cmd | dino personal | git ls-remote --heads --exit-code origin master
13:31:49 Cmd | dino personal | git merge-base f77916fce2207b72ba49ad947199bac0ffa06c53 master
13:31:49 Git | dino personal | Remote f77916fce2207b72ba49ad947199bac0ffa06c53 is already in our history
13:31:51 Cmd | dino personal | git status --porcelain
13:31:56 Cmd | dino personal | git status --porcelain
13:32:00 Cmd | dino personal | git status --porcelain
13:32:51 Git | test project | Checking for remote changes...
13:32:51 Cmd | test project | git rev-parse HEAD
13:32:51 Cmd | test project | git ls-remote --heads --exit-code origin master
13:32:52 Git | test project | No remote changes, local+remote: 2e01eb0ac8254a23b6096588d2d2637f75da7b9f
13:36:51 SyncUp | dino personal | Initiated
13:36:51 Cmd | dino personal | git add --all
13:36:54 Cmd | dino personal | git status --porcelain
13:36:55 Cmd | dino personal | git push --all --progress origin
13:36:55 Git | fatal: protocol error: expected old/new/ref, got 'shallow adade304811b0514ade8de42eb04ab83b8a4c636'
13:36:55 Git | fatal: The remote end hung up unexpectedly
13:36:56 Git | Counting objects: 4, done.
13:36:56 Git | Delta compression using up to 4 threads.
13:36:56 Git | fatal: The remote end hung up unexpectedly
13:37:03 SyncUp | dino personal | Error
13:37:03 SyncDown | dino personal | Initiated
13:37:03 Cmd | dino personal | git rev-parse HEAD
13:37:03 Cmd | dino personal | git fetch --progress origin master
13:37:03 Git | From ssh://199.241.142.237/home/storage/sparkle_storage/dino_personal
13:37:03 Git |  * branch              master     -> FETCH_HEAD
13:37:03 Cmd | dino personal | git status --porcelain
13:37:04 Cmd | dino personal | git config core.ignorecase true
13:37:04 Cmd | dino personal | git merge FETCH_HEAD
13:37:04 Cmd | dino personal | git config core.ignorecase false
13:37:10 Cmd | dino personal | git --no-pager log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges
13:37:14 Cmd | dino personal | git rev-parse HEAD
13:37:14 SyncDown | dino personal | Done
13:37:14 Cmd | dino personal | git add --all
13:37:15 Cmd | dino personal | git status --porcelain
13:37:16 Cmd | dino personal | git push --all --progress origin
13:37:17 Git | fatal: protocol error: expected old/new/ref, got 'shallow adade304811b0514ade8de42eb04ab83b8a4c636'
13:37:17 Git | fatal: The remote end hung up unexpectedly
13:37:17 Git | Counting objects: 4, done.
13:37:17 Git | Delta compression using up to 4 threads.
13:37:17 Git | fatal: The remote end hung up unexpectedly

**Comment by hbons** [comment]
I remember this problem from a few years back. It’s due to some incompatible Git versions being use between the server and client. The Git project broke some compatibility at some point with shallow clones that SparkleShare uses.

I recommend using the v2 SparkleShare client everywhere, and creating the hosted repository from scratch with a recent Git version too. I know it’s a pain to do, but that’s th only way to fix it.

Feel free to reopen if that doesn’t work.
