### ISSUE TITLE
presets config still created in ~/.config/sparkleshare/presets

### ISSUE THREAD

**Issue by glunardi** [hbons/SparkleShare#1792]
While the rest of the configuration seems to have moved to the new ".config/org.sparkleshare.SparkleShare" directory, it seems the presets are still created in the old "~/.config/sparkleshare/presets"

**Comment by glunardi** [comment]
Preset.cs still uses 
        public static string LocalPresetsPath = IO.Path.Combine (
            Environment.GetFolderPath (Environment.SpecialFolder.ApplicationData), "sparkleshare", "presets");

to store the presets into. On F27, that results in a "~/.config/sparkleshare/presets" directory being created while everything else now goes to ".config/org.sparkleshare.SparkleShare".

**Comment by hbons** [comment]
Thanks! This should probably be fixed globally somewhere, but I don't have time to do that now...
