### ISSUE TITLE
https access?

### ISSUE THREAD

**Issue by markusstoll** [hbons/SparkleShare#1794]
on trying to update to the new version I am puzzled…

Is this true, that my use case (accessing the GIT repo via https rather than ssh) has been kicked out silently? Why not announcing anything, no message on update?

I guess there is no other synching client with GIT repos in the back end? :-(

**Comment by hbons** [comment]
I couldn't support the HTTPS stuff anymore... It was always a couple of hacks, not very usable, and not secure at all. It was getting in the way of other features. I did mention it in the release notes for 2.0: https://github.com/hbons/SparkleShare/blob/master/RELEASE_NOTES.txt#L28

**Comment by ikus060** [comment]
Did you drop HTTP support in the same release ?
