### ISSUE TITLE
High CPU and unresponsive when quitting on OS X 10.12.1

### ISSUE THREAD

**Issue by jarmitage** [hbons/SparkleShare#1796]
- SparkleShare v.2.0.1
- Mac OS X 10.12.1

### What happened:
- Quit using the menu bar
- <img width="593" alt="2018-01-11 at 14 17 56" src="https://user-images.githubusercontent.com/2885827/34829968-563c9c84-f6da-11e7-9d37-1b7d90ed2230.png">
- [log_2018-01-11.1.txt](https://github.com/hbons/SparkleShare/files/1622938/log_2018-01-11.1.txt)
- Happens <100% of the time

### What I expected to happen:
- Quitting

### You can reproduce the issue like this:
1. Try quitting

It seems activity during unresponsiveness and force quitting is not recorded in the logs.

**Comment by hbons** [comment]
Fixed in #1821.
