### ISSUE TITLE
About dialog on F27 (not flatpak) minor cosmetic issues

### ISSUE THREAD

**Issue by glunardi** [hbons/SparkleShare#1804]
The about dialog on F27 (not flatpak) has a few minor cosmetic issues when running locally as mentioned in https://github.com/hbons/SparkleShare/pull/1791#issuecomment-355465292 

Some of these changes help:
1b25f0c83f8c8f47b21b7e4596064b0238473c20

**Comment by hbons** [comment]
Oh, I thought I had merged this. Will add.

**Comment by glunardi** [comment]
Figured this was best handled with a new issue :-) 

Should have created one to begin with.

**Comment by hbons** [comment]
🍒👌 'ed to master.
