### ISSUE TITLE
Doesn't ask for decryption password

### ISSUE THREAD

**Issue by michaelbaisch** [hbons/SparkleShare#1831]
My `project-crypto` worked perfectly with version 1.x. Now I updated to 2.0.1 and I first had to add all my projects again and second I wasn't asked for a password for my `project-crypto`. Now I have the encrypted files which is not very helpful.

Did I miss an update step or something?

Using macOS HS.

**Comment by hbons** [comment]
Hi, 2.0 has a new way of dealing with encrypted project. Unfortunately, this means the remote project needs to be recreated. The project no longer needs to be named "-crypto", SparkleShare 2.x will ask if you want the project to be encrypted when you clone a new empty repository.

Although I mentioned in the release SparkleShare 2.x breaks compatibility, I forgot to mention encrypted repositories will need to be recreated.

Let me know if that works.
