### ISSUE TITLE
Not a SparkleShare bug:  memory leak in WebKitWebProcess in F27

### ISSUE THREAD

**Issue by glunardi** [hbons/SparkleShare#1832]
Just another point for consideration regarding the use of webkit.

Discovered in the past few days that there is a pretty bad memory leak in webkit2gtk.
`/usr/libexec/webkit2gtk-4.0/WebKitWebProcess`

It was not visible before possibly because it would typically crash before the memory usage would become an issue (or it was the issue all along).

At any rate with an 72h+ uptime for my F27 SparkleShare process, the webkit2gtk process is using over 2GB of resident memory.

Not sure if that memory usage is a problem on the other platforms supported.

**Comment by glunardi** [comment]
Could that be why you were destroying it before?

**Comment by hbons** [comment]
Oh I haven't seen this. This is indeed another good reason to move away from the webview. Thanks for reporting!

**Comment by hbons** [comment]
linking this to #1774.
