### ISSUE TITLE
System.DllNotFoundException: libwebkit2sharpglue-2.10.9.so

### ISSUE THREAD

**Issue by IvanMalison** [hbons/SparkleShare#1835]
### What happened:

https://gist.github.com/IvanMalison/46a504dfad803a3bb3821b51afbe58d9

but I do have libwebkit2sharpglue-2.10.9.so on my machine:

```
~/Projects/SparkleShare fix/appindicator*
$ sudo find /usr | grep libwebkit2sharpglue-2.10.9.so
/usr/lib/libwebkit2sharpglue-2.10.9.so
```

I'm running on arch linux, and all of the shared objects that sparkleshare depends on are in

/usr/lib rather than /usr/local/lib which is where the default installation paths are (could this be the cause of this issue).

I'm not familiar with how shared objects are linked in C#. Is there a way I can effectively set LD_LIBRARY_PATH at compile or run time?

**Comment by IvanMalison** [comment]
looks like @hbons encountered this here shana/bindinator#26 that it somehow resolved itself.

**Comment by hbons** [comment]
Ah, I remember that thread. :) 

This is probably something related to how stuff is packaged in the distro. I suggest reaching out to the folks at Arch responsible for the GNOME/mono stuff. They're much more knowledgable about this stuff.

**Comment by hbons** [comment]
btw, I saw you comment on the other thread. If you just want to try out the latest changes, it's much easier to build the flatpak on your machine: https://github.com/hbons/org.sparkleshare.SparkleShare.

It takes a bit longer to build, but it's more likely succeed. You can change the branch you want to build in the .json manifest file.
