### ISSUE TITLE
dazzle.sh missing quotation mark

### ISSUE THREAD

**Issue by GotoDengo** [hbons/SparkleShare#1836]
### What happened:
Running `dazzle setup` on my Ubuntu-VPS throws the error:
``` 
syntax error near unexpected token 'fi'
/usr/bin/dazzle: line 208: '  fi'
```

Can be solved by putting the missing `"` at the end of line 50.

**Comment by vsviridov** [comment]
I posted a Pull Request in the dazzle repo and it's been merged. So, download again.

**Comment by GotoDengo** [comment]
Thanks
