### ISSUE TITLE
No help info available on --help

### ISSUE THREAD

**Issue by Ppjet6** [hbons/SparkleShare#1841]
Running Arch with flatpak and Sparkleshare 2.0.1

### What happened:
Version and Copyright got displayed

### What I expected to happen:
Some information about the commands available and their parameters. I know at least of `open` that could be added to this.

### This happens when:
1. `flatpak run org.sparkleshare.SparkleShare --help`

**Comment by hbons** [comment]
I've added some in this branch: https://github.com/hbons/SparkleShare/commit/231171ca5c22928c44b711dbe81c20d507fd93f4

Once it's merged (and the other bugs you filed are fixed :) you will see it.

**Comment by Ppjet6** [comment]
On 2018/05/04, Hylke Bons wrote:
> I've added some in this branch: https://github.com/hbons/SparkleShare/commit/231171ca5c22928c44b711dbe81c20d507fd93f4
> 
> Once it's merged (and the other bugs you filed are fixed :) you will see it.

Thanks!

-- 
Maxime “pep” Buquet
