### ISSUE TITLE
Icon missing on the top bar

### ISSUE THREAD

**Issue by stasiatrubitsyna** [hbons/SparkleShare#1845]
### What happened:
When I launch Sparkleshare the icon appears on the top bar, but it looks like the proper icon is missing. See the screenshot attached (I circled the icon I'm talking about with orange line).

### What I expected to happen:
I expected to see Sparkleshare icon instead of the wrong icon.

### This happens when:
This happens when I launch the application Sparkleshare version 1.5.0.
![_2018-05-18_18-24-30](https://user-images.githubusercontent.com/30405749/40243717-a13a4530-5ac9-11e8-8d57-00b1bb54ed05.png)

**Comment by hbons** [comment]
Is it possible to test version 2? 1.5 is pretty old now.

**Comment by stasiatrubitsyna** [comment]
I tried to install the flatpak version but couldn't because it requested gnome and I am on xfce.
I don't really want (or know how) to build from scratch.

**Comment by rob-hills** [comment]
@hbons this issue also affects Ubuntu 18.04 LTS using SparkleShare 2.x, except that I have no icon on the top bar at all.  If I hover over the correct "blank" spot on the top bar, the SS menu drops down.  I upgraded to the latest Flatpak version yesterday (3.28.0) but that hasn't fixed the problem.

**Comment by hbons** [comment]
Can you try the latest flatpak version? See my comments here:
https://github.com/hbons/SparkleShare/issues/1778#issuecomment-405030652

**Comment by hbons** [comment]
The fix is now on Flathub, you can install it from [here](https://flathub.org/apps/details/org.sparkleshare.SparkleShare). Run with `flatpak run org.sparkleshare.SparkleShare --status-icon=gtk`. Feel free to reopen if that doesn't work.
