### ISSUE TITLE
Wrong "recent changes" details

### ISSUE THREAD

**Issue by EugeneTM** [hbons/SparkleShare#1846]
21:54:07 | Environment | SparkleShare version: 1.5.0, Operating system: Unix (Unix 4.15.0.20)

### What happened
![2018-05-23 08-25-27](https://user-images.githubusercontent.com/6246479/40405549-b69a67d0-5e65-11e8-8825-82b2cfda562a.jpg)

### What I expected to happen

SparkleShare.txt

### This happens when:
1. Just installed and synced.

Thanks for reporting your issue or feature request, it helps lots!

**Comment by hbons** [comment]
This was recently fixed in master.
