### ISSUE TITLE
DAZZLE_USER is empty by default

### ISSUE THREAD

**Issue by EugeneTM** [hbons/SparkleShare#1847]
### What happened:
DAZZLE_USER is empty by default
#### Nice defaults
DAZZLE_USER="${DAZZLE_USER:-$MYUSER}"
DAZZLE_GROUP="${DAZZLE_GROUP:-$DAZZLE_USER}"

The script locks out SSHD, bringing a wrong entry to /etc/ssh/sshd_config. It also creates /home/.ssh, because "DAZZLEUSER" = "".

### What I expected to happen:
DAZZLE_USER=storage
DAZZLE_USER="${DAZZLE_USER:-$MYUSER}"
DAZZLE_GROUP="${DAZZLE_GROUP:-$DAZZLE_USER}"

### This happens when:
1. # dazzle setup

**Comment by hbons** [comment]
Thanks for reporting. This behaviour was reverted in https://github.com/hbons/Dazzle/issues/42.
