### ISSUE TITLE
How can I get a more recent release of SparkleShare on Mac?

### ISSUE THREAD

**Issue by gmacario** [hbons/SparkleShare#1849]
This is actually not a bug, rather a question:

As of today (2018-05-27) latest release is 2.0.1 which was released more than five months ago.

See related #1848

**Comment by gmacario** [comment]
I am not a Mac developer (just installed SparkleShare on my wife MacBook Pro), therefore not sure how I can help here, but just let me know.

**Comment by hbons** [comment]
Hi @gmacario. This is indeed the latest version. I'm aiming for two releases a year. :)
