### ISSUE TITLE
Flatpak version blocks forever on encrypted keys

### ISSUE THREAD

**Issue by ocrete** [hbons/SparkleShare#1868]
### What happened:

1. I started the Flatpak version of 3.28.0 because I need the indicator support because SparkleShare doesn't use a GNOME 3 design.
2. It creates a ssh key which I can't use, so I just put my existing key in the sparkleshare config directory.
3. When I try to clone the repo, it just freezes waiting for the password to unlock the key.. with no feedback (that's bad!)

### What I expected to happen:

1. It should just clone it.
2. It should use the system's ssh-agent (see https://github.com/flatpak/flatpak/issues/1438)

**Comment by hbons** [comment]
Sparkleshare used an ssh-agent before, but it never worked well. SparkleShare requires an unlocked key. 

Any reason why you can’t use the provided key?

**Comment by ocrete** [comment]
I feel that putting my key unlocked on the drive is a nasty security risk and I'm pretty sure it's very much against our corporate security policy. What problems did you have with ssh agent before?

**Comment by hbons** [comment]
I don’t recall what exactly, but most had to do with having a shared SSH configuration with other apps. There’s an issue open for storing the key in a secure store and only getting it when needed, but I’m not sure how much it would help as the key still needs to be read from disc for a short amount of time.

**Comment by hbons** [comment]
Duplicate of #1780.
