### ISSUE TITLE
SparkleShare 2.0.1 and OSX Mojave

### ISSUE THREAD

**Issue by markusstoll** [hbons/SparkleShare#1872]
### What happened:
is not starting

I get this error:

[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
  at System.String.Substring (System.Int32 startIndex, System.Int32 length) [0x0004a] in <5357e6452d21439088fd8589dfcf1134>:0 
  at Sparkles.InstallationInfo.MacOSVersion () [0x00039] in <e4ce89a63d7c45f0baebe5a36aca1841>:0 
  at SparkleShare.BaseController.Initialize () [0x00079] in <431f4724be5840a2bdac0ac223371386>:0 
  at SparkleShare.Controller.Initialize () [0x00000] in <431f4724be5840a2bdac0ac223371386>:0 
  at SparkleShare.SparkleShare.Main (System.String[] args) [0x00119] in <431f4724be5840a2bdac0ac223371386>:0

**Comment by markusstoll** [comment]
i wanted to look into this as its obviously a minor bug. But how am I supposed to work in this?

latest Xamarin Studio for Mac is crashing on this project (on Mojave) and latest Visual Studio for Mac does not compile this project (neither branch master nor release/2.0.1)

Any hints?

**Comment by hbons** [comment]
Thanks for looking into this. What error do you get trying to compile?

**Comment by markusstoll** [comment]
on release/2.0.1 I get:

/Daten/GIT/SparkleShare/SparkleShare/Mac/Assets.xcassets/AppIcon.appiconset/Contents.json: Error: File not found: /Daten/GIT/SparkleShare/SparkleShare/Mac/Assets.xcassets/AppIcon.appiconset/Contents.json (SparkleShare.Mac)

on master I get:

/Daten/GIT/SparkleShare/SparkleShare/Mac/MainMenu.xib: Error: 2018-09-28 11:31:35.859 ibtoold[30031:1440142] [MT] DVTPlugInLoading: Failed to load code for plug-in com.apple.dt.IDE.IDEInterfaceBuilderAppleTVIntegration (/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin), error = Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration
  Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration, NSDebugDescription=dlopen_preflight(/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration
  Reason: image not found, NSBundlePath=/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin, NSLocalizedDescription=The bundle “IDEInterfaceBuilderAppleTVIntegration” couldn’t be loaded because it is damaged or missing necessary resources.}, dyldError = dlopen(/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration, 0): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration
  Reason: image not found
2018-09-28 11:31:35.859 ibtoold[30031:1440142] [MT] DVTPlugInExtensionFaulting: Failed to fire fault for extension Xcode.InterfaceBuilderKit.AppleTVIntegration.ConfigurationList: Error Domain=DVTPlugInErrorDomain Code=2 "Loading a plug-in failed." UserInfo={DVTPlugInIdentifierErrorKey=com.apple.dt.IDE.IDEInterfaceBuilderAppleTVIntegration, DVTPlugInExecutablePathErrorKey=/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration, NSLocalizedRecoverySuggestion=The plug-in or one of its prerequisite plug-ins may be missing or damaged and may need to be reinstalled., DVTPlugInDYLDErrorMessageErrorKey=dlopen(/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration, 0): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration
  Reason: image not found, NSLocalizedDescription=Loading a plug-in failed., NSFilePath=/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin, NSLocalizedFailureReason=The plug-in “com.apple.dt.IDE.IDEInterfaceBuilderAppleTVIntegration” at path “/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin” could not be loaded.  The plug-in or one of its prerequisite plug-ins may be missing or damaged., NSUnderlyingError=0x7fd0165ea0b0 {Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration
  Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration, NSDebugDescription=dlopen_preflight(/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin/Contents/MacOS/IDEInterfaceBuilderAppleTVIntegration
  Reason: image not found, NSBundlePath=/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/IDEInterfaceBuilderAppleTVIntegration.ideplugin, NSLocalizedDescription=The bundle “IDEInterfaceBuilderAppleTVIntegration” couldn’t be loaded because it is damaged or missing necessary resources.}}}
2018-09-28 11:31:35.862 ibtoold[30031:1440142] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error getting value for parameter key 'class' of extension 'Xcode.InterfaceBuilderKit.AppleTVIntegration.ConfigurationList' in plug-in 'com.apple.dt.IDE.IDEInterfaceBuilderAppleTVIntegration''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3620f571 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff621bcefb objc_exception_throw + 48
	2   DVTFoundation                       0x00000001049b734c -[DVTExtensionParameter valueForKey:error:] + 0
	3   Foundation                          0x00007fff38515864 -[NSArray(NSKeyValueCoding) valueForKey:] + 430
	4   Foundation                          0x00007fff3855f816 -[NSArray(NSKeyValueCoding) valueForKeyPath:] + 436
	5   Foundation                          0x00007fff384dbee3 -[NSObject(NSKeyValueCoding) valueForKeyPath:] + 260
	6   IDEInterfaceBuilderKit              0x0000000103fd9f6b -[IBPlatform matchesExtension:] + 50
	7   IDEInterfaceBuilderKit              0x0000000103fda107 __42-[IBPlatform extensionsForExtensionPoint:]_block_invoke + 27
	8   IBFoundation                        0x00000001050696ee -[NSSet(IBSetAdditions) ib_setByFilteringUsingBlock:] + 258
	9   IDEInterfaceBuilderKit              0x0000000103fda0c5 -[IBPlatform extensionsForExtensionPoint:] + 201
	10  IDEInterfaceBuilderKit              0x0000000103fd91c3 -[IBPlatform registerMemberConfigurationVariables] + 166
	11  IDEInterfaceBuilderKit              0x0000000104115304 -[IBScopedSingletonRegistry init] + 1350
	12  IDEInterfaceBuilderKit              0x0000000104114da4 __43+[IBScopedSingletonRegistry sharedInstance]_block_invoke + 41
	13  libdispatch.dylib                   0x00007fff63234dcb _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00007fff63236511 _dispatch_once_callout + 20
	15  IDEInterfaceBuilderKit              0x0000000104114d78 +[IBScopedSingletonRegistry sharedInstance] + 45
	16  IDEInterfaceBuilderKit              0x0000000103f2a0a0 -[IBInterfaceBuilderPlugin init] + 146
	17  IDEInterfaceBuilderKit              0x0000000103f29ff4 +[IBInterfaceBuilderPlugin ide_initializeWithOptions:error:] + 34
	18  IDEFoundation                       0x000000010537d789 _IDEInitializeOnePlugInAndPrerequisites + 2324
	19  IDEFoundation                       0x000000010537d090 _IDEInitializeOnePlugInAndPrerequisites + 539
	20  IDEFoundation                       0x000000010537d090 _IDEInitializeOnePlugInAndPrerequisites + 539
	21  IDEFoundation                       0x000000010537bfe6 _IDEInitializePlugIns + 1598
	22  IDEFoundation                       0x000000010537b3f3 IDEInitialize + 8444
	23  ibtoold                             0x0000000103c105b0 IBIDEInitialize + 52
	24  ibtoold                             0x0000000103c0f6dc main + 1744
	25  libdyld.dylib                       0x00007fff63283085 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException (SparkleShare.Mac)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(3,3): Error: ibtool exited with code 134 (SparkleShare.Mac)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(3,3): Error: Failed to load ibtool log file `obj/Debug/ibtool-manifests/MainMenu.nib`: Failed to parse PList data type:  (SparkleShare.Mac)

**Comment by markusstoll** [comment]
addon: and ibtool is opening a standard OSX crash report (on building master)

**Comment by markusstoll** [comment]
see pull request #1873
was able to compile using visual studio (still struggling with that, currently compiles only as Debug with my setup)

**Comment by hbons** [comment]
No special setup for me... Just VS for Mac on High Sierra.
