### ISSUE TITLE
Cannot fetch repository

### ISSUE THREAD

**Issue by novakmi** [hbons/SparkleShare#1892]
I was using old version of SparkleShare, now I'm trying to migrate to new one.

Installed with `flatpack`  (Xubuntu 18.10)

```
flatpak install flathub org.sparkleshare.SparkleShare
```

Version:
```
10:58:16 Environment | SparkleShare 3.28.0
10:58:16 Environment | Git LFS 2.5.2
10:58:16 Environment | Git 2.19.1
10:58:16 Environment | GNOME (Linux 4.19.16.41916)
```

### What happened:
When fetching project from `gitlab`, fetch failed
```
10:59:12 Fetcher | /home/novak/.config/org.sparkleshare.SparkleShare/tmp/sparkle.git | Fetching folder: ssh://git@gitlab.com/novakmi/sparkle.git
10:59:12 Auth | Fetching host key for gitlab.com
10:59:12 Cmd | ssh-keyscan -t rsa -p 22 gitlab.com
10:59:18 Auth | Fingerprint matches
10:59:18 Auth | Accepted host key for gitlab.com
10:59:18 Cmd | tmp | git ls-remote --heads "ssh://git@gitlab.com/novakmi/sparkle.git"
10:59:20 Fetcher | Failed
```
There is no indication what is wrong.

The command (run in shell) seems to work
```
$ git ls-remote --heads "ssh://git@gitlab.com/novakmi/sparkle.git"
400fafb1b5367d30ef5d76dc8f894a1b960ccca3	refs/heads/master
$ echo $?
0
```

(same problem seems to be with `github.com` for me)

### What I expected to happen:

repository is fetched

Thanks for any help.

**Comment by hbons** [comment]
Have you uploaded the new computer ID? The flatpak version is a separate app, so uses a new ID.

**Comment by novakmi** [comment]
Thanks. 

I did not realize ssh key (computer ID) is needed. At least I didn't setup any for older version (system key was probably used). 

Now it works :-).  I'm closing the issue.
