### ISSUE TITLE
No files updates on ubuntu 18.04 machines

### ISSUE THREAD

**Issue by frepie** [hbons/SparkleShare#1905]
I have 3 machines that run sparkleshare: machine1 is ubuntu v16.04 and machine2 and machine3 are ubuntu v18.04. 
All connect to the sparkleshare server running Ubuntu 18.04 SERVER. 
Machine1 connects normally and updates with the server. 

Both 18.04 clients however do not update their sparkleshare folders. 

I uninstalled and reinstalled sparkleshare on machine2 and this is what happens when trying to connect to the server:

![SparkleShare Setup_004](https://user-images.githubusercontent.com/37632265/58385570-53546900-7fc0-11e9-8858-0add66805d4f.png)

![SparkleShare Setup_005](https://user-images.githubusercontent.com/37632265/58385572-564f5980-7fc0-11e9-8769-81cf93859f00.png)

The "adding project" process  never ends.

These are the logs for that machine2:

`15:40:20 | Environment | SparkleShare version: 1.5.0, Operating system: Unix (Unix 4.15.0.50)
15:40:24 | Auth | Imported key '/home/frepie/.config/sparkleshare/2019-05-11_15h01.key'
15:40:24 | Auth | The following keys may be used:
4096 SHA256:5+g8joQedr1Lhk6w2Q9MWtdOxgA5cfRXXAwvZ3YlB84 /home/frepie/.config/sparkleshare/2019-05-11_15h01.key (RSA)
15:40:28 | Avatars | Invalid certificate for https://www.gravatar.com/
15:40:28 | Avatars | Error fetching avatar for frepie@gmail.com: Error: TrustFailure (The authentication or decryption has failed.)   at System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) [0x0008a] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Net.WebClient.DownloadData (System.Uri address) [0x00029] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Net.WebClient.DownloadData (System.String address) [0x00019] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at (wrapper remoting-invoke-with-check) System.Net.WebClient:DownloadData (string)
  at SparkleShare.SparkleAvatars.GetAvatar (System.String email, System.Int32 size, System.String target_path) [0x0016f] in <5fddc956b41e4e8c85e8326eae4fa80c>:0 
13:29:07 | Fetcher | /home/frepie/SparkleShare/.tmp/fp2 | Fetching folder: ssh://storage@192.168.1.4:22/home/storage/fp2
13:29:07 | Auth | Fetching host key for 192.168.1.4
13:29:07 | Cmd | ssh-keyscan -t rsa -p 22 192.168.1.4
`

**Comment by topassg** [comment]
I seem to have the same Problem on a kubuntu 18.04.
The log stops at the same place, the keyscan, and I find defunct ssh-keyscan processes listed afterwards.

**Comment by hbons** [comment]
You seem to be using 1.5.0 which is a very old version. I recommend trying the latest from flathub.org.
