### ISSUE TITLE
The version of SparkleShare for Windows remain 1.4

### ISSUE THREAD

**Issue by Hansanshi** [hbons/SparkleShare#1909]
Could you please provide newer version (the newest version should be 3.28) of SparkleShare for Windows on your offical website.

**Comment by sveeke** [comment]
To add to/confirm this, the client itself says that there is a much newer version available: 

![image](https://user-images.githubusercontent.com/12334213/60689931-4f1a4600-9eb2-11e9-9955-7181f3f73796.png)

But I indeed can't find >1.4 on the website.

**Comment by linsui** [comment]
There is 1.5 on bitbucket https://bitbucket.org/hbons/sparkleshare/downloads/sparkleshare-windows-1.5.msi , though it's still too old.

**Comment by Adamanthus** [comment]
You need to download the latest release from here (Github) and compile it yourself

**Comment by Adamanthus** [comment]
You need to download the latest release from here (Github) and compile it yourself it seems...

**Comment by Hansanshi** [comment]
> You need to download the latest release from here (Github) and compile it yourself it seems...

I tried and failed😂.
Some file(.sln) is missing, according to log info of the console

**Comment by Hansanshi** [comment]
Need your help @hbons

**Comment by hbons** [comment]
The Windows version is currently not compiling because so much in the app has changed, but the UI needs updating on the platform. I've no interest in doing this at this point. So unless someone comes around to maintain the Windows UI, 1.4 will be the last version.

**Comment by Hansanshi** [comment]
a pity but thanks ：）

**Comment by AvtechScientific** [comment]
related: 
https://github.com/hbons/SparkleShare/issues/1924
