### ISSUE TITLE
Fetcher | Failed

### ISSUE THREAD

**Issue by frepie** [hbons/SparkleShare#1910]
Trying to add a project to my client and here is the message I get:

`19:31:56 Environment | SparkleShare 3.28.0 (Flatpak)
19:31:56 Environment | Git LFS 2.4.0
19:31:56 Environment | Git 2.17.0
19:31:56 Environment | Ubuntu (Linux 4.15.0.54)
19:31:56 Cmd | gio set "/home/frepie/SparkleShare" metadata::custom-icon-name org.sparkleshare.SparkleShare
19:31:56 Environment | GTK+ 3.22.30
19:31:56 Environment | Status Icon: AppIndicator
19:34:46 Fetcher | /home/frepie/.config/org.sparkleshare.SparkleShare/tmp/fp2 | Fetching folder: ssh://storage@192.168.1.4/home/storage/fp2
19:34:46 Auth | Fetching host key for 192.168.1.4
19:34:46 Cmd | ssh-keyscan -t rsa -p 22 192.168.1.4
19:34:47 Auth | Skipping fingerprint check
19:34:47 Cmd | tmp | git ls-remote --heads "ssh://storage@192.168.1.4/home/storage/fp2"
19:34:47 Fetcher | Failed
`
Client: unbuntu 16.04
Server Ubuntu 18.04 server

Thanks

**Comment by OJezu** [comment]
Same here.

**Comment by OJezu** [comment]
I had to restart SparkleShare, a new public key was generated, and once I copied a new one over, the files synced

**Comment by frepie** [comment]
What do you mean  "Restart" ? 
Rebooting the computer has no effect. Uninstall and reinstall Sparkleshare?

**Comment by frepie** [comment]
Made a brand new install on both server and client. 
OS is 

- ubuntu 18.04 Server on the server
-ubuntu 18.04 on client

I uninstalled Sparkleshare on both, deleted the .ssh folder on the server, deleted ~/.config/org.sparkleshare.SparkleShare folder, reinstalled on both, linked my client to the server but still not working.
This is the log 

 `~/.config/org.sparkleshare.SparkleShare/logs$ cat log_2019-12-28.2.txt 
20:49:43 Environment | SparkleShare 3.28.0 (Flatpak)
20:49:43 Environment | Git LFS 2.4.0
20:49:43 Environment | Git 2.17.0
20:49:43 Environment | Ubuntu (Linux 4.15.0.72)
20:49:43 Cmd | gio set "/home/frepie/SparkleShare" metadata::custom-icon-name org.sparkleshare.SparkleShare
20:49:43 Environment | GTK+ 3.22.30
20:49:43 Environment | Status Icon: AppIndicator
20:50:09 Fetcher | /home/frepie/.config/org.sparkleshare.SparkleShare/tmp/fp2 | Fetching folder: ssh://storage@192.168.1.4/home/storage/fp2
20:50:09 Auth | Fetching host key for 192.168.1.4
20:50:09 Cmd | ssh-keyscan -t rsa -p 22 192.168.1.4
20:50:09 Auth | Skipping fingerprint check
20:50:09 Cmd | tmp | git ls-remote --heads "ssh://storage@192.168.1.4/home/storage/fp2"
20:50:09 Fetcher | Failed
`
I can access my server via ssh without problems.
