### ISSUE TITLE
How does SparkleShare work with git?

### ISSUE THREAD

**Issue by AtomicNess123** [hbons/SparkleShare#1944]
Specifically, if my SparkleShare local folder gets synced with Githhub, do I need to push at all, or just commit?

**Comment by jnm** [comment]
Doesn't SparkleShare handle all the pushing _and_ committing automatically? Unless you're doing something fancy, you don't have to interact with Git directly.

**Comment by nekohayo** [comment]
Sparkleshare is automatic, yes. As the question is answered, I would recommend closing this ticket.
