### ISSUE TITLE
github.com RSA SSH host key changed again, March 24 2023

### ISSUE THREAD

**Issue by mbg-unsw** [hbons/SparkleShare#2004]
I see this was already reported in #1998 and fixed in 6cfd602 but the fingerprint I get is different to the one in the commit.

Please see PR #2003 for the change to Presets/github.xml that works for me.

As for the older issue, for details of the change see https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

And support page listing all keys: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints.

**Comment by macedd** [comment]
Both Github and Gitlab currently has bad `fingerprint`.

**Comment by hbons** [comment]
Fixed by #2003 and aa17cb36ba6a6116ea1801116d388167ddf3a281.

**Comment by hbons** [comment]
SparkleShare now has an experimental CLI and support for ED25519 (the new default) keys: https://github.com/hbons/Twinkle.

If you like this work and want to support development, I’m looking for sponsors since I’m currently jobless: https://github.com/sponsors/hbons.
