### ISSUE TITLE
ssh_askpass: exec /usr/libexec/ssh-askpass : No such file or directory

### ISSUE THREAD

**Issue by steamynicks** [hbons/SparkleShare#304]
Not sure if this is the correct place to post this issue.  If not, a public flogging and any recommendation of where to search is appreciated.

I've setup my Mac OS 10.6.8 as a client and ubuntu 11.04 as the server according to this page (using the client portion of Mac OS documentation, and the Server portion of Ubuntu documentation):

https://github.com/hbons/SparkleShare/wiki/How-to-set-up-your-own-server

I can successfully ssh from the Mac into the linux server using the ssh keys (doesn't ask for a password), but when I try to setup a remote folder in SparkleShare, SparkleShare says there's something wrong.

Here's my Mac OS syslog while trying to connect:

Aug  3 22:51:49 my-macbook [0x0-0x71071].org.sparkleshare.sparkleshare[3308]: ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory
Aug  3 22:51:49 my-macbook [0x0-0x71071].org.sparkleshare.sparkleshare[3308]: Permission denied, please try again.
Aug  3 22:51:49 my-macbook [0x0-0x71071].org.sparkleshare.sparkleshare[3308]: ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory
Aug  3 22:51:49 my-macbook [0x0-0x71071].org.sparkleshare.sparkleshare[3308]: Permission denied, please try again.
Aug  3 22:51:49 my-macbook [0x0-0x71071].org.sparkleshare.sparkleshare[3308]: ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory
Aug  3 22:51:49 my-macbook [0x0-0x71071].org.sparkleshare.sparkleshare[3308]: Permission denied (publickey,password).
Aug  3 22:51:49 my-macbook [0x0-0x71071].org.sparkleshare.sparkleshare[3308]: fatal: The remote end hung up unexpectedly
Aug  3 22:51:49 my-macbook [0x0-0x71071].org.sparkleshare.sparkleshare[3308]: 22:51:49 [Git] Exit code 128
Aug  3 22:51:49 my-macbook [0x0-0x71071].org.sparkleshare.sparkleshare[3308]: 22:51:49 [Fetcher] Failed
Aug  3 22:51:49 my-macbook [0x0-0x71071].org.sparkleshare.sparkleshare[3308]: 22:51:49 [Fetcher] Enabled host key checking

I don't see /usr/libexec in either my Mac or the linux machine.

I've searched using the title of my post, and see several entries that refer to this, but many with no answer, some that it mysteriously clears up, and one that resets .ssh folder permissions, which I tried to no avail (chmod 700 .ssh, chmod 644 .ssh/authorized_keys on both machines).

--Cheers

**Comment by gtzpower** [comment]
I fought this error for an entire day.  Rebooting didn't fix it for me.  I finally figured out that I had to re-add my SSH identity:
$ ssh-add ~/.ssh/id_rsa

**Comment by dzintars** [comment]
In my case problem was in `~/.ssh/known_hosts` as i accidentally deleted hosts and their signatures.
[This SO](https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository) helped to me.
