### ISSUE TITLE
Feature request: readonly checkout

### ISSUE THREAD

**Issue by ways** [hbons/SparkleShare#339]
If I try to add a github repo like "hbons/SparkleShare", I will get an error. I assume this is because I have no write access to the repo.

Could it be possible to allow checkout anyway, but read only? So that one will get updates when stuff happens on the project of interest.

**Comment by hbons** [comment]
SparkleShare now has an experimental CLI and readonly mode: https://github.com/hbons/Twinkle.

If you like this work and want to support development, I’m looking for sponsors since I’m currently jobless: https://github.com/sponsors/hbons.
