### ISSUE TITLE
Support git annex for large repos

### ISSUE THREAD

**Issue by alucard2511** [hbons/SparkleShare#385]
Hello,
I'm working on SparkleShare and I've a question. The size of the folder .git grows bigger after a time of usage or after many time of deleting big files. I've a repository with 600MB of working data and 2GB of folder .git. 
As I know that's because the Git system keeps  in the folder .git  the old versions of my files even the deleted files. I have searched on internet for deleting the old history of the repository GIT by the command "git filter-branch" and "git rebase".

But when I can delete the old history on the remote repository, It seem that I have to re-synchronise all the repository (it's like i have to clone a new repository again) because the repository became totally different, the tree and all the hash of commit change.

Do you have any solution to delete the old history in the repository without re-clone all repository again?

Thank you in advance for your response.

**Comment by burdges** [comment]
It's worth mentioning the Git Large File Storage project by GitHub itself : https://github.com/github/git-lfs  https://github.com/blog/1986-announcing-git-large-file-storage-lfs

**Comment by hbons** [comment]
@burdges yep. integrating LFS is the current plan.

**Comment by niftylettuce** [comment]
@hbons Awesome!

**Comment by niftylettuce** [comment]
So you'll modify Dazzle to act as <https://github.com/github/lfs-test-server> too? @hbons
