### ISSUE TITLE
Customize folder icon in favorites sidebar

### ISSUE THREAD

**Issue by alexschomb** [hbons/SparkleShare#624]
Although it is a very minor issue and certainly nothing important I'd like to at least mention it.
This applies to Mac and Windows, haven't tested Linux yet. When the DropBox folder is added to the favorites sidebar of Windows or Mac the icon of the folder is customized. For SparkleShare just a simple folder icon is shown.

Some screenshots:
![Mac](http://img718.imageshack.us/img718/9177/bildschirmfoto20120312u.png)
![Windows](http://img860.imageshack.us/img860/9177/bildschirmfoto20120312u.png)

**Comment by ErHimanshuK** [comment]
> I'm closing this now. On Mac I'm still waiting for some API bindings to even be able to add the folder to the sidebar (the code is already written). That's before we can even look at the coloured icons.

@hbons have you find any solution on this?
