### ISSUE TITLE
[FEATURE REQUEST] sparkleshare daemon

### ISSUE THREAD

**Issue by mathroc** [hbons/SparkleShare#786]
apparently it's not possible to build sparkleshare without gui.
is it planned? it could be really useful to use it in server. I intended to use it to synchronize my sandbox folder on my web server to share easily experiments with html/js/css. and I'm sure there is a lot of other use cases (eg: backup of config files)

what do you think?

**Comment by hbons** [comment]
SparkleShare now has an experimental CLI mode: https://github.com/hbons/Twinkle.

If you like this work and want to support development, I’m looking for sponsors since I’m currently jobless: https://github.com/sponsors/hbons.
